flake.nix
The add-from-github script depends on some gnutar specific wildcard behaviour and otherwise fails on run on macOS.
Closes #17.
=> Make sure we have gnutar in scope

_sources/ekg-json/0.1.0.7.0.0.0.0.1/meta.toml
From https://github.com/vshabanov/ekg-json at 00ebe7211c981686e65730b7144fbf5350462608
This is the version used by `cardano-node`. It seems the maintainer is totally unresponsive, so this is unlikely to be resolved soon.
=> Added ekg-json-0.1.0.7.0.0.0.0.1

README.md
Not needed, and it makes it easier for people to get the wrong URL when constructing the `inputMap` which makes things not work.
=> Don't put a slash at the end of the url

_sources/ekg-forward/0.2.0/meta.toml
From https://github.com/input-output-hk/ekg-forward at 9c92060de57d91f69c6792489489598991313901
This is the version being used in `cardano-node` now, I got the version bumped upstream: https://github.com/input-output-hk/ekg-forward/pull/10
=> Added ekg-forward-0.2.0

_sources/flat/0.4.4.0.0.0.0.2/meta.toml
From https://github.com/input-output-hk/flat at 3bd82065ec7f8f253bcb18832b200dbf07707a3b
Needed for 9.2 support.
=> Added flat-0.4.4.0.0.0.0.2

_sources/moo/1.2.0.0.0.0.1/meta.toml
From https://github.com/input-output-hk/moo at 8c487714fbfdea66188fcb85053e7e292e0cc348
It has a duplicate package stanza which means it breaks with cabal-3.8. The dependency has been removed from the ledger, but still exists for the currently-released versions, so it's worth patching it here.
=> Added moo-1.2.0.0.0.0.1

_sources/cardano-api/1.35.3/meta.toml, _sources/cardano-cli/1.35.3/meta.toml, _sources/cardano-git-rev/0.1.0.0/meta.toml, _sources/cardano-node/1.35.3/meta.toml, _sources/cardano-submit-api/3.1.2/meta.toml, _sources/cardano-testnet/1.35.3/meta.toml, _sources/trace-dispatcher/1.29.0/meta.toml, _sources/trace-forward/0.1.0/meta.toml, _sources/trace-resources/0.1.0.0/meta.toml
This releases the packages from `cardano-node` at 1.35.3. I chose the packages that `plutus-apps` pulls in.
This will let downstream packages start building on CHaP. I tested it locally, and I could build `cardano-api` as long as I pulled in the constraints from the `cabal.project` in https://github.com/input-output-hk/cardano-node/pull/4540
We probably don't want to merge this PR until the above PR to the node is merged.
=> Release cardano-node packages at 1.35.3

_sources/cardano-crypto-class/2.0.0.0.1/meta.toml
Needed for SECP release without having to refactor the heapwords changes into ledger.
From https://github.com/input-output-hk/cardano-base at cc049d7c9b9a0129c15b1355fd1dff9e1a1a551c
=> Added cardano-crypto-class-2.0.0.0.1

_sources/ouroboros-consensus-cardano-tools/0.1.0.0/meta.toml
Gives us db-synthesizer tool with append mode useful for network respins.
From https://github.com/input-output-hk/ouroboros-network at 80832bab975422800a521d16bce5aa90c6749b3c
=> Added ouroboros-consensus-cardano-tools-0.1.0.0

_sources/cardano-client/0.1.0.1/meta.toml, _sources/cardano-crypto-praos/2.0.0.0.1/meta.toml, _sources/cardano-crypto-tests/2.0.0.0.1/meta.toml, _sources/monoidal-synchronisation/0.1.0.1/meta.toml, _sources/network-mux/0.1.0.1/meta.toml, _sources/ouroboros-consensus-byron-test/0.1.0.1/meta.toml, _sources/ouroboros-consensus-byron/0.1.0.1/meta.toml, _sources/ouroboros-consensus-byronspec/0.1.0.1/meta.toml, _sources/ouroboros-consensus-cardano-test/0.1.0.1/meta.toml, _sources/ouroboros-consensus-cardano-tools/0.1.0.1/meta.toml, _sources/ouroboros-consensus-cardano/0.1.0.1/meta.toml, _sources/ouroboros-consensus-mock-test/0.1.0.1/meta.toml, _sources/ouroboros-consensus-mock/0.1.0.1/meta.toml, _sources/ouroboros-consensus-protocol/0.1.0.1/meta.toml, _sources/ouroboros-consensus-shelley-test/0.1.0.1/meta.toml, _sources/ouroboros-consensus-shelley/0.1.0.1/meta.toml, _sources/ouroboros-consensus-test/0.1.0.1/meta.toml, _sources/ouroboros-consensus/0.1.0.1/meta.toml, _sources/ouroboros-network-framework/0.1.0.1/meta.toml, _sources/ouroboros-network-testing/0.1.0.1/meta.toml, _sources/ouroboros-network/0.1.0.1/meta.toml
Need to include a couple more packages from base for the 2.0.0.0.1 version
Need a bug fix in consensus that prevents the intra-era hard fork from occurring
=> dependency bumps for node 1.35.4

.github/workflows/CI.yml
Fixes #13.
This adds a build step to the workflow. The built repository is uploaded as an artifact, which can then be downloaded by the `deploy` job if that runs (i.e. only on master). That gets us two things:
1. The built repository is available as a build artifact, which is possibly useful for debugging.
2. It gives us a place to put checks that need a built repository, like the archive extension check in #75.
=> Add a separate build workflow step

.github/workflows/CI.yml, scripts/check-archive-extension.sh
I didn't have time to set this up in the GHA, it's changed a bit and I'm not sure what's going on right now. Maybe you can take a look @andreabedini ?
I tested this a bit and it seems to do the job. I tried:
- Adding a package with an old timestamp (BAD)
- Adding a package with a new timestamp (GOOD)
- Removing a package (BAD)
- Changing the timestamp of a package (BAD)
=> Add script to check whether the newly built archive is an extension of the previous one

_sources/network-mux/0.2.0.0/meta.toml, _sources/ouroboros-consensus/0.1.0.2/meta.toml, _sources/ouroboros-network-framework/0.2.0.0/meta.toml, _sources/ouroboros-network/0.2.0.0/meta.toml
- Added network-mux-0.2.0.0
- Added ouroboros-network-0.2.0.0
- Added ouroboros-network-framework-0.2.0.0
- Added ouroboros-consensus-0.1.0.2
=> Release `ouroboros-network` packages for `cardano-node-1.35.5`

.github/PULL_REQUEST_TEMPLATE.md, CODEOWNERS, README.md
I think this is a reasonably sane way to do access control. As a trial, I'm just going to set it up to request reviews from the listed people, but not to require them. We may want to make it a requirement in future.
Thus far I've added what I think is correct for `plutus`, `ledger`, `ouroboros-consensus`, and the patched pacakges. I don't know who or what to put for `cardano-node`, ideally there would be a team (Jordan?).
It would be great to find people for the other repositories in here.
I've also added some commentary to the README suggesting when people should add themselves to CODEOWNERS.
Work towards #33.
@disassembler maybe the release team should also be listed everywhere?
@coot I added the teams that are listed in the `ouroboros-network` CODEOWNERS but I can't find them anywhere …
=> Start a CODEOWNERS file

CODEOWNERS, _sources/hydra-cardano-api/0.8.0/meta.toml
Basically the same as https://github.com/input-output-hk/cardano-haskell-packages/pull/65, but this time the `cardano-api` is on CHaP and this is buildable without any `source-repository-package`s.
=> Add hydra-cardano-api 0.8.0

_sources/ouroboros-consensus/0.1.0.3/meta.toml, _sources/ouroboros-network/0.3.0.0/meta.toml
For `cardano-node-1.35.5` release.
- Added ouroboros-network-0.3.0.0
- Added ouroboros-consensus-0.1.0.3
=> ouroboros-network-0.3.0.0

README.md
I noticed you can pass full package-ids (name-version) to `extra-packages` which simplifies the syntax a bit.
=> Update instructions to test in isolation

scripts/version-lookup.sh
The following command extracts version information of CHaP dependencies for a project as a JSON file.  The `plan.json` for the project must have already been generated.
```
cardano-node $ ../cardano-haskell-packages/scripts/version-lookup.sh
[
{
"timestamp": "2022-10-17T00:00:00Z",
"github": {
"repo": "input-output-hk/Win32-network",
"rev": "3825d3abf75f83f406c1f7161883c438dac7277d"
},
"package": {
"name": "Win32-network",
"version": "0.1.0.0"
}
},
...
{
"timestamp": "2022-10-17T00:00:00Z",
"github": {
"repo": "input-output-hk/plutus",
"rev": "a56c96598b4b25c9e28215214d25189331087244"
},
"subdir": "word-array",
"package": {
"name": "word-array",
"version": "0.1.0.0"
}
}
]
```
Requires `yq` and `yj` to be installed.
=> Script for extracting version information from CHaP package dependencies of a project

flake.lock, flake.nix
These changes reduce the closure size of devShell.default from 576.3M to 192.2M
* use the same nixpkgs from foliage, sharing is caring
* switch from `mkShell` to `mkShellNoCC` because we don't need a compiler
=> Reduce devShell closure size

_sources/contra-tracer/0.1.0.1/meta.toml, _sources/iohk-monitoring/0.1.11.1/meta.toml, _sources/tracer-transformers/0.1.0.2/meta.toml
=> Add iohk-monitoring-framework packages required by cardano-node.

.github/workflows/CI.yml
Cuts down on our CI time a bit.
=> Use foliage parallel building

.github/workflows/CI.yml
This seems to be the way to avoid getting double workflow runs on PRs
while still getting the other behaviour we want.
=> Only trigger the CI workflow on push if the push is to master

CODEOWNERS, _sources/ouroboros-consensus-byron-test/0.2.0.0/meta.toml, _sources/ouroboros-consensus-byron/0.2.0.0/meta.toml, _sources/ouroboros-consensus-byronspec/0.2.0.0/meta.toml, _sources/ouroboros-consensus-cardano-test/0.2.0.0/meta.toml, _sources/ouroboros-consensus-cardano-tools/0.2.0.0/meta.toml, _sources/ouroboros-consensus-diffusion/0.2.0.0/meta.toml, _sources/ouroboros-consensus-mock-test/0.2.0.0/meta.toml, _sources/ouroboros-consensus-mock/0.2.0.0/meta.toml, _sources/ouroboros-consensus-protocol/0.2.0.0/meta.toml, _sources/ouroboros-consensus-shelley-test/0.2.0.0/meta.toml, _sources/ouroboros-consensus-shelley/0.2.0.0/meta.toml, _sources/ouroboros-consensus-test/0.2.0.0/meta.toml, _sources/ouroboros-consensus/0.2.0.0/meta.toml
Tagging after the merge of [this PR](https://github.com/input-output-hk/ouroboros-network/pull/4353). See the [change](https://github.com/input-output-hk/ouroboros-network/blob/master/ouroboros-consensus/CHANGELOG.md)[logs](https://github.com/input-output-hk/ouroboros-network/blob/master/ouroboros-consensus-cardano/CHANGELOG.md) for details.
=> Release ouroboros-consensus 0.2.0.0

_sources/monoidal-synchronisation/0.1.0.2/meta.toml
From https://github.com/input-output-hk/ouroboros-network at aff4ef4a043a70ceb38002f1c4ac57d729139350
=> Added monoidal-synchronisation-0.1.0.2

.github/workflows/CI.yml, flake.lock
Bump foliage to support package metadata. Passing to foliage the option `--write-metadata` makes foliage write out a file `_repo/foliage/packages.json` containing metadata about the package provenance. This can be used by downstream tools.
```
[
{
"pkg-name": "Win32-network",
"pkg-version": "0.1.0.0",
"timestamp": "2022-10-17T00:00:00Z",
"url": "github:input-output-hk/Win32-network/3825d3abf75f83f406c1f7161883c438dac7277d"
},
{
"pkg-name": "Win32-network",
"pkg-version": "0.1.1.0",
"timestamp": "2022-10-25T00:00:00Z",
"url": "github:input-output-hk/Win32-network/4ed1f5dc22754e4e461cfc6901fd5eebe34541f4"
},
{
"forced-version": true,
"pkg-name": "Win32-network",
"pkg-version": "0.1.1.1",
"timestamp": "2023-01-03T09:34:24Z",
"url": "github:input-output-hk/Win32-network/1521906427571afd64670c2 …
```
=> Bump foliage to support package metadata

_sources/cardano-binary-test/1.4.0.0/meta.toml, _sources/cardano-binary/1.6.0.0/meta.toml, _sources/cardano-crypto-class/2.1.0.0/meta.toml, _sources/cardano-crypto-praos/2.1.1.0/meta.toml, _sources/cardano-crypto-tests/2.1.0.0/meta.toml, _sources/cardano-strict-containers/0.1.2.0/meta.toml
This release includes:
* `cardano-crypto-praos-2.1.1.0`
* `cardano-crypto-tests-2.1.0.0`
* `cardano-crypto-class-2.1.0.0`
* `cardano-binary-1.6.0.0`
* `cardano-binary-test-1.4.0.0`
* `cardano-strict-containers-0.1.2.0`
Other packages from `cardano-base` repo have not changed since the last time a release was made from that repo.
=> cardano-base release

README.md
This adds the haskell.nix parsing workaround to the README. See https://github.com/input-output-hk/haskell.nix/issues/1869 for the haskell.nix issue.
=> Mention Haskell.nix parsing limitation in the README

flake.lock
Foliage included more stringent [consistency checks](https://github.com/andreabedini/foliage/pull/37) that prevent the situation where the package name or version in the metadata does not match the corresponding info the cabal file.
This prevent the mess-up with had with quickcheck-contractmodel a couple of weeks ago.
=> Bump foliage to include package version check

_sources/freer-extras/1.2.0.0/meta.toml, _sources/freer-extras/1.2.0.0/revisions/1.cabal, _sources/plutus-ledger/1.2.0.0/meta.toml, _sources/plutus-ledger/1.2.0.0/revisions/1.cabal, _sources/plutus-script-utils/1.2.0.0/meta.toml, _sources/plutus-script-utils/1.2.0.0/revisions/1.cabal
This adds
* plutus-ledger-1.2.0.0
* plutus-script-utils-1.2.0.0
* freer-extras-1.2.0.0
From the commit hash https://github.com/input-output-hk/plutus-apps/commit/c4f4dc5fedd5b1804781abb7db0fb5a553e24ecb. Note this is not identical to the [1.2.0.0 release](https://github.com/input-output-hk/plutus-apps/releases/tag/v1.2.0), since unfortunately that release refers to `quickcheck-contractmodel` with the old name `contractmodel`. The only difference between the two commits is in plutus-ledger cabal file, which changes its dependency from contract-model to quickcheck-contractmodel.
```
diff --git a/plutus-ledger/plutus-ledger.cabal b/plutus-ledger/plutus-ledger.cabal
index b2426cdfc..3e9c4e46f 100644
--- a/plutus-ledger/plutus-ledger.cabal
+++ b/plutus-ledger/plutus-ledger.cabal
@@ -140,13 …
```
=> Add some of plutus-apps packages

.github/workflows/CI.yml
Rather than relying on the nix config settings. This is more robust and
also they were incomplete, so we were getting jobs hanging because
things weren't cached.
=> Fix CI workflow to accept flake config

.github/workflows/CI.yml, README.md, flake.nix, nix/chap-meta.nix, scripts/compare-package-metadata.sh
This has a few changes:
- All the packages are available through the flake `packages`.
- There is a specific package to build everything and also all the smoke
test packages. This means we can use `nix build` instead of `nix flake
check` which might be unreliable.
- There is a job to build newly added packages, which works in a sneaky
way by modifying the package metadata in the repository and then
building "everything".
=> CHaP CI: more reliable attribute build plus building new packages

_sources/cardano-ledger-shelley/0.1.0.0/revisions/3.cabal, _sources/ouroboros-consensus-shelley/0.1.0.1/revisions/3.cabal
* `ouroboros-consensus-shelley-0.1.0.1` is compatible with
`ouroboros-network < 0.4`.
* Relax upper bound of `cardano-data` in `cardano-ledger-shelley` to
allow all minor versions `cardano-data-0.1.x`.
=> New revisions of ouroboros-consensus-shelley and cardano-ledger-shelley

_sources/plutus-core/1.4.0.0/meta.toml, _sources/plutus-ledger-api/1.4.0.0/meta.toml, _sources/plutus-tx-plugin/1.4.0.0/meta.toml, _sources/plutus-tx/1.4.0.0/meta.toml
=> Publish 1.4.0.0 for plutus core packages

.github/workflows/CI.yml, flake.lock
This pulls in Andrea's recent fix which should stop the CI from doing so
many spurious rebuilds.
=> Bump haskell.nix

_sources/libsystemd-journal/1.4.5.0.0.0.0.1/meta.toml, _sources/libsystemd-journal/1.4.5.0.0.0.0.1/revisions/2.cabal
I was able to successfully build `cardano-node` with newest `unix-bytestring-0.4`. Only bounds that are updated in this revision are:
```diff
-         unix-bytestring >=0.3.2 && <0.4,
+         unix-bytestring >=0.3.2 && <0.5,
```
=> Add a revision for `libsystemd-journal` to allow newer `unix-bytestring`

.github/workflows/CI.yml, flake.lock, nix/builder.nix
Now haskell.nix fetches the sdists from the actual repository URL, not the flake input. But for new packages they won't be _in_ the remote version of `cardano-haskell-packages`, so it will fail. Instead we use the flake input as the repo directly.
Contains a fake package publish just to test the CI. Do not merge with that in.
Do not merge until https://github.com/input-output-hk/haskell.nix/pull/1910 is merged also.
=> Rework builder to work with new haskell.nix

CODEOWNERS, README.md
At the moment we're using CODEOWNERS to manage access control. That
works for what it covers, but some stuff _isn't_ covered.
That means that anyone who is part of the teams with write access can,
e.g. push a new package, including patched Hackage packages; add new
package versions of anything that isn't owned; alter the CI; etc.
There's a fairly simple solution: just add a catch all rule for the CHaP
"trustee" team (a new team I just made so that it can be distinct from
the team which has admin on the repo).  This means that everyting will
get reviewed by _someone_.
=> Add a catch-all CODEOWNERS rule for trustees

_sources/ouroboros-network-api/0.2.0.0/meta.toml, _sources/ouroboros-network-framework/0.4.0.0/meta.toml, _sources/ouroboros-network-protocols/0.4.0.0/meta.toml, _sources/ouroboros-network/0.5.0.0/meta.toml
From https://github.com/input-output-hk/ouroboros-network at aabf8f87f7587b5e94f109c6ab64e02d1db03c35
Still missing a release for `ouroboros-consensus` and `ouroboros-consensus-diffusion`. @Jasagredo , it should be the same revision.
=> Released necessary ouroboros-network-* packages for https://github.com/input-output-hk/cardano-node/pull/4854

_sources/cardano-binary-test/1.4.0.2/meta.toml, _sources/cardano-binary/1.7.0.1/meta.toml, _sources/cardano-crypto-praos/2.1.1.2/meta.toml, _sources/cardano-slotting/0.1.1.1/meta.toml
Rest of the packages from cardano-base with ghc-9.6 support. `cardano-crypto-class` and `cardano-crypto-tests` have already been released in #229
=> Cardano base packages with ghc 9.6 support

_sources/fs-api/0.1.0.1/meta.toml, _sources/fs-api/0.1.0.1/revisions/1.cabal, _sources/fs-sim/0.1.0.1/meta.toml, _sources/fs-sim/0.1.0.1/revisions/1.cabal
... that relaxes the bounds to use `io-classes`,  and `strict-stm` to include version `1.1` of these packages.
=> Add a revision for `fs-sim` and `fs-api`

_sources/set-algebra/0.1.0.0/meta.toml, _sources/set-algebra/0.1.0.0/revisions/1.cabal, _sources/set-algebra/0.1.1.1/meta.toml, _sources/set-algebra/0.1.1.1/revisions/1.cabal, _sources/set-algebra/0.1.1.2/meta.toml, _sources/set-algebra/0.1.1.2/revisions/1.cabal, _sources/set-algebra/1.0.0.0/meta.toml, _sources/set-algebra/1.0.0.0/revisions/1.cabal
A previously exposed module and some instances were removed from `cardano-data >=1.1` in [cardano-ledger/#3371](https://github.com/input-output-hk/cardano-ledger/pull/3371).
This PR adds revisions to all previously released versions of `set-algebra` to restrict its dependency on `cardano-data` to be `<1.1`.
=> Revision #1 for set-algebra to use cardano-data <1.1

_sources/cardano-ping/0.1.0.0/meta.toml, _sources/cardano-ping/0.1.0.0/revisions/1.cabal, _sources/monoidal-synchronisation/0.1.0.3/meta.toml, _sources/network-mux/0.4.0.0/meta.toml, _sources/ntp-client/0.0.1.1/meta.toml, _sources/ouroboros-network-api/0.3.0.0/meta.toml, _sources/ouroboros-network-framework/0.5.0.0/meta.toml, _sources/ouroboros-network-mock/0.1.0.1/meta.toml, _sources/ouroboros-network-protocols/0.5.0.0/meta.toml, _sources/ouroboros-network-testing/0.3.0.0/meta.toml, _sources/ouroboros-network/0.6.0.0/meta.toml, flake.lock
- Added ouroboros-network-0.6.0.0
- Added ouroboros-network-framework-0.5.0.0
- Added ntp-client-0.0.1.1
- Added monoidal-synchronisation-0.1.0.3
- Added network-mux-0.4.0.0
- Added ouroboros-network-api-0.3.0.0
- Added ouroboros-network-mock-0.1.0.1
- Added ouroboros-network-protocols-0.5.0.0
- Added ouroboros-network-testing-0.3.0.0
- cardano-ping: relax network-mux version bound
=> coot/ouroboros network 0.6.0.0

_sources/cardano-ledger-alonzo/1.1.1.0/meta.toml
This is a new bugfix release, that contains this fix: https://github.com/input-output-hk/cardano-ledger/pull/3399
=> Added cardano-ledger-alonzo-1.1.1.0

_sources/optparse-applicative-fork/0.16.2.0/meta.toml
From https://github.com/input-output-hk/optparse-applicative at f3e0bc1b44b93866824c284565480a391d1f6c5f
=> Added optparse-applicative-fork-0.16.2.0

_sources/typed-protocols-cborg/0.1.0.3/meta.toml, _sources/typed-protocols-examples/0.2.0.1/meta.toml, _sources/typed-protocols/0.1.0.5/meta.toml
=> Update typed-protocols versions (ghc-9.6)

README.md, _sources/cardano-api/8.0.0/meta.toml, _sources/cardano-cli/8.0.0/meta.toml, _sources/cardano-git-rev/0.1.0.0/meta.toml, _sources/cardano-git-rev/0.1.0.0/revisions/1.cabal, _sources/cardano-git-rev/0.1.1.0/meta.toml, _sources/cardano-node-chairman/8.0.0/meta.toml, _sources/cardano-node/8.0.0/meta.toml, _sources/cardano-testnet/8.0.0/meta.toml, _sources/cardano-topology/8.0.0/meta.toml, _sources/ekg-forward/0.1.0/meta.toml, _sources/ekg-forward/0.1.0/revisions/1.cabal, _sources/ekg-forward/0.2.0/meta.toml, _sources/ekg-forward/0.2.0/revisions/1.cabal, _sources/trace-dispatcher/2.0.0/meta.toml, _sources/trace-forward/1.35.4/meta.toml, _sources/trace-forward/1.35.4/revisions/1.cabal, _sources/trace-forward/2.0.0/meta.toml, _sources/trace-resources/0.2.0.0/meta.toml, flake.lock
This is the [`8.0.0`](https://github.com/input-output-hk/cardano-node/tree/8.0.0) release of `cardano-node` packages to CHaP
=> Release 8.0.0

_sources/cardano-ledger-shelley/1.1.1.1/meta.toml, _sources/cardano-ledger-shelley/1.1.1.1/revisions/1.cabal
Adding  an upper bound in `cardano-ledger-shelley 1.1.1.1` on `cardano-ledger-core ^>=1.1`
=> cardano-ledger-shelley 1.1.1.1 revision

CODEOWNERS, _sources/cardano-data/1.1.0.0/meta.toml, _sources/cardano-ledger-allegra/1.1.1.0/meta.toml, _sources/cardano-ledger-alonzo-test/1.1.1.0/meta.toml, _sources/cardano-ledger-alonzo/1.2.0.0/meta.toml, _sources/cardano-ledger-api/1.2.0.0/meta.toml, _sources/cardano-ledger-babbage-test/1.1.1.0/meta.toml, _sources/cardano-ledger-babbage/1.2.0.0/meta.toml, _sources/cardano-ledger-binary/1.1.1.0/meta.toml, _sources/cardano-ledger-conway-test/1.1.1.0/meta.toml, _sources/cardano-ledger-conway/1.2.0.0/meta.toml, _sources/cardano-ledger-core/1.2.0.0/meta.toml, _sources/cardano-ledger-mary/1.2.0.0/meta.toml, _sources/cardano-ledger-pretty/1.1.1.0/meta.toml, _sources/cardano-ledger-shelley-ma-test/1.2.0.0/meta.toml, _sources/cardano-ledger-shelley-ma/1.1.0.1/meta.toml, _sources/cardano-ledger-shelley-test/1.1.1.0/meta.toml, _sources/cardano-ledger-shelley/1.1.0.0/meta.toml, _sources/cardano-ledger-shelley/1.1.0.0/revisions/1.cabal, _sources/cardano-ledger-shelley/1.1.1.0/meta.toml, _sources/cardano-ledger-shelley/1.1.1.0/revisions/1.cabal, _sources/cardano-ledger-shelley/1.2.0.0/meta.toml, _sources/cardano-protocol-tpraos/1.0.3.0/meta.toml, _sources/ouroboros-consensus-cardano/0.5.0.1/meta.toml, _sources/ouroboros-consensus-cardano/0.5.0.1/revisions/1.cabal, _sources/set-algebra/1.1.0.0/meta.toml
I am updating several packages from ledger. The biggest change is support for Plutus V3 starting in the conway ledger era.
- cardano-ledger-babbage - 1.2.0.0
- cardano-ledger-babbage-test - 1.1.1.0
- cardano-ledger-mary - 1.2.0.0
- cardano-ledger-allegra - 1.1.1.0
- cardano-ledger-conway - 1.2.0.0
- cardano-ledger-conway-test - 1.1.1.0
- cardano-ledger-alonzo - 1.2.0.0
- cardano-ledger-alonzo-test - 1.1.1.0
- cardano-ledger-shelley - 1.2.0.0
- cardano-ledger-shelley-test - 1.1.1.0
- cardano-ledger-binary - 1.1.1.0
- cardano-ledger-api - 1.2.0.0
- cardano-ledger-pretty - 1.1.1.0
- cardano-data - 1.1.0.0
- cardano-ledger-core - 1.2.0.0
- cardano-protocol-tpraos - 1.0.3.0
- cardano-shelley-ma - 1.1.0.1
- cardano-shelley-ma - 1.2.0.0
- set-algebra - 1.1.0.0
I also updated the `CODEOWNERS` …
=> ledger updates

_sources/cardano-crypto-wrapper/1.4.2/meta.toml, _sources/cardano-crypto-wrapper/1.4.2/revisions/2.cabal
Add missing bound.
Build failure can be reproduced with
```
nix build --override-input CHaP github:input-output-hk/cardano-haskell-packages/8132844 \
'.#"ghc8107/cardano-crypto-wrapper/1.4.2"'
```
Evidence that this fixes it needs a local checkout (unfortunately):
```
nix develop -c foliage build
nix build --override-input CHaP path:_repo '.#"ghc8107/cardano-crypto-wrapper/1.4.2"'
```
=> Revision: cardano-crypto-wrapper-1.4.2 needs cardano-binary < 1.5.0.1

_sources/iog-contra-tracer/0.1.0.2/meta.toml, _sources/iog-contra-tracer/0.1.0.2/revisions/1.cabal
This should cause all packages that use `iog-contra-tracer` to fall back to a previous version which uses `contra-tracer` (ie before the rename).
=> Disable iog-contra-tracer (base < 0)

_sources/contra-tracer/0.1.0.2/meta.toml, _sources/iohk-monitoring/0.1.11.3/meta.toml, _sources/tracer-transformers/0.1.0.4/meta.toml
=> iohk-minitoring-framework with contra-tracer instead of iog-contra-tracer

_sources/typed-protocols-cborg/0.1.0.4/meta.toml, _sources/typed-protocols-examples/0.2.0.2/meta.toml, _sources/typed-protocols/0.1.0.6/meta.toml
=> typed-protocols switched back to using contra-tracer

scripts/add-revision.sh
I looked into actually retrieving the needed cabal file but that seems a little too fragile, so report the error, create the required  directory and suggest copying the needed cabal file.
=> scripts/add-revision.sh: Improve error reporting

flake.lock, nix/builder.nix
This adds a function to the derivations passthru to be able to quickly add constraints to builds.
E.g. if `.#"ghc8107/cardano-ledger-core/0.1.0.0"` is an derivation that aggregates all components of `cardano-ledger-core-0.1.0.0` then
```
.#"ghc8107/cardano-ledger-core/0.1.0.0".passthru.addConstraint "cardano-crypto-class <2.0.0.1, cardano-binary<1.5.0.1"
```
builds the same aggregates with the additional listed constraints.
Usage from the command line is a bit awkward because nix being ... nix, but we can script over it:
```
nix build $(nix eval --raw '.#"ghc8107/cardano-ledger-core/0.1.0.0"' \
--apply 'd: (d.passthru.addConstraint "cardano-crypto-class <2.0.0.1, cardano-binary<1.5.0.1").drvPath')
```
Unfortunately there's no `nix build --apply` …
=> Add shortcut to quickly add constraints to packages

_sources/ouroboros-network-api/0.4.0.0/meta.toml, _sources/ouroboros-network-api/0.4.0.0/revisions/1.cabal, _sources/ouroboros-network-protocols/0.5.0.1/meta.toml, _sources/ouroboros-network-protocols/0.5.0.1/revisions/1.cabal
One should use:
* `ouroboros-network-api-0.5.0.0` and
* `ouroboros-network-protocols-0.5.0.2`
instead of
* `ouroboros-network-0.4.0.0` and
* `ouroboros-network-protocols-0.5.0.1`
=> Forbid using `ouroboros-network-api-0.4.0.0`

flake.lock, flake.nix
foliage is now under IOG https://github.com/input-output-hk/foliage, this updates the url in flake.nix and bump its version.
=> Update foliage url and bump

_sources/cardano-cli/7.1.0/meta.toml
From https://github.com/input-output-hk/cardano-cli at 2c0a07b21a45e7ee2f8d129aaa2c7cc777543280
This is for testing the moving of `cardano-cil` to its own repository.  The version number was chosen to not conflict with what's currently in `cardano-node` repository.
=> Added cardano-cli-7.1.0

_sources/streaming/0.2.3.1.0.0.0.0.1/meta.toml
From https://github.com/haskell-streaming/streaming at 0c815bf9043d0f0cbda92b80ef791892e2b7fb43
Upstream HEAD is fixed, but not yet released to Hackage.
https://github.com/haskell-streaming/streaming/issues/119
=> Added streaming-0.2.3.1.0.0.0.0.1

.github/workflows/CI.yml
This also removes nixbuild.net as I guess the point of self-hosted runners is to build ourselves, too. Also their action [writes system-wide SSH config](https://github.com/nixbuild/nixbuild-action/blob/2c22043033fd4118ff8f465d59e1edb7619fca74/nixbuild-action.sh#L123) which is hard to work around.
=> use self-hosted runners for github actions

_sources/byron-spec-chain/1.0.0.1/meta.toml, _sources/byron-spec-ledger/1.0.0.1/meta.toml, _sources/cardano-ledger-allegra/1.2.0.2/meta.toml, _sources/cardano-ledger-alonzo-test/1.1.2.2/meta.toml, _sources/cardano-ledger-alonzo/1.3.1.1/meta.toml, _sources/cardano-ledger-api/1.3.0.0/meta.toml, _sources/cardano-ledger-babbage-test/1.1.1.3/meta.toml, _sources/cardano-ledger-babbage/1.4.0.1/meta.toml, _sources/cardano-ledger-byron/1.0.0.2/meta.toml, _sources/cardano-ledger-conway-test/1.2.0.2/meta.toml, _sources/cardano-ledger-conway/1.5.0.0/meta.toml, _sources/cardano-ledger-core/1.4.0.0/meta.toml, _sources/cardano-ledger-mary/1.3.0.2/meta.toml, _sources/cardano-ledger-pretty/1.2.1.1/meta.toml, _sources/cardano-ledger-shelley/1.4.1.0/meta.toml, _sources/cardano-protocol-tpraos/1.0.3.3/meta.toml
- Added `cardano-ledger-pretty-1.2.1.1`
- Added `cardano-ledger-core-1.4.0.0`
- Added `cardano-ledger-api-1.3.0.0`
- Added `cardano-ledger-shelley-1.4.1.0`
- Added `cardano-ledger-mary-1.3.0.2`
- Added `cardano-ledger-conway-1.5.0.0`
- Added `cardano-ledger-byron-1.0.0.2`
- Added `byron-spec-ledger-1.0.0.1`
- Added `byron-spec-chain-1.0.0.1`
- Added `cardano-ledger-babbage-1.4.0.1`
I'm not certain that this is the full set of changes required from cardano-ledger, but this includes all of the packages whose versions have been incremented. There are some other changes to dependency bounds, though I'm not certain that this warrants the affected packages being released.
=> Release 8.2 cardano-ledger packages (second wave)

_sources/cardano-ledger-alonzo/1.3.3.0/meta.toml, _sources/cardano-ledger-babbage/1.4.2.0/meta.toml
This PR makes a release of
* cardano-ledger-alonzo-1.3.3.0
* cardano-ledger-babbage-1.4.2.0
Which contains a backport of a fix implemented in https://github.com/input-output-hk/cardano-ledger/pull/3567
=> Backport mint translation bugfix

_sources/bech32/1.1.4/meta.toml
From https://github.com/input-output-hk/bech32 at c938472efd2b72ecbbb1e323993142b6d360566a
=> Added bech32-1.1.4

_sources/cardano-ledger-shelley-test/1.2.0.2/meta.toml, _sources/small-steps-test/1.0.0.1/meta.toml
Couple of the test packages didn't get released when ghc-9.6. compatibility was being implemented. This is the release of those packages
=> Ledger ghc 9.6 compat packages

_sources/fs-api/0.2.0.0/meta.toml, _sources/fs-sim/0.2.1.0/meta.toml, _sources/ouroboros-consensus/0.7.0.0/meta.toml, _sources/ouroboros-consensus/0.7.0.0/revisions/1.cabal, _sources/ouroboros-consensus/0.8.0.0/meta.toml, _sources/ouroboros-consensus/0.8.0.0/revisions/1.cabal, _sources/ouroboros-consensus/0.9.0.0/meta.toml, _sources/ouroboros-consensus/0.9.0.0/revisions/1.cabal
New versions of `fs-api` and `fs-sim` require revisions to old `ouroboros-consensus` versions, since they don't have upper bounds on `fs-api` and `fs-sim`, which breaks their builds and makes the smoke tests fail.
=> `fs-sim-0.2.1.0`, `fs-api-0.2.0.0`, accompanying `ouroboros-consensus` revisions

_sources/cardano-crypto-test/1.5.0.0/meta.toml, _sources/cardano-crypto-test/1.5.0.0/revisions/1.cabal, _sources/cardano-crypto-wrapper/1.5.1.0/meta.toml, _sources/cardano-crypto-wrapper/1.5.1.0/revisions/1.cabal, _sources/cardano-data/1.1.0.0/meta.toml, _sources/cardano-data/1.1.0.0/revisions/1.cabal, _sources/non-integral/1.0.0.0/meta.toml, _sources/non-integral/1.0.0.0/revisions/1.cabal, _sources/set-algebra/1.1.0.1/meta.toml, _sources/set-algebra/1.1.0.1/revisions/1.cabal, _sources/small-steps/1.0.0.0/meta.toml, _sources/small-steps/1.0.0.0/revisions/1.cabal, _sources/vector-map/1.0.1.0/meta.toml, _sources/vector-map/1.0.1.0/revisions/1.cabal
These cabal files are taken from `cardano-ledger@master`. They were already updated, but they had not been published yet.
Diff:
```diff
diff --git a/cardano-crypto-test.cabal b/_sources/cardano-crypto-test/1.5.0.0/revisions/1.cabal
index 6914047d..6eebb78c 100644
--- a/cardano-crypto-test.cabal
+++ b/_sources/cardano-crypto-test/1.5.0.0/revisions/1.cabal
@@ -51,10 +51,9 @@ library
-Wno-safe -Wno-unsafe -Wunused-packages
build-depends:
-        base >=4.12 && <4.17,
+        base >=4.14 && <4.19,
bytestring,
-        cardano-ledger-binary,
-        cardano-ledger-binary:testlib,
+        cardano-ledger-binary:{cardano-ledger-binary, testlib} >=1.0,
cardano-crypto,
cardano-crypto-wrapper ^>=1.5,
cardano-prelude,
diff --git a/cardano-crypto-wrapper.cabal …
```
=> Added revisioned ledger packages for GHC9.6

_sources/ouroboros-consensus-cardano/0.8.0.1/meta.toml, _sources/ouroboros-consensus-diffusion/0.7.1.1/meta.toml, _sources/ouroboros-consensus-protocol/0.5.0.6/meta.toml, _sources/ouroboros-consensus/0.10.0.1/meta.toml
The follow-up to https://github.com/input-output-hk/ouroboros-consensus/pull/301 and https://github.com/input-output-hk/ouroboros-consensus/pull/308
Notably: integrates the release of `cardano-ledger-conway-1.7.0.0`.
Closes https://github.com/input-output-hk/ouroboros-consensus/issues/303.
=> Release Consensus packages enabling the 8.3 node pre-release

nix/builder.nix
If we put the index.html in there, we'll end up getting index.html for all parts, which we don't want. We need the relative base for this to work. 
Using index.html means that we are trying to look up
- https://ci.iog.io/build/722545/download/1/linuwial.css
- https://ci.iog.io/build/722545/download/1/quick-jump.css for 
- https://ci.iog.io/build/722545/download/1/index.html
which do not exist, as hydra only knows about the explicit index.html build product. Putting the html folder in there should give them all the proper relative path. See also: [NixOS/nix/flake.nix#L615]( https://github.com/NixOS/nix/blob/0a6ac133cfd1c86b8f6062b8b12e5aac8e18df3c/flake.nix#L615)
=> Put folder, not file into hydra-build-products

scripts/add-from-github.sh
- The flag to force the version was appealingly named `-v` and looked like you were just supposed to always pass the version. I made it scary and changed the flag so that anyone who is currently using it gets tripped up
- The "revision" flag is extremely confusing given we also have, you know, revisions. It's also not used that much, so I just removed it.
=> Clean up version flags in add-from-github

flake.nix
This just got added, which is why I missed it. (The previous version did not work).
=> Node 8.3.1 does build on 9.6

flake.lock
So it gets the latest cardano-node that builds on 9.6 also.
=> Bump CHaP input for hydra

_sources/cardano-api/1.36.0/meta.toml
From https://github.com/input-output-hk/cardano-api at 163b02dfc09d7b6e61a7e904705339db1f4ca621
=> Added cardano-api-1.36.0

_sources/cardano-ledger-conway/1.8.1.0/meta.toml, _sources/cardano-ledger-shelley/1.6.1.0/meta.toml
This version updated provides a backport fix for treasury withdrawals
=> Path cardano ledger conway 1.8.1.0

CODEOWNERS, _sources/ekg-core/0.1.1.7.0.0.0.0.1/meta.toml, _sources/ekg-json/0.1.0.7.0.0.0.0.2/meta.toml, _sources/ekg/0.4.0.15.0.0.0.0.2/meta.toml, scripts/add-from-github.sh
EKG packages are unmaintained so we forked them. For now our forks are not the official ones so we will publish them as `.0.0.0.0` revisions over the Hackage releases
=> EKG packages

_sources/cardano-prelude/0.1.0.4/meta.toml
=> cardano-prelude now support ghc-9.8

flake.lock, flake.nix, result
We're moving towards 9.8, we're not going to use 9.2 or 9.4 in the long run.
Since 9.8 is only going to work for a small set of packages to begin with, I added an `experimental-compilers` list. Things in that list are off by default but you can turn them on in `exceptions`.
`cardano-prelude` builds with 9.8 now, so that's our first test!
=> Add 9.8 to CI, remove 9.2 and 9.4

_sources/cardano-api/8.29.1.0/meta.toml
From https://github.com/input-output-hk/cardano-api at 44567a67d7992c0888fbe203ae96f9e5c5486d7c
Sets upper bound for `nothunks < 0.1.5` in order to build with `plutus-ledger-api == 1.15`. There is a duplicate instances conflict.
=> Added cardano-api-8.29.1.0

_sources/cardano-node-capi/0.1.0.1/meta.toml, _sources/cardano-node-chairman/8.6.1/meta.toml, _sources/cardano-node/8.7.0/meta.toml, _sources/cardano-submit-api/3.2.0/meta.toml, _sources/cardano-testnet/8.7.0/meta.toml, _sources/cardano-topology/8.4.0/meta.toml, _sources/cardano-tracer/0.2.1/meta.toml, _sources/locli/1.34/meta.toml, _sources/plutus-scripts-bench/1.0.0.6/meta.toml, _sources/trace-dispatcher/2.4.1/meta.toml, _sources/trace-forward/2.2.1/meta.toml, _sources/tx-generator/2.10/meta.toml
Release packages at input-output-hk/cardano-node@34d89af65439db92293b88967c299c20692abc1c
=> Cardano Node 8.7.0

_sources/cardano-node/8.7.1/meta.toml, _sources/cardano-node/8.7.1/revisions/1.cabal
=> Revise cardano-node-8.7.1 to relax the text upper bound

_sources/cardano-api/8.36.1.1/meta.toml
From https://github.com/input-output-hk/cardano-api at ba115ebba354363276299b6044380c8b6a8be0b2
=> Added cardano-api-8.36.1.1

_sources/cardano-git-rev/0.2.1.0/meta.toml
From https://github.com/IntersectMBO/cardano-base at 30c6ce8f6464cc6fcba8fc77677b339e29731eb7
=> Added cardano-git-rev-0.2.1.0

_sources/cardano-cli/8.21.0.0/meta.toml
From https://github.com/IntersectMBO/cardano-cli at 05c32d8ab51be55fe8052ae0f0d8d5d75840fe74
Changelog: https://github.com/IntersectMBO/cardano-cli/blob/release/cardano-cli-8.21.0.0/cardano-cli/CHANGELOG.md#82100
=> Added cardano-cli-8.21.0.0

_sources/cardano-git-rev/0.2.2.0/meta.toml
From https://github.com/IntersectMBO/cardano-base at 6fe0b492ac7e2e52c4c72ed0283c198657800973
=> Added cardano-git-rev-0.2.2.0

_sources/latex-svg-image/0.2.0.0.0.1/meta.toml
From https://github.com/jasagredo/latex-svg at c52c9905cb043ddb430c93b41ce431a7506a300d
Until this gets merged and released https://github.com/phadej/latex-svg/pull/9
=> Added latex-svg-image-0.2.0.0.0.1

_sources/ouroboros-consensus-cardano/0.14.2.0/meta.toml, _sources/ouroboros-consensus-cardano/0.14.2.0/revisions/2.cabal, _sources/ouroboros-consensus-diffusion/0.14.0.0/meta.toml, _sources/ouroboros-consensus/0.16.0.0/meta.toml, _sources/ouroboros-consensus/0.16.0.0/revisions/1.cabal
Note that this is a **backport release**, see https://github.com/IntersectMBO/ouroboros-consensus/pull/1042, 0.13.0.0 is still the latest and greatest. (We might change our versioning scheme in the future to make that more clear.)
=> Release ouroboros-consensus-diffusion-0.14.0.0

README.md
I think this piece of doc is outdated as described by @andreabedini [here](https://github.com/input-output-hk/haskell.nix/issues/1869#issuecomment-1506279322)
=> Remove old workaround form doc

_sources/cardano-addresses/3.12.0/meta.toml
From https://github.com/intersectmbo/cardano-addresses at b4a9765314aee3f2926a8eca79f6cfdac836bda1
=> Added cardano-addresses-3.12.0

nix/builder.nix
This tries to reduce the divergences between Haskell.nix and
cabal-install, as they can cause issues (e.g. Haskell.nix reinstall ghc
by default, assuming that Cabal is in the plan, which it might not be).
=> Include `constraints: ghc source` when planning

_sources/set-algebra/1.1.0.2/meta.toml, _sources/set-algebra/1.1.0.2/revisions/1.cabal
Removes the upper bound on `ansi-wl-pprint`. This allows to use the latest versions which are shims to  `prettyprinter`.
=> Revise set-algebra 1.1.0.2

_sources/Win32-network/0.2.0.0/meta.toml
From https://github.com/IntersectMBO/Win32-network at cd5ab6ae6e24e059bd01a3aacc7601ab1f01b72c
=> Added Win32-network-0.2.0.0

scripts/list-latest-package-revs.sh
This PR adds a standalone bash script `list-latest-package-revs.sh` for listing the latest versions for packages, their repos, their subdir, and their commit, separated by space.
Unlike `list-latest-package-versions.sh`, this script doesn't require to build the whole `folliage` database, and only relies on the `_sources` directory.
The reason I think this is useful is for manually querying without having to wait and without requiring lots of disk space. And the motivation was that I was considering generating a dependency graph of projects, so this would serve as a first step in that direction.
This is the beginning of the current output:
```bash
$ scripts/list-latest-package-revs.sh | sort
erikd/vector-algorithms 0.9.0.1.0.0.0.0.1 e3fc242ac75d928ca613be9702ff2946011ef7d4 …
```
=> Add quick script for listing latest versions and revs

scripts/depencencies-from-cabal-file.sh
This PR adds a standalone bash script `depencencies-from-cabal-file.sh` for extracting the dependencies from a cabal file.
The reason I think this is useful is for gathering dependency info quickly across projects. And the motivation was that I was considering generating a dependency graph of projects, so this would serve as a step in that direction.
=> Add script to extract dependencies from cabal files

_sources/fs-api/0.2.0.1/meta.toml, _sources/fs-api/0.2.0.1/revisions/2.cabal, _sources/fs-sim/0.2.1.1/meta.toml, _sources/fs-sim/0.2.1.1/revisions/2.cabal
=> Revisions for bumping `io-classes` to `1.6` in `fs-api-0.2.0.1` and `fs-sim-0.2.1.1`

scripts/fetch-all-cabal-files.sh
This PR adds a standalone bash script `fetch-all-cabal-files.sh` for gathering all the cabal files for all the revisions of all the projects.
The reason I think this is useful is that this way we can conveniently gather all cabal files for the projects we work on for analysis purposes.
And the exact motivation was that I was considering generating a dependency graph of projects, so this would serve as a step in that direction.
=> Add script to fetch all cabal files

scripts/generate-dependency-graph.sh
This PR adds a standalone bash script `generate-dependency-graph.sh` to generate a `graphviz` dependency graph of all the haskell packages.
It may have inaccuracies but it is meant to serve as a map and to be easy and quick to generate.
The generated graph does have transitive dependencies but they can be removed easily by using the `tred` tool, which leads to a considerably more readable graph.
=> Add script to generate dependency graph

_sources/cardano-ledger-allegra/1.5.0.0/meta.toml, _sources/cardano-ledger-alonzo-test/1.2.1.2/meta.toml, _sources/cardano-ledger-alonzo/1.9.0.0/meta.toml, _sources/cardano-ledger-api/1.9.2.0/meta.toml, _sources/cardano-ledger-babbage-test/1.2.0.3/meta.toml, _sources/cardano-ledger-babbage/1.8.1.0/meta.toml, _sources/cardano-ledger-binary/1.3.3.0/meta.toml, _sources/cardano-ledger-byron-test/1.5.1.1/meta.toml, _sources/cardano-ledger-conway-test/1.2.1.6/meta.toml, _sources/cardano-ledger-conway/1.15.0.0/meta.toml, _sources/cardano-ledger-core/1.13.0.0/meta.toml, _sources/cardano-ledger-mary/1.6.1.0/meta.toml, _sources/cardano-ledger-shelley-ma-test/1.2.2.2/meta.toml, _sources/cardano-ledger-shelley-test/1.4.0.2/meta.toml, _sources/cardano-ledger-shelley/1.12.0.0/meta.toml, _sources/cardano-protocol-tpraos/1.2.0.1/meta.toml, _sources/set-algebra/1.1.0.3/meta.toml, flake.nix
~Ledger containing CIP-0069 changes, but NOT the plutus update. I opened the PR in order to see and fix any problems.
So we should not merge until the latter is in as well.~
CIP-0069 and plutus update to 1.30. 
Can be merged after this is merged into ledger: https://github.com/IntersectMBO/cardano-ledger/pull/4409
=> Ledger release 8.12

_sources/ouroboros-consensus-cardano/0.17.0.0/meta.toml, _sources/ouroboros-consensus-diffusion/0.17.0.0/meta.toml, _sources/ouroboros-consensus-protocol/0.9.0.1/meta.toml, _sources/ouroboros-consensus/0.19.0.0/meta.toml, flake.nix
Depends on https://github.com/IntersectMBO/ouroboros-consensus/pull/1151
| Package | Old version | New version |
| --- | :-: | :-: |
| `ouroboros-consensus` | `0.18.0.0` | `0.19.0.0` |
| `ouroboros-consensus-diffusion` | `0.16.0.0` | `0.17.0.0`|
| `ouroboros-consensus-protocol` | `0.9.0.0` | `0.9.0.1` |
| `ouroboros-consensus-cardano` | `0.16.0.0` | `0.17.0.0` |
=> Release Consensus packages for Node 8.12

_sources/cardano-ledger-babbage/1.6.1.0/meta.toml, _sources/cardano-ledger-conway/1.12.1.0/meta.toml, _sources/small-steps-test/0.1.0.0/meta.toml, _sources/small-steps-test/0.1.0.0/revisions/1.cabal, _sources/small-steps-test/0.1.1.1/meta.toml, _sources/small-steps-test/0.1.1.1/revisions/1.cabal, _sources/small-steps-test/0.1.1.2/meta.toml, _sources/small-steps-test/0.1.1.2/revisions/1.cabal, _sources/small-steps-test/1.0.0.0/meta.toml, _sources/small-steps-test/1.0.0.0/revisions/1.cabal, _sources/small-steps-test/1.0.0.1/meta.toml, _sources/small-steps-test/1.0.0.1/revisions/1.cabal, _sources/small-steps-test/1.0.1.0/meta.toml, _sources/small-steps-test/1.0.1.0/revisions/1.cabal
Waiting for CI to pass: https://github.com/IntersectMBO/cardano-ledger/pull/4447
This PR also adds revisions for the deprecated `small-steps-test` package, so it no longer tries to build with newer and incompatible `small-steps` dependency
=> Backport ledger release for node 8.9.4

_sources/cuddle/0.2.0.1/meta.toml
From https://github.com/input-output-hk/cuddle at 90f57394ec5d12eadc1d9d0d8c99170815cc8079
This adds a new release of cuddle:
- Loosens the version bounds on Base
- Does not generate duplicate keys in CBOR maps
=> Added cuddle-0.2.0.1

_sources/cardano-api/8.49.0.0/meta.toml
From https://github.com/IntersectMBO/cardano-api at d280689ba294982b01a80eea0fbe936d3efb6e8d
Corresponding API PR: https://github.com/IntersectMBO/cardano-api/pull/565
=> Added cardano-api-8.49.0.0

_sources/ouroboros-network/0.16.1.1/meta.toml
From https://github.com/intersectmbo/ouroboros-network at f22edb3f537cc0d1da482f3c43bc2c1a6fcf11e4
=> Added ouroboros-network-0.16.1.1

_sources/cardano-cli/8.25.0.0/meta.toml
From https://github.com/IntersectMBO/cardano-cli at 02ef3279560f36eaebe24e041e58708504310100
Corresponding CLI PR: https://github.com/IntersectMBO/cardano-cli/pull/807
=> Added cardano-cli-8.25.0.0

_sources/fs-api/0.2.0.1/meta.toml, _sources/fs-api/0.2.0.1/revisions/3.cabal, _sources/fs-sim/0.2.1.1/meta.toml, _sources/fs-sim/0.2.1.1/revisions/3.cabal
Just bump dependencies.
Have already tested that these work by adding:
```
allow-newer:
, fs-api:*
, fs-sim:*
```
to the `cardano-consensus` `cabal.project` file, and building with `ghc-9.10`.
=> Make fs-api and fs-sim build with ghc-9.10

_sources/cardano-testnet/9.0.0/meta.toml
From https://github.com/IntersectMBO/cardano-node at 2820a63dc934c6d5b5f450b6c2543b81c6476696
Fixes https://github.com/IntersectMBO/cardano-node/issues/5913
=> Added cardano-testnet-9.0.0

_sources/latex-svg-image/0.2.0.0.0.1/meta.toml, _sources/latex-svg-image/0.2.0.0.0.1/revisions/1.cabal
=> Bump base dependency for latex-svg-image

_sources/cardano-ledger-alonzo-test/1.2.1.2/meta.toml, _sources/cardano-ledger-alonzo-test/1.2.1.2/revisions/1.cabal, _sources/cardano-ledger-alonzo/1.10.0.0/meta.toml, _sources/cardano-ledger-alonzo/1.10.0.0/revisions/1.cabal, _sources/cardano-ledger-babbage/1.8.2.0/meta.toml, _sources/cardano-ledger-babbage/1.8.2.0/revisions/1.cabal, _sources/cardano-ledger-binary/1.3.3.0/meta.toml, _sources/cardano-ledger-binary/1.3.3.0/revisions/1.cabal, _sources/cardano-ledger-conway/1.16.0.0/meta.toml, _sources/cardano-ledger-conway/1.16.0.0/revisions/1.cabal
@lehins All I have done is added `^>=1.31` to the bounds of `plutus-ledger-api` so it looks like:
```
plutus-ledger-api ^>=1.30 || ^>= 1.31
```
to allow me to remove all the `allow-newer` stanzas in my `cardano-cli` PR.
If this is ok with you, please merge it.
=> Lossen upper bounds on plutus-ledger-api

_sources/cardano-client/0.3.1.5/meta.toml, _sources/cardano-ping/0.4.0.1/meta.toml, _sources/ouroboros-network-api/0.9.0.1/meta.toml, _sources/ouroboros-network-framework/0.13.2.4/meta.toml, _sources/ouroboros-network-protocols/0.10.0.2/meta.toml, _sources/ouroboros-network/0.17.1.1/meta.toml
From https://github.com/intersectmbo/ouroboros-network at 5dd745f32652132cd24ec34e7164688c0e40dd48
checked with build-with-chap.sh in ouroboros-network
This PR fixes the non-existent git ref in release 0.17.1.0.
=> Release ouroboros-network-0.17.1.1 & co

_sources/typed-protocols-examples/0.2.0.3/meta.toml, _sources/typed-protocols/0.1.1.1/meta.toml, flake.lock, flake.nix
- **Added typed-protocols-0.1.1.1**
- **Added typed-protocols-examples-0.2.0.3**
- **Dropped ghc92**
- **Updated haskell-nix**
- **Updated hackage-nix**
=> typed-protocols: using io-classes-1.6

_sources/cardano-ledger-shelley/1.12.3.0/meta.toml, _sources/cardano-ledger-shelley/1.13.1.0/meta.toml
This is a backport of https://github.com/IntersectMBO/cardano-ledger/pull/4589 for:
* `cardano-node-9.1`: https://github.com/IntersectMBO/cardano-ledger/pull/4591
* `cardano-node-9.2`: https://github.com/IntersectMBO/cardano-ledger/pull/4590
=> Backport ledger state deserialization fix

_sources/typed-protocols/0.1.1.1/meta.toml, _sources/typed-protocols/0.1.1.1/revisions/2.cabal
We'll stick with `io-classes-1.5` for now.  We need to wait for
Hackage.Nix support.
=> Make `typed-protocols-0.1.1.1` unreachable

_sources/cardano-ledger-conway/1.16.2.0/meta.toml, _sources/cardano-ledger-core/1.14.1.0/meta.toml
This PR is the backport of nice performance improvements from this PR: https://github.com/IntersectMBO/cardano-ledger/pull/4644
=> Prepare `cardano-ledger-conway-1.16.2.0` release

_sources/plutus-core/1.35.0.0/meta.toml, _sources/plutus-ledger-api/1.35.0.0/meta.toml, _sources/plutus-tx-plugin/1.35.0.0/meta.toml, _sources/plutus-tx/1.35.0.0/meta.toml, _sources/prettyprinter-configurable/1.35.0.0/meta.toml
Deleted the previous PR because the timestamps became unmanageably broken.
=> Plutus core Release 1.35.0.0

_sources/cardano-prelude-test/0.1.0.5/meta.toml
From https://github.com/IntersectMBO/cardano-prelude/ at cfb3e0784f0d483f4d5c4f047f324b7dc8091475
=> Added cardano-prelude-test-0.1.0.5

_sources/cardano-client/0.3.1.6/meta.toml, _sources/cardano-ping/0.5.0.0/meta.toml, _sources/ouroboros-network-api/0.10.0.0/meta.toml, _sources/ouroboros-network-framework/0.13.2.5/meta.toml, _sources/ouroboros-network-protocols/0.11.0.0/meta.toml, _sources/ouroboros-network/0.17.1.2/meta.toml
From https://github.com/intersectmbo/ouroboros-network at 4bdf801bbaf4aaddb2ec394891697fe6d3185bf0
checked with build-with-chap.sh in ouroboros-network
=> Release ouroboros-network-0.17.1.2 & co 

_sources/cardano-api-gen/10.0.0.0/meta.toml, _sources/cardano-api/10.0.0.0/meta.toml
From https://github.com/IntersectMBO/cardano-api at 06265fe58
Corresponding PR IntersectMBO/cardano-api#655
=> Release cardano-api-10.0.0.0

_sources/cardano-ledger-conway/1.17.1.0/meta.toml
Here is a PR into ledger with this release: https://github.com/IntersectMBO/cardano-ledger/pull/4710
This is a backport release of this PR that fixes two bugs in `cardano-ledger-conway-1.17.0.0`: https://github.com/IntersectMBO/cardano-ledger/pull/4709
=> Release `cardano-ledger-conway-1.17.1.0`

_sources/cardano-ledger-conway/1.17.2.0/meta.toml
Backport release of `cardano-ledger-conway-1.17.2.0`: https://github.com/IntersectMBO/cardano-ledger/pull/4716
From https://github.com/IntersectMBO/cardano-ledger at 0268e812b19f9d7a88859253b884dbe4d0bce1e6
=> Added cardano-ledger-conway-1.17.2.0

_sources/cardano-node-chairman/10.0.1/meta.toml, _sources/cardano-node/10.1.1/meta.toml
From https://github.com/IntersectMBO/cardano-node at 76e90db0647ab3d8aadf8f83cf081993c03e340d
Related PR https://github.com/IntersectMBO/cardano-node/pull/6022
=> release cardano-node 10.1.1

_sources/cardano-tracer/0.3/meta.toml
From https://github.com/IntersectMBO/cardano-node at 4184f9297bf7306713bfbb8f39eef61c056198cc
(identical commit as cardano-node-10.1.1)
=> Added cardano-tracer-0.3

_sources/ouroboros-consensus-cardano/0.21.0.0/meta.toml, _sources/ouroboros-consensus-diffusion/0.19.0.0/meta.toml, _sources/ouroboros-consensus-protocol/0.10.0.0/meta.toml, _sources/ouroboros-consensus/0.22.0.0/meta.toml
* ouroboros-consensus-0.22.0.0
* ouroboros-consensus-diffusion-0.19.0.0
* ouroboros-consensus-protocol-0.10.0.0
* ouroboros-consensus-cardano-0.21.0.0
From https://github.com/IntersectMBO/ouroboros-consensus at 21f62aee88f8b6d7bad421727d20c0ad2bbc5cc3
=> Update ouroboros-consensus packages

_sources/cardano-prelude/0.2.1.0/meta.toml
From https://github.com/IntersectMBO/cardano-prelude/ at 68e015f6e7f17e67d8dbf16bc1590b926d064962
=> Added cardano-prelude-0.2.1.0

_sources/ouroboros-network/0.19.0.1/meta.toml
From https://github.com/intersectmbo/ouroboros-network at e91d5c41976343d6642e3701f28d7ea510553916
=> Added ouroboros-network-0.19.0.1

_sources/plutus-ledger/1.3.0.0/meta.toml, _sources/plutus-ledger/1.3.0.0/revisions/2.cabal
From https://github.com/IntersectMBO/cardano-crypto at 9152d0e74bf1d17781482bc6649e2079827a93aa
This version is the first to use the `crypton` library as a replacement for `cryptonite`.
=> plutus-ledger-1.3.0.0: Restrict dependency on cardano-crypto

_sources/cardano-crypto-praos/2.0.0.0.1/meta.toml, _sources/cardano-crypto-praos/2.0.0.0.1/revisions/1.cabal, _sources/cardano-crypto-praos/2.0.0.1/meta.toml, _sources/cardano-crypto-praos/2.0.0.1/revisions/1.cabal, _sources/cardano-crypto-praos/2.0.0/meta.toml, _sources/cardano-crypto-praos/2.0.0/revisions/1.cabal, _sources/cardano-crypto-praos/2.1.0.0/meta.toml, _sources/cardano-crypto-praos/2.1.0.0/revisions/1.cabal, _sources/cardano-crypto-praos/2.1.1.0/meta.toml, _sources/cardano-crypto-praos/2.1.1.0/revisions/1.cabal, _sources/cardano-crypto-praos/2.1.1.1/meta.toml, _sources/cardano-crypto-praos/2.1.1.1/revisions/1.cabal, _sources/cardano-crypto-praos/2.1.1.2/meta.toml, _sources/cardano-crypto-praos/2.1.1.2/revisions/1.cabal, _sources/cardano-crypto-praos/2.1.2.0/meta.toml, _sources/cardano-crypto-praos/2.1.2.0/revisions/3.cabal, _sources/cardano-crypto-tests/2.0.0.0.1/meta.toml, _sources/cardano-crypto-tests/2.0.0.0.1/revisions/1.cabal, _sources/cardano-crypto-tests/2.0.0.1/meta.toml, _sources/cardano-crypto-tests/2.0.0.1/revisions/1.cabal, _sources/cardano-crypto-tests/2.0.0/meta.toml, _sources/cardano-crypto-tests/2.0.0/revisions/1.cabal, _sources/cardano-crypto-tests/2.1.0.0/meta.toml, _sources/cardano-crypto-tests/2.1.0.0/revisions/1.cabal, _sources/cardano-crypto-tests/2.1.0.1/meta.toml, _sources/cardano-crypto-tests/2.1.0.1/revisions/1.cabal
Older versions of `cardano-crypto-tests` and `cardano-crypto-praos` are incompatible with `cardano-crypto-class-2.2`. This PR adds revisions with upper bounds for all older versions of those packages
=> Crypto upper bound revisions

_sources/typed-protocols-cborg/0.3.0.0/meta.toml, _sources/typed-protocols-cborg/0.3.0.0/revisions/1.cabal, _sources/typed-protocols-stateful-cborg/0.3.0.0/meta.toml, _sources/typed-protocols-stateful-cborg/0.3.0.0/revisions/1.cabal, _sources/typed-protocols/0.3.0.0/meta.toml, _sources/typed-protocols/0.3.0.0/revisions/1.cabal, flake.lock
Tested by successfully compiling `ouroboros-network` with:
```
if impl (ghc >= 9.12)
allow-newer:
, typed-protocols:io-classes
, typed-protocols-cborg:base
, typed-protocols-cborg:io-classes
, typed-protocols-stateful-cborg:base
, typed-protocols-stateful-cborg:base
, typed-protocols-stateful-cborg:base
```
=> Bump upper dependency bounds on base and io-classes

_sources/Win32-network/0.2.0.1/meta.toml
From https://github.com/IntersectMBO/Win32-network at fec6d7bdfec15d9bd1033ae5ed25f4385f4f1237
=> Added Win32-network-0.2.0.1

_sources/cardano-api/8.33.0.0/meta.toml, _sources/cardano-api/8.33.0.0/revisions/1.cabal
This pull request fixes an issue with the `cardano-api-8.33.0.0` package where the version constraints on `ouroboros-consensus` and `ouroboros-consensus-cardano` have been flipped accidentally.
=> Revise `cardano-api-8.33.0.0`

_sources/cardano-api/10.9.0.0/meta.toml
From https://github.com/IntersectMBO/cardano-api at 545948ae2b3cc29b66401ba09a80ad96d5bde88c
Commit: [545948ae2b3cc29b66401ba09a80ad96d5bde88c](https://github.com/IntersectMBO/cardano-api/commits/545948ae2b3cc29b66401ba09a80ad96d5bde88c)
PR in package's repo: https://github.com/IntersectMBO/cardano-api/pull/753
Release number: 10.9.0.0
=> Added cardano-api-10.9.0.0

scripts/check-cabal-plan.sh
Checks whether a cabal build plan is using the latest packages from CHaP
=> Add `scripts/check-cabal-plan.sh`

scripts/local-ci.sh
Run the equivalent of GH CI locally, in an idempotent, non-mutating way
This can be helpful when investigating build failures because it gives local access to the nix build logs
=> Add `scripts/local-ci.sh`

_sources/cardano-wallet-read/1.0.0.1/meta.toml, _sources/plutus-core/1.40.0.0/meta.toml, _sources/plutus-core/1.40.0.0/revisions/1.cabal
From https://github.com/cardano-foundation/cardano-wallet-agda at cfcf563f3455d104bda373c4416518d4fb342e95
This pull request also adds a revision for `plutus-core-1.40.0.0`, which fails to compile with older versions of `cardano-crypto`.
=> Added cardano-wallet-read-1.0.0.1

_sources/cardano-ledger-byron/1.0.0.0/meta.toml, _sources/cardano-ledger-byron/1.0.0.0/revisions/1.cabal, _sources/cardano-ledger-byron/1.0.0.1/meta.toml, _sources/cardano-ledger-byron/1.0.0.1/revisions/1.cabal, _sources/cardano-ledger-byron/1.0.0.2/meta.toml, _sources/cardano-ledger-byron/1.0.0.2/revisions/1.cabal, _sources/cardano-ledger-byron/1.0.0.3/meta.toml, _sources/cardano-ledger-byron/1.0.0.3/revisions/1.cabal, _sources/cardano-ledger-byron/1.0.0.4/meta.toml, _sources/cardano-ledger-byron/1.0.0.4/revisions/1.cabal, _sources/cardano-ledger-byron/1.0.1.0/meta.toml, _sources/cardano-ledger-byron/1.0.1.0/revisions/2.cabal, _sources/cardano-ledger-core/1.0.0.0/meta.toml, _sources/cardano-ledger-core/1.0.0.0/revisions/3.cabal, _sources/cardano-ledger-core/1.1.0.0/meta.toml, _sources/cardano-ledger-core/1.1.0.0/revisions/3.cabal, _sources/cardano-ledger-core/1.1.0.1/meta.toml, _sources/cardano-ledger-core/1.1.0.1/revisions/3.cabal
This PR adds a revision for `cardano-ledger-core` and `cardano-ledger-byron` that adds an upper bound for `cardano-ledger-binary <1.5`, wince there was a breaking change that affected older versions of these packages.
=> Revision with ledger binary upper bound

_sources/ouroboros-consensus-cardano/0.23.0.0/meta.toml, _sources/ouroboros-consensus-diffusion/0.21.0.1/meta.toml, _sources/ouroboros-consensus-protocol/0.11.0.0/meta.toml, _sources/ouroboros-consensus-protocol/0.11.0.0/revisions/1.cabal, _sources/ouroboros-consensus/0.24.0.0/meta.toml, _sources/sop-extras/0.3.0.0/meta.toml
- Release ouroboros-consensus 0.24.0.0
- Release ouroboros-consensus-cardano 0.23.0.0
- Revision ouroboros-consensus-diffusion 0.21.0.0
- Relax upper bound for ouroboros-consensus 0.24.0.0
- Tighten lower bound for sop-extras to 0.2.2
- Revision ouroboros-consensus-protocol 0.11.0.0
- Relax upper bound for ouroboros-consensus 0.24.0.0
- Release sop-extras 0.2.3.0
=> Release consensus packages

_sources/cardano-cli/10.6.0.0/meta.toml
From https://github.com/IntersectMBO/cardano-cli at 83d8514856cb03959df327b2b5966f12abe61a2f
Related release PR in `cardano-cli`: https://github.com/IntersectMBO/cardano-cli/pull/1122
=> Added cardano-cli-10.6.0.0

_sources/ouroboros-consensus-cardano/0.25.0.1/meta.toml
From https://github.com/IntersectMBO/ouroboros-consensus at ae57f6a953f7f0f907b7278b6f2c2ca34b6879fc
=> Added ouroboros-consensus-cardano-0.25.0.1

_sources/cardano-api/10.15.0.0/meta.toml
From https://github.com/IntersectMBO/cardano-api at 333e470307192cfb1a9107a37ce8df11ead65fc2
Related release PR in cardano-api: https://github.com/IntersectMBO/cardano-api/pull/830
=> Added cardano-api-10.15.0.0

_sources/cardano-node/10.4.1/meta.toml
Release PR: https://github.com/IntersectMBO/cardano-node/pull/6201
=> Added cardano-node-10.4.1

_sources/plutus-core/1.46.0.0/meta.toml, _sources/plutus-ledger-api/1.46.0.0/meta.toml, _sources/plutus-tx-plugin/1.46.0.0/meta.toml, _sources/plutus-tx/1.46.0.0/meta.toml, flake.nix
=> Plutus Release 1.46.0.0

_sources/cardano-api/10.18.0.0/meta.toml
From https://github.com/IntersectMBO/cardano-api at 842ad95ff8f1ee43989e50d1dd42514a51e3a35f
Related release PR in cardano-api: https://github.com/IntersectMBO/cardano-api/pull/957
=> Added cardano-api-10.18.0.0

_sources/cardano-prelude/0.1.0.1/meta.toml, _sources/cardano-prelude/0.1.0.1/revisions/1.cabal, _sources/cardano-prelude/0.1.0.2/meta.toml, _sources/cardano-prelude/0.1.0.2/revisions/1.cabal, _sources/cardano-prelude/0.1.0.4/meta.toml, _sources/cardano-prelude/0.1.0.4/revisions/1.cabal, _sources/cardano-prelude/0.2.0.0/meta.toml, _sources/cardano-prelude/0.2.0.0/revisions/1.cabal, _sources/cardano-prelude/0.2.1.0/meta.toml, _sources/cardano-prelude/0.2.1.0/revisions/1.cabal
`microlens-0.5` removes functionality from `Lens.Micro.Internal` that was being used in `cardano-prelude` so for now add upper bound.
=> Add microlens upper bound in cardano-prelude

_sources/ouroboros-consensus-cardano/0.26.0.0/meta.toml, _sources/ouroboros-consensus-diffusion/0.24.0.0/meta.toml, _sources/ouroboros-consensus-protocol/0.13.0.0/meta.toml, _sources/ouroboros-consensus/0.28.0.0/meta.toml, _sources/sop-extras/0.4.1.0/meta.toml
- `ouroboros-consensus-0.28.0.0` at `4759da500fc9e1d25f2d91c865aa41054cc70f22`
- `ouroboros-consensus-protocol-0.13.0.0` at `4759da500fc9e1d25f2d91c865aa41054cc70f22`
- `ouroboros-consensus-diffusion-0.24.0.0` at `4759da500fc9e1d25f2d91c865aa41054cc70f22`
- `ouroboros-consensus-cardano-0.26.0.0` at `4759da500fc9e1d25f2d91c865aa41054cc70f22`
- `sop-extras-0.4.1.0` at `4759da500fc9e1d25f2d91c865aa41054cc70f22`
=> ouroboros-consensus releases for 10.6
