IntersectMBO/cardano-haskell-packages

README.md
I included the "extra version components" version of the policy, let's not merge this until we find out if that actually works!
=> Add some explanations and policy about patched versions

_sources/plutus-core/1.0.0.0/meta.toml, _sources/plutus-core/1.0.0.0/revisions/2.cabal, _sources/plutus-ledger-api/1.0.0.0/meta.toml, _sources/plutus-ledger-api/1.0.0.0/revisions/2.cabal, _sources/plutus-tx-plugin/1.0.0.0/meta.toml, _sources/plutus-tx-plugin/1.0.0.0/revisions/2.cabal, _sources/plutus-tx/1.0.0.0/meta.toml, _sources/plutus-tx/1.0.0.0/revisions/2.cabal, scripts/check.sh
The fork for flat advertises version 0.4.5 but we published in the
repository with version 0.4.4.0.0.0.0.1
=> Fix plutus revisions

README.md
Add a section to the README discussing the workflow I have been following while troubleshooting build plans.
=> Add a section to README about testing changes

scripts/add-from-github.sh
=> Fix comment

README.md, scripts/add-from-github.sh
=> add-from-github script can force versions

README.md
=> Add nickname

README.md
WDYT @andreabedini ? It would be cool to check this, but for now I think we just have to ask people not to do it.
=> Add some policy on not requiring extra build configuration

_sources/plutus-core/1.0.0.1/meta.toml
From https://github.com/input-output-hk/plutus at d5f6f4a5505094490f61c8d164515adf7c8f46cc
This one at least I'm sure of.
=> Added plutus-core-1.0.0.1

_sources/byron-spec-chain/0.1.1.0/meta.toml, _sources/byron-spec-ledger/0.1.1.0/meta.toml, _sources/cardano-crypto-test/1.3.1/meta.toml, _sources/cardano-crypto-wrapper/1.3.1/meta.toml, _sources/cardano-data/0.1.1.0/meta.toml, _sources/cardano-ledger-alonzo-test/0.1.1.0/meta.toml, _sources/cardano-ledger-alonzo/0.1.1.0/meta.toml, _sources/cardano-ledger-babbage-test/0.1.1.0/meta.toml, _sources/cardano-ledger-babbage/0.1.1.0/meta.toml, _sources/cardano-ledger-byron-test/1.3.1/meta.toml, _sources/cardano-ledger-byron/0.1.1.0/meta.toml, _sources/cardano-ledger-conway-test/0.1.1.0/meta.toml, _sources/cardano-ledger-conway/0.1.1.0/meta.toml, _sources/cardano-ledger-core/0.1.1.0/meta.toml, _sources/cardano-ledger-pretty/0.1.1.0/meta.toml, _sources/cardano-ledger-shelley-ma-test/0.1.1.0/meta.toml, _sources/cardano-ledger-shelley-ma/0.1.1.0/meta.toml, _sources/cardano-ledger-shelley-test/0.1.1.0/meta.toml, _sources/cardano-ledger-shelley/0.1.1.0/meta.toml, _sources/cardano-ledger-test/0.1.1.0/meta.toml, _sources/cardano-protocol-tpraos/0.1.1.0/meta.toml, _sources/ledger-state/0.1.1.0/meta.toml, _sources/non-integral/0.1.1.0/meta.toml, _sources/plutus-preprocessor/0.1.1.0/meta.toml, _sources/set-algebra/0.1.1.0/meta.toml, _sources/small-steps-test/0.1.1.0/meta.toml, _sources/small-steps/0.1.1.0/meta.toml, _sources/vector-map/0.1.1.0/meta.toml
Do not merge this until I've tested that it works.
=> Release the ledger packages from the release branches for the 1.35 node release

_sources/plutus-ledger-api/1.0.0.1/meta.toml
From https://github.com/input-output-hk/plutus at d5f6f4a5505094490f61c8d164515adf7c8f46cc
=> Added plutus-ledger-api-1.0.0.1

_sources/int-cast/0.2.0.0.0.0.0.0.1/meta.toml
From https://github.com/input-output-hk/int-cast at 20cc3a95383fc8d1c2ea3b3d691700036cecdeac
=> Added int-cast-0.2.0.0.0.0.0.0.1

scripts/_sources/cardano-crypto-praos/2.1.0.0/meta.toml
From https://github.com/input-output-hk/cardano-base at 2c5285e40f9076d15a86c53254777601c1077cc9
=> Added cardano-crypto-praos-2.1.0.0

_sources/cardano-crypto-praos/2.1.0.0/meta.toml, scripts/_sources/cardano-crypto-praos/2.1.0.0/meta.toml
Previous PR #51 added the package into the wrong place, this PR fixes that
=> Added cardano-crypto-praos 2.1.0.0

_sources/cardano-slotting/0.1.0.2/meta.toml
From https://github.com/input-output-hk/cardano-base at b5f2941d003398b77f9b3d1b43a9cebb8a4515fd
=> Added cardano-slotting-0.1.0.2

README.md
FYI @andreabedini I think this is sensible
=> Add a note about making issues for patched packages

README.md, flake.lock
This PR bumps foliage to get the new generated webpages. Please test this :-)
=> Add static pages

README.md
Include @andreabedini's setup for just testing a built repository conveniently.
=> Rework the discussion of testing CHaP

_sources/cardano-strict-containers/0.1.1.0/meta.toml
From https://github.com/input-output-hk/cardano-base at 319b70ae75243620594dca056bd27b7f447b4cde
=> Added cardano-strict-containers-0.1.1.0

_sources/goblins/0.2.0.1/meta.toml
From https://github.com/input-output-hk/goblins at b83a0a0e99210f5988adea1820636e654bd03947
=> Added goblins-0.2.0.1

_sources/ouroboros-network-testing/0.2.0.0/meta.toml
From https://github.com/input-output-hk/ouroboros-network at a376bb268a43470567fbcc08b55584858fc0f4c9
=> Added ouroboros-network-testing-0.2.0.0

_sources/cardano-api/1.35.4/meta.toml, _sources/cardano-cli/1.35.4/meta.toml, _sources/cardano-client-demo/0.1.0.0/meta.toml, _sources/cardano-node-capi/0.1.0.0/meta.toml, _sources/cardano-node-chairman/1.35.4/meta.toml, _sources/cardano-node/1.35.4/meta.toml, _sources/cardano-testnet/1.35.4/meta.toml, _sources/cardano-topology/1.35.4/meta.toml, _sources/cardano-tracer/0.1.0/meta.toml, _sources/locli/1.29/meta.toml, _sources/tx-generator/2.2/meta.toml
From https://github.com/input-output-hk/cardano-node at ebc7be471b30e5931b35f9bbc236d21c375b91bb
=> cardano-node 1.35.4 release

_sources/typed-protocols-cborg/0.1.0.2/meta.toml, _sources/typed-protocols/0.1.0.2/meta.toml
- Added typed-protocols-0.1.0.2
- Added typed-protocols-cborg-0.1.0.2
=> typed-protocols

.github/workflows/CI.yml
So that the text gets shown even if the command fails! I'd prefer to have it at the bottom, but this will do.
=> Echo message before trying the script that might fail

_sources/byron-spec-chain/0.1.1.2/meta.toml, _sources/byron-spec-ledger/0.1.1.2/meta.toml, _sources/cardano-crypto-test/1.4.2/meta.toml, _sources/cardano-crypto-wrapper/1.4.2/meta.toml, _sources/cardano-data/0.1.1.2/meta.toml, _sources/cardano-ledger-alonzo-test/0.1.1.2/meta.toml, _sources/cardano-ledger-alonzo/0.1.1.2/meta.toml, _sources/cardano-ledger-babbage-test/0.1.1.2/meta.toml, _sources/cardano-ledger-babbage/0.1.1.2/meta.toml, _sources/cardano-ledger-byron-test/1.4.2/meta.toml, _sources/cardano-ledger-byron/0.1.1.2/meta.toml, _sources/cardano-ledger-conway-test/0.1.1.2/meta.toml, _sources/cardano-ledger-conway/0.1.1.2/meta.toml, _sources/cardano-ledger-core/0.1.1.2/meta.toml, _sources/cardano-ledger-pretty/0.1.1.2/meta.toml, _sources/cardano-ledger-shelley-ma-test/0.1.1.2/meta.toml, _sources/cardano-ledger-shelley-ma/0.1.1.2/meta.toml, _sources/cardano-ledger-shelley-test/0.1.1.2/meta.toml, _sources/cardano-ledger-shelley/0.1.1.2/meta.toml, _sources/cardano-ledger-test/0.1.1.2/meta.toml, _sources/cardano-protocol-tpraos/0.1.1.2/meta.toml, _sources/ledger-state/0.1.1.2/meta.toml, _sources/non-integral/0.1.1.2/meta.toml, _sources/plutus-preprocessor/0.1.1.2/meta.toml, _sources/set-algebra/0.1.1.2/meta.toml, _sources/small-steps-test/0.1.1.2/meta.toml, _sources/small-steps/0.1.1.2/meta.toml, _sources/vector-map/0.1.1.2/meta.toml
Added cardano-ledger-conway-0.1.1.2
Added cardano-ledger-conway-test-0.1.1.2
Added cardano-ledger-shelley-0.1.1.2
Added cardano-ledger-shelley-test-0.1.1.2
Added cardano-ledger-alonzo-0.1.1.2
Added cardano-ledger-alonzo-test-0.1.1.2
Added cardano-crypto-test-1.4.2
Added cardano-crypto-wrapper-1.4.2
Added cardano-ledger-byron-test-1.4.2
Added cardano-ledger-byron-0.1.1.2
Added byron-spec-ledger-0.1.1.2
Added byron-spec-chain-0.1.1.2
Added cardano-ledger-babbage-0.1.1.2
Added cardano-ledger-babbage-test-0.1.1.2
Added cardano-ledger-shelley-ma-0.1.1.2
Added cardano-ledger-shelley-ma-test-0.1.1.2
Added cardano-ledger-pretty-0.1.1.2
Added small-steps-test-0.1.1.2
Added non-integral-0.1.1.2
Added cardano-data-0.1.1.2
Added set-algebra-0.1.1.2
Added cardano-protocol-tpraos-0.1.1.2
Added …
=> Added cardano-ledger 1.1.2

_sources/typed-protocols/0.1.0.3/meta.toml
From https://github.com/input-output-hk/typed-protocols at v0.1.0.3
=> Added typed-protocols-0.1.0.3

_sources/io-classes/0.4.0.0/meta.toml, _sources/io-sim/0.4.0.0/meta.toml, _sources/strict-stm/0.4.0.0/meta.toml
- Added io-sim-0.4.0.0
- Added io-classes-0.4.0.0
- Added strict-stm-0.4.0.0
=> coot/io sim v0.4.0.0

_sources/trace-dispatcher/1.35.4/meta.toml, _sources/trace-forward/1.35.4/meta.toml
From https://github.com/input-output-hk/cardano-node at ebc7be471b30e5931b35f9bbc236d21c375b91bb
=> Added trace-dispatcher-1.35.4

CODEOWNERS
=> Add CODEOWNERS for cardano-node and packages therein

CODEOWNERS
- performance-tracing:  take ownership of related packages
=> performance-tracing:  take ownership of related packages

_sources/ouroboros-consensus-cardano/0.2.0.0/meta.toml
From https://github.com/input-output-hk/ouroboros-network at e259a34dab759dc907cff5fd2f1edb631a6a9ef9
=> Added ouroboros-consensus-cardano-0.2.0.0

_sources/hedgehog-extras/0.3.0.0/meta.toml
From https://github.com/input-output-hk/hedgehog-extras at 61da3e1a833d7eb5b882a0da49b594a0cc368d96
=> Added hedgehog-extras-0.3.0.0

_sources/Win32-network/0.1.1.1/meta.toml
From https://github.com/input-output-hk/Win32-network at 1521906427571afd64670c2ce5f074d36aefb636
=> Added Win32-network-0.1.1.1

CODEOWNERS, README.md, _sources/inline-r/1.0.0.0.0.0.0.1/meta.toml
From https://github.com/tweag/HaskellR at 53ce6887d8043252a068bc0a7db438abd4cfdc52
Temporary until hackage is updated.
=> Added inline-r-1.0.0.0.0.0.0.1

README.md
https://github.com/search?q=index-state%3A+cardano-haskell-packages&type=code
:facepalm:
=> Fix readme with respect to index-state syntax

README.md
=> Make example in the readme more explicit

_sources/cardano-data/0.1.0.1/meta.toml
From https://github.com/input-output-hk/cardano-ledger at 6e97d31540ee5918e1149c0385e629fcb70ccc03
=> Added cardano-data-0.1.0.1

flake.lock
Need to do this before using new features as the CI workflow runs
foliage on the base of the PR first!
=> Bump foliage

scripts/list-packages.sh
Very simple, but useful to have. I want to use it in another PR to
compute the new package versions that get added, so again I need it
in the base branch so things work!
=> Add a script to list the packages in the repo

_sources/ouroboros-network-testing/0.2.0.1/meta.toml
From https://github.com/input-output-hk/ouroboros-network at d5c4460aecc3cbedf4305369615896b6b784d56a
=> Added ouroboros-network-testing-0.2.0.1

_sources/ouroboros-network/0.3.0.1/meta.toml
From https://github.com/input-output-hk/ouroboros-network at 399da3a7dfcf3d84e63f8499b8766693fa01993f
=> Added ouroboros-network-0.3.0.1

CODEOWNERS, _sources/cardano-lmdb-simple/0.5.0.0/meta.toml
From https://github.com/input-output-hk/lmdb-simple/ at f1bab357aa2bdbf639fdc79646f87307a4d44764
=> Added `cardano-lmdb-simple-0.5.0.0`

_sources/ekg-forward/0.3.0.1/meta.toml
From https://github.com/input-output-hk/ekg-forward at 5cb1dbac35ac07870302511403faf8efb96c56c3
=> Added ekg-forward-0.3.0.1

_sources/plutus-core/1.1.1.0/meta.toml, _sources/plutus-core/1.1.1.0/revisions/1.cabal
=> plutus-core-1.1.1.0: Revise to allow for newer cardano-crypto-class

_sources/ouroboros-consensus-diffusion/0.2.1.0/meta.toml, _sources/ouroboros-consensus-mock-test/0.2.1.0/meta.toml, _sources/ouroboros-consensus-mock/0.2.1.0/meta.toml, _sources/ouroboros-consensus-protocol/0.2.1.0/meta.toml, _sources/ouroboros-consensus-test/0.2.1.0/meta.toml, _sources/ouroboros-consensus/0.2.1.0/meta.toml
Release `ouroboros-consensus 0.2.1.0`
=> Release `ouroboros-consensus 0.2.1.0`

_sources/byron-spec-chain/1.0.0.0/meta.toml, _sources/byron-spec-ledger/1.0.0.0/meta.toml, _sources/cardano-crypto-test/1.5.0.0/meta.toml, _sources/cardano-crypto-wrapper/1.5.0.0/meta.toml, _sources/cardano-data/1.0.0.0/meta.toml, _sources/cardano-ledger-allegra/1.0.0.0/meta.toml, _sources/cardano-ledger-alonzo-test/1.0.0.0/meta.toml, _sources/cardano-ledger-alonzo/1.0.0.0/meta.toml, _sources/cardano-ledger-api/1.0.0.0/meta.toml, _sources/cardano-ledger-babbage-test/1.0.0.0/meta.toml, _sources/cardano-ledger-babbage/1.0.0.0/meta.toml, _sources/cardano-ledger-binary/1.0.0.0/meta.toml, _sources/cardano-ledger-byron-test/1.5.0.0/meta.toml, _sources/cardano-ledger-byron/1.0.0.0/meta.toml, _sources/cardano-ledger-conway-test/1.0.0.0/meta.toml, _sources/cardano-ledger-conway/1.0.0.0/meta.toml, _sources/cardano-ledger-core/1.0.0.0/meta.toml, _sources/cardano-ledger-mary/1.0.0.0/meta.toml, _sources/cardano-ledger-pretty/1.0.0.0/meta.toml, _sources/cardano-ledger-shelley-ma-test/1.0.0.0/meta.toml, _sources/cardano-ledger-shelley-ma/1.0.0.0/meta.toml, _sources/cardano-ledger-shelley-test/1.0.0.0/meta.toml, _sources/cardano-ledger-shelley/1.0.0.0/meta.toml, _sources/cardano-protocol-tpraos/1.0.0.0/meta.toml, _sources/non-integral/1.0.0.0/meta.toml, _sources/set-algebra/1.0.0.0/meta.toml, _sources/small-steps-test/1.0.0.0/meta.toml, _sources/small-steps/1.0.0.0/meta.toml, _sources/vector-map/1.0.0.0/meta.toml
This is the first release of packages from cardano-ledger repo that will start with PVP versioning scheme. That is why all of the packages are being released with a major version bump
=> Latest ledger release

_sources/quickcheck-contractmodel/0.1.2/meta.toml
=> Add quickcheck-contractmodel

CODEOWNERS
=> Add an owner for quickcheck-contractmodel

_sources/ouroboros-network-protocols/0.3.0.0/meta.toml, _sources/ouroboros-network/0.4.0.1/meta.toml
- Added ouroboros-network-0.4.0.1
- Added ouroboros-network-protocols-0.3.0.0
=> coot/ouroboros network 0.4.0.1

CODEOWNERS, _sources/ouroboros-consensus-diffusion/0.3.0.0/meta.toml, _sources/ouroboros-consensus-mock-test/0.3.0.0/meta.toml, _sources/ouroboros-consensus-mock/0.3.0.0/meta.toml, _sources/ouroboros-consensus-protocol/0.3.0.0/meta.toml, _sources/ouroboros-consensus-test/0.3.0.0/meta.toml, _sources/ouroboros-consensus-tutorials/0.3.0.0/meta.toml, _sources/ouroboros-consensus/0.3.0.0/meta.toml
Release `ouroboros-consensus` 0.3.0.0
=> Release `ouroboros-consensus` 0.3.0.0

_sources/cardano-lmdb-simple/0.6.0.0/meta.toml
From https://github.com/input-output-hk/lmdb-simple at c8b7c4b7ecc449e131015596195ef12c15db8317
=> Added `cardano-lmdb-simple-0.6.0.0`

_sources/plutus-core/1.3.0.0/meta.toml, _sources/plutus-ledger-api/1.3.0.0/meta.toml, _sources/plutus-tx-plugin/1.3.0.0/meta.toml, _sources/plutus-tx/1.3.0.0/meta.toml
=> Publish 1.3.0.0 for Plutus Core packages

flake.nix
=> Add flake settings for extra subtituters

scripts/add-from-github.sh, scripts/add-revision.sh, scripts/current-timestamp.sh, scripts/fetch-github-cabal-files.sh
Not very clever, relies on the existence of an already built repository.
Did a bit of script refactoring while I was there, some of which isn't
now needed, but I guess I did it already.
=> Add a script to add revisions for a package version

_sources/cardano-ping/0.1.0.0/meta.toml
From https://github.com/input-output-hk/ouroboros-network at d9a002347843e88bc725b185d00ba535edb72e29
=> Added cardano-ping-0.1.0.0

_sources/ouroboros-network-framework/0.2.0.1/meta.toml, _sources/ouroboros-network/0.3.0.2/meta.toml
- Added ouroboros-network-framework-0.2.0.1
- Added ouroboros-network-0.3.0.2
=> coot/ouroboros network 0.3.0.2

_sources/ouroboros-consensus/0.1.0.3/meta.toml, _sources/ouroboros-consensus/0.1.0.3/revisions/1.cabal
It is not compatible with `unix-bytestring-0.4.0`
=> ouroboros-consensus-0.1.0.3 revision

README.md
I clarified how to build the repository, use the revision script, and I also restructured it a bit as it was getting quite long.
=> Update the README a bunch

CODEOWNERS, _sources/fs-api/0.1.0.0/meta.toml, _sources/fs-sim/0.1.0.0/meta.toml
Part of https://github.com/input-output-hk/ouroboros-network/issues/4082
=> `fs-api-0.1.0.0`, `fs-sim-0.1.0.0`

CODEOWNERS, _sources/marlowe-spec-test/0.1.0.0/meta.toml, _sources/marlowe/0.1.0.0/meta.toml
Add packages from https://github.com/input-output-hk/marlowe
=> Add `marlowe`, `marlowe-spec-test`

_sources/base-deriving-via/0.1.0.2/meta.toml, _sources/cardano-api/1.35.4/meta.toml, _sources/cardano-api/1.35.4/revisions/2.cabal, _sources/cardano-binary/1.7.0.0/meta.toml, _sources/cardano-crypto-class/2.1.0.1/meta.toml, _sources/cardano-crypto-praos/2.1.1.1/meta.toml, _sources/cardano-crypto-tests/2.1.0.1/meta.toml, _sources/cardano-slotting/0.1.1.0/meta.toml, _sources/cardano-strict-containers/0.1.2.1/meta.toml, _sources/heapwords/0.1.0.2/meta.toml, _sources/measures/0.1.0.2/meta.toml, _sources/orphans-deriving-via/0.1.0.2/meta.toml
Release packages from cardano-base that contain some JSON instances and remove `development` cabal flag
=> cardano- base releases

_sources/async-components/0.1.0.0/meta.toml, _sources/base16-aeson/0.1.0.0/meta.toml, _sources/eventuo11y-extras/0.1.0.0/meta.toml, _sources/marlowe-cardano/0.1.0.3/meta.toml, _sources/marlowe-chain-sync/0.0.1/meta.toml, _sources/marlowe-client/0.0.1/meta.toml, _sources/marlowe-protocols/0.1.0.0/meta.toml, _sources/marlowe-runtime-web/0.0.1/meta.toml, _sources/marlowe-runtime/0.0.1/meta.toml, _sources/marlowe-test/0.1.1.0/meta.toml, _sources/typed-protocols/0.1.0.0/meta.toml, _sources/typed-protocols/0.1.0.0/revisions/2.cabal, flake.nix
=> Add `marlowe-cardano` packages

.github/workflows/CI.yml, flake.lock
This reverts commit 2d7cd7f15b43403b3e2b2c88a66f91c4143feeae.
=> Revert "Bump haskell.nix (#197)"

_sources/cardano-crypto-wrapper/1.5.1.0/meta.toml, _sources/cardano-data/1.0.1.0/meta.toml, _sources/cardano-ledger-allegra/1.1.0.0/meta.toml, _sources/cardano-ledger-alonzo-test/1.1.0.0/meta.toml, _sources/cardano-ledger-alonzo/1.1.0.0/meta.toml, _sources/cardano-ledger-api/1.1.0.0/meta.toml, _sources/cardano-ledger-babbage-test/1.1.0.0/meta.toml, _sources/cardano-ledger-babbage/1.1.0.0/meta.toml, _sources/cardano-ledger-binary/1.1.0.0/meta.toml, _sources/cardano-ledger-conway-test/1.1.0.0/meta.toml, _sources/cardano-ledger-conway/1.1.0.0/meta.toml, _sources/cardano-ledger-core/1.1.0.0/meta.toml, _sources/cardano-ledger-mary/1.1.0.0/meta.toml, _sources/cardano-ledger-pretty/1.1.0.0/meta.toml, _sources/cardano-ledger-shelley-ma-test/1.1.0.0/meta.toml, _sources/cardano-ledger-shelley-test/1.1.0.0/meta.toml, _sources/cardano-ledger-shelley/1.1.0.0/meta.toml, _sources/cardano-protocol-tpraos/1.0.1.0/meta.toml, _sources/vector-map/1.0.1.0/meta.toml
Release of all pacakges from ledger that have changed since last time there was a release from [`cardano-ledger`](https://github.com/input-output-hk/cardano-ledger) repository
=> Ledger release

_sources/cardano-ledger-shelley/1.1.1.0/meta.toml
From https://github.com/input-output-hk/cardano-ledger at 36cae5287cf6b83e714782dd6a8140df882b55de
=> Added cardano-ledger-shelley-1.1.1.0

.github/workflows/CI.yml, flake.lock, nix/builder.nix
It looks like the issues were caused by transient issues on
nixbuild.net: https://github.com/nixbuild/feedback/issues/30
Reverting this let us try to build something different, which got
through, but I don't think this is the culprit. I've also added a
`--show-trace` in case of future mystery errors.
=> Revert revert + --fallback

CODEOWNERS, _sources/io-classes/0.5.0.0/meta.toml, _sources/io-classes/0.5.0.0/revisions/1.cabal, _sources/io-classes/0.6.0.0/meta.toml, _sources/io-sim/0.5.0.0/meta.toml, _sources/io-sim/0.5.0.0/revisions/1.cabal, _sources/io-sim/0.6.0.0/meta.toml, _sources/strict-mvar/0.1.0.0/meta.toml, _sources/strict-stm/0.5.0.0/meta.toml, _sources/strict-stm/0.5.0.0/revisions/1.cabal, _sources/strict-stm/0.6.0.0/meta.toml
- Added io-classes-0.6.0.0
- Added io-sim-0.6.0.0
- Added strict-stm-0.6.0.0
- Disable io-sim-0.5
- Added strict-mvar-0.1.0.0
=> coot/io sim 0.6.0.0

_sources/quickcheck-contractmodel/0.1.3.0/meta.toml, flake.nix
=> Add quickcheck-contractmodel 0.1.3

flake.nix
These won't actually work until https://github.com/andreabedini/foliage/issues/53
is fixed, but we might as well leave the more generic code in place.
=> Restore other systems in the flake

_sources/cardano-prelude-test/0.1.0.2/meta.toml, _sources/cardano-prelude/0.1.0.2/meta.toml
=> Update cardano-prelude and cardano-prelude-test

README.md, scripts/add-revision.sh
- Added arguments to add-revision.sh
- Added instructions how to update hackage index.
=> Added argument parsing to add-revision.sh script

_sources/quickcheck-contractmodel/0.1.4.0/meta.toml
From https://github.com/input-output-hk/quickcheck-contractmodel at 11fbbf4823655e91cf015b369f62982724a8cdf5
This time I used the script. 🥺
=> Added quickcheck-contractmodel-0.1.4.0

_sources/ouroboros-consensus-cardano/0.5.0.0/meta.toml, _sources/ouroboros-consensus-diffusion/0.5.0.0/meta.toml, _sources/ouroboros-consensus-protocol/0.5.0.0/meta.toml, _sources/ouroboros-consensus/0.5.0.0/meta.toml
First release with the new structure of packages after the code migration
=> Release consensus 0.5

_sources/cardano-ledger-alonzo/1.1.0.1/meta.toml, _sources/cardano-ledger-babbage/1.1.0.1/meta.toml, _sources/cardano-ledger-binary/1.1.0.1/meta.toml, _sources/cardano-ledger-core/1.1.0.1/meta.toml, _sources/cardano-ledger-shelley/1.1.1.1/meta.toml
=> Minor ledger releases with performance fixes

_sources/cardano-crypto-class/2.1.0.2/meta.toml, _sources/cardano-crypto-tests/2.1.0.2/meta.toml
Minor patch with performance improvements and GHC-9.6 compatibility
=> Minor crypto release with performance fixes

_sources/cardano-crypto-class/2.1.1.0/meta.toml, _sources/cardano-crypto-praos/2.1.2.0/meta.toml, _sources/cardano-crypto-tests/2.1.1.0/meta.toml, _sources/cardano-protocol-tpraos/1.0.2.0/meta.toml
This is a follow up release to #229
=> New release from cardano-base

_sources/cardano-ping/0.1.0.1/meta.toml
From https://github.com/input-output-hk/ouroboros-network at 3c91184485de25d17d8a4c1979b7ad106e2a5512
=> Added cardano-ping-0.1.0.1

README.md
Hope this helps the next poor soul coming across this.
=> Add note about troubleshooting CI builds

README.md, flake.nix, scripts/list-latest-package-versions.sh, scripts/update-chap-deps.sh
=> Add a script to update CHaP dependencies

_sources/plutus-core/1.5.0.1/meta.toml
From https://github.com/input-output-hk/plutus at e42d1a03576520c0b7bcbbb7fed073946b9ba5ba
=> Added plutus-core-1.5.0.1

.github/workflows/update-flake-lock.yml
Closes #166
We defintely want to run tests here so we need to set a token as in the `DeterminateSystems/update-flake-lock` [README](https://github.com/DeterminateSystems/update-flake-lock#with-a-personal-authentication-token).
=> Automate bumping hackage.nix

CODEOWNERS
=> Add codeowners for optparse-applicative-fork

_sources/ekg-forward/0.3.0.2/meta.toml
From https://github.com/input-output-hk/ekg-forward/ at 837092de64e69a15beb6341fa65c0569f1d03ab5
=> Added ekg-forward-0.3.0.2

_sources/quickcheck-contractmodel/0.1.4.1/meta.toml
Minor update requested by Quviq
=> Add quickcheck-contractmodel 0.1.4.1

_sources/plutus-core/1.6.0.0/meta.toml, _sources/plutus-ledger-api/1.6.0.0/meta.toml, _sources/plutus-tx-plugin/1.6.0.0/meta.toml, _sources/plutus-tx/1.6.0.0/meta.toml, _sources/prettyprinter-configurable/1.6.0.0/meta.toml
=> Publish 1.6.0.0 for plutus core packages

_sources/plutus-core/1.6.1.0/meta.toml
From https://github.com/input-output-hk/plutus at e3c3b1787bef63ba8bfc80c7d971972e056bddce
=> Added plutus-core-1.6.1.0

_sources/iog-contra-tracer/0.1.0.2/meta.toml
From https://github.com/input-output-hk/iohk-monitoring-framework/ at d3a461998a45c25a842c919545b39284726fbbb1
=> Added iog-contra-tracer-0.1.0.2

_sources/cardano-lmdb-simple/0.6.1.0/meta.toml
From https://github.com/input-output-hk/lmdb-simple at 7324e71e61325f8be89d49f6fb1e5abfa2d4df0f
=> Added `cardano-lmdb-simple-0.6.1.0`

_sources/typed-protocols-cborg/0.1.0.3.0.0.0.0.1/meta.toml, _sources/typed-protocols-examples/0.2.0.1.0.0.0.0.1/meta.toml, _sources/typed-protocols/0.1.0.5.0.0.0.0.1/meta.toml
=> Typed protocols using iog-contra-tracer

_sources/cardano-api/8.1.0.1/meta.toml, _sources/cardano-cli/8.0.0/meta.toml, _sources/cardano-cli/8.0.0/revisions/1.cabal, _sources/cardano-node-chairman/8.0.0/meta.toml, _sources/cardano-node-chairman/8.0.0/revisions/1.cabal, _sources/cardano-node/8.0.0/meta.toml, _sources/cardano-node/8.0.0/revisions/1.cabal, _sources/cardano-testnet/8.0.0/meta.toml, _sources/cardano-testnet/8.0.0/revisions/1.cabal
From https://github.com/input-output-hk/cardano-api at b57b5260ee3c766853e38ea730a819ed0d70ba4c
=> Added cardano-api-8.1.0.1

_sources/cardano-api-gen/8.1.0.1/meta.toml
From https://github.com/input-output-hk/cardano-api at 8469469f763830991e4a72d48a5d56f825fa49b5
=> Added cardano-api-gen-8.1.0.1

_sources/cardano-api-gen/8.1.0.2/meta.toml
From https://github.com/input-output-hk/cardano-api at 67a987d5c2e0d950523eb055d2b7689037b3f065
=> Added cardano-api-gen-8.1.0.2

_sources/ekg-forward/0.3.0.3/meta.toml
From https://github.com/input-output-hk/ekg-forward at 399406e800ffbab376b4005a62b59eca7c0bf828
=> Added ekg-forward-0.3.0.3

_sources/cardano-crypto/1.1.2/meta.toml
From https://github.com/input-output-hk/cardano-crypto at 6568a5e8f1bc231afaae9cc9f6a997d094438859
=> Added cardano-crypto-1.1.2

CONTRIBUTING.md
=> Add a CONTRIBUTING

_sources/plutus-core/1.7.0.0/meta.toml, _sources/plutus-ledger-api/1.7.0.0/meta.toml, _sources/plutus-tx-plugin/1.7.0.0/meta.toml, _sources/plutus-tx/1.7.0.0/meta.toml, _sources/prettyprinter-configurable/1.7.0.0/meta.toml
Don't merge until https://github.com/input-output-hk/cardano-haskell-packages/pull/288 is in.
=> Plutus 1.7 release

_sources/cardano-ledger-alonzo/1.2.1.0/meta.toml, _sources/cardano-ledger-babbage/1.2.1.0/meta.toml
=> Ledger alonzo and babbage bug fix release

_sources/cardano-api/8.1.1.0/meta.toml
From https://github.com/input-output-hk/cardano-api at 1f2355c546976665da1b1a108397bd2761d38ef9
=> Added cardano-api-8.1.1.0

flake.nix
=> Switch to GHC 9.2.7

_sources/cardano-cli/7.1.1.0/meta.toml
From https://github.com/input-output-hk/cardano-cli at ce0ae2641af406c51ab996f54e43acaf709bf94b
=> Added cardano-cli-7.1.1.0

_sources/foundation/0.0.29.0.0.0.0.2/meta.toml
From https://github.com/input-output-hk/foundation at 44ec11afdb6c64639aeae5a4a062186d49d3c9f1
=> Added foundation-0.0.29.0.0.0.0.2

_sources/fs-api/0.1.0.2/meta.toml, _sources/fs-sim/0.1.0.2/meta.toml
=> fs-sim and fs-api

_sources/cardano-cli/7.0.0.0/meta.toml
From https://github.com/input-output-hk/cardano-cli at a05c6260b030a115b46feaad1d4317c6d1636970
=> Added cardano-cli-7.0.0.0

_sources/ekg-forward/0.3.0.4/meta.toml
From https://github.com/input-output-hk/ekg-forward at f7856c4951f8f147d9fc9b3eeade41d81d273eba
=> Added ekg-forward-0.3.0.4

_sources/ouroboros-network/0.8.1.0/meta.toml
From https://github.com/input-output-hk/ouroboros-network at f2b5e5ca3f8be66100ca9bbf64d83e46f3068ce1
=> Added ouroboros-network-0.8.1.0

_sources/th-extras/0.0.0.6.0.0.0.0.1/meta.toml
From https://github.com/input-output-hk/th-extras at 53e062bf2b1e3ae933262c4012cf6badc7cd5237
=> Added th-extras-0.0.0.6.0.0.0.0.1

_sources/persistent-postgresql/2.13.5.2.0.0.0.0.1/meta.toml, _sources/persistent-sqlite/2.13.1.1.0.0.0.0.1/meta.toml, _sources/persistent/2.14.5.0.0.0.0.0.1/meta.toml, _sources/validation-selective/0.2.0.0.0.0.0.0.1/meta.toml, _sources/weigh/0.0.17.0.0.0.0.1/meta.toml
=> Add ghc-9.6 revisions for ledger dependencies

_sources/protolude/0.3.3.0.0.0.0.1/meta.toml
From https://github.com/input-output-hk/protolude/ at 26302ded8dc0861338f326b90e75b7413687223a
=> Added protolude-0.3.3.0.0.0.0.1

_sources/cardano-cli/7.1.2.0/meta.toml
From https://github.com/input-output-hk/cardano-cli at 6f2ee5663c5f46b6225bd6437c492def57fdd228
=> Added cardano-cli-7.1.2.0

README.md
- Add some explanation about how to download the built repository
- Add some more forward links to the most useful how-tos
=> More README work

_sources/ouroboros-network/0.8.1.1/meta.toml
From https://github.com/input-output-hk/ouroboros-network at 0012bba1ec5639d1e27793abc62ae6128f024522
=> Added ouroboros-network-0.8.1.1

README.md
=> Add some notes on debugging solver problems

_sources/cardano-ping/0.2.0.4/meta.toml
From https://github.com/input-output-hk/ouroboros-network at dfcea03b864c1fc777862b189bd3029c8da1d2e3
=> Added cardano-ping-0.2.0.4

_sources/cardano-cli/8.2.0/meta.toml
From https://github.com/input-output-hk/cardano-cli at 0dbed294783c45029bcd734d5ff596794bb237d8
=> Added `cardano-cli-8.2.0`

_sources/cardano-api/8.3.0.0/meta.toml
From https://github.com/input-output-hk/cardano-api at 4d69f83a7afef0715050b26a62b8b1c12f031ce7
=> Added cardano-api-8.3.0.0

_sources/cardano-api/8.4.0.0/meta.toml
From https://github.com/input-output-hk/cardano-api at 2aa34c53adcf8a4af1faf777cdcb16802ff8149c
=> Added cardano-api-8.4.0.0

_sources/cardano-ping/0.2.0.5/meta.toml
From https://github.com/input-output-hk/ouroboros-network at 10ea6f1c93b283d41f9382f6a1df94dc57563ed7
=> Added cardano-ping-0.2.0.5

_sources/cardano-api/8.5.0.0/meta.toml
=> Add `cardano-api-8.5.0.0`

_sources/cardano-api/8.5.2.0/meta.toml
From https://github.com/input-output-hk/cardano-api at 9010b71bb1c5d991c1a6ccc2fb16124dbc501471
=> Added cardano-api-8.5.2.0

flake.lock, nix/builder.nix
crypton 0.32 is now on hackage.
Fixes #352
=> Remove crypton override.

_sources/optparse-applicative/0.16.1.1/meta.toml
From https://github.com/input-output-hk/optparse-applicative at ac9a7ac5a872e2348c38cda928fce614a311f229
=> Added optparse-applicative-0.16.1.1

_sources/optparse-applicative/0.16.2.1/meta.toml
From https://github.com/input-output-hk/optparse-applicative at 398f2ff663bc8a5af1cb6dcaf96897a9b4cbbe8c
=> Added optparse-applicative-0.16.2.1

_sources/ouroboros-consensus-cardano/0.6.1.0/meta.toml, _sources/ouroboros-consensus-diffusion/0.6.1.0/meta.toml, _sources/ouroboros-consensus-protocol/0.5.0.3/meta.toml, _sources/ouroboros-consensus/0.8.0.0/meta.toml
- Release `ouroboros-consensus-0.8.0.0`
- Release `ouroboros-consensus-diffusion-0.6.1.0`
- Release `ouroboros-consensus-protocol-0.5.0.3`
- Release `ouroboros-consensus-cardano-0.6.1.0`
=> Release 8.2 ouroboros-consensus package versions

_sources/cardano-cli/8.2.1/meta.toml
From https://github.com/input-output-hk/cardano-cli at d3bbfa41341221789a3a0d0fd471908e5eeb0fb9
=> Added cardano-cli-8.2.1

_sources/plutus-core/1.8.0.0/meta.toml, _sources/plutus-ledger-api/1.8.0.0/meta.toml, _sources/plutus-tx-plugin/1.8.0.0/meta.toml, _sources/plutus-tx/1.8.0.0/meta.toml, _sources/prettyprinter-configurable/1.8.0.0/meta.toml
=> Publish 1.8.0.0 for plutus core packages

_sources/cardano-api/8.6.0.0/meta.toml
=> Add `cardano-api-8.6.0.0`

_sources/cardano-api/8.7.0.0/meta.toml
From https://github.com/input-output-hk/cardano-api at 08a8c9dd31bea4ae8e5e24ff17a4f335680cd569
=> Added cardano-api-8.7.0.0

_sources/byron-spec-chain/0.1.1.2/meta.toml, _sources/byron-spec-chain/0.1.1.2/revisions/2.cabal, _sources/cardano-client/0.1.0.3/meta.toml
- Added cardano-client-0.1.0.3
- byron-spec-chain-0.1.1.2 revision
=> coot/cardano client 0.1.0.3

_sources/ouroboros-consensus-cardano/0.7.0.0/meta.toml, _sources/ouroboros-consensus-cardano/0.7.0.0/revisions/1.cabal
=> ouroboros-consensus-cardano: remove beacon

_sources/cardano-ledger-conway-test/1.2.0.3/meta.toml, _sources/cardano-ledger-conway/1.6.0.0/meta.toml, _sources/cardano-ledger-pretty/1.2.1.2/meta.toml, _sources/ouroboros-consensus-cardano/0.7.0.0/meta.toml, _sources/ouroboros-consensus-cardano/0.7.0.0/revisions/2.cabal
This release fixes an infinite loop in one of the Conway rules
=> New conway release

_sources/cardano-api/8.8.0.0/meta.toml
=> Add `cardano-api-8.8.0.0`

_sources/cardano-cli/8.3.0.0/meta.toml
From https://github.com/input-output-hk/cardano-cli at 9b37ee04e4d080fd2e6d3a609c8fb0929a851b0a
=> Added cardano-cli-8.3.0.0

scripts/add-revision.sh
- Shellcheck lints
- Update add-revision script to new paths
=> Fix add-revision script

_sources/cardano-cli/8.3.1.0/meta.toml
From https://github.com/input-output-hk/cardano-cli at 2288dc0fc8b7eadba6ff1e7ebf7f2946bd27dcff
=> Added cardano-cli-8.3.1.0

_sources/optparse-applicative-fork/0.18.1.0/meta.toml
From https://github.com/input-output-hk/optparse-applicative at a85e8bcef4c3411aa3353e472b84e1ce46a83d7d
=> Added `optparse-applicative-fork-0.18.1.0`

_sources/cardano-api-gen/8.1.1.0/meta.toml, _sources/cardano-api/8.8.1.0/meta.toml
=> cardano-api 8.8.1.0 cardano-api-gen 8.1.1.0

_sources/plutus-core/1.8.0.0/meta.toml, _sources/plutus-core/1.8.0.0/revisions/1.cabal, result
=> Revise plutus-core-1.8.0.0 to have a higher lower bound on cardano-crypto-class

_sources/diff-containers/1.1.0.0/meta.toml, _sources/fingertree-rm/1.0.0.1/meta.toml
=> `diff-containers-1.1.0.0`, `fingertree-rm-1.0.0.1`

_sources/cardano-ledger-conway/1.6.1.0/meta.toml
From https://github.com/input-output-hk/cardano-ledger at 02a2d963050d56423a969107b983381854318a89
=> Added cardano-ledger-conway-1.6.1.0

_sources/cardano-api-gen/8.1.1.1/meta.toml, _sources/cardano-api/8.8.1.1/meta.toml
=> Update cardano api and cardano-api-gen

.github/workflows/CI.yml, result
=> Tar built repository before uploading it as artifact

_sources/cardano-cli/8.3.2.0/meta.toml
From https://github.com/input-output-hk/cardano-cli at 34d985d17234910accbde0b19941bd8c028d4e2f
=> Added cardano-cli-8.3.2.0

_sources/ouroboros-network-framework/0.7.0.0/meta.toml, _sources/ouroboros-network-protocols/0.5.1.0/meta.toml, _sources/ouroboros-network/0.8.2.0/meta.toml
From https://github.com/input-output-hk/ouroboros-network at f84fcddce472d6cfc2b838b20a2ad085fe0896ed
=> Added ouroboros-network-0.8.2.0

_sources/plutus-core/1.5.0.0/meta.toml, _sources/plutus-core/1.5.0.0/revisions/1.cabal, _sources/plutus-core/1.5.0.1/meta.toml, _sources/plutus-core/1.5.0.1/revisions/1.cabal, _sources/plutus-ledger-api/1.5.0.1/meta.toml
From https://github.com/input-output-hk/plutus at 7d730071f4ea4f571379fde3ec7b3d194f15cc13
=> Added plutus-ledger-api-1.5.0.1

_sources/cardano-api/8.9.0.0/meta.toml
From https://github.com/input-output-hk/cardano-api at 64bf8c6b15ad1984a7b5de88194bea9c0e697f01
=> Added cardano-api-8.9.0.0

_sources/plutus-ledger-api/1.7.0.1/meta.toml
From https://github.com/input-output-hk/plutus at 974f70414c18f51b7dcb968b5611ece1b718c53e
=> Added plutus-ledger-api-1.7.0.1

_sources/cardano-ledger-conway/1.6.3.0/meta.toml
From https://github.com/input-output-hk/cardano-ledger at 60070f8fdbb2f30f77c3a5efb4e10503853f1073
=> Added cardano-ledger-conway-1.6.3.0

_sources/cardano-cli/8.3.3.0/meta.toml
From https://github.com/input-output-hk/cardano-cli at b2fff09b149bc38f476b9b348704b7d3e36bf180
=> Added cardano-cli-8.3.3.0

_sources/cardano-api/8.10.0.0/meta.toml
From https://github.com/input-output-hk/cardano-api at 0e3edca0b947295f61c514f845ae1033301cc6f7
=> Added cardano-api-8.10.0.0

_sources/cardano-cli/8.1.2/meta.toml, _sources/cardano-cli/8.1.2/revisions/1.cabal, _sources/cardano-node/8.1.2/meta.toml
From https://github.com/input-output-hk/cardano-node at 862e62d8c7e0586aacd575d307cf48ff647fcf22
=> Added cardano-node-8.1.2

_sources/cardano-cli/8.4.0.0/meta.toml
From https://github.com/input-output-hk/cardano-cli at be025cbd9152d847a03e61f80ceb7865037caa08
=> Added cardano-cli-8.4.0.0

_sources/cardano-cli/8.3.4.0/meta.toml
From https://github.com/input-output-hk/cardano-cli at e98bea0154c1da710c6fb83e4d6bdbd030a74ad8
=> Added cardano-cli-8.3.4.0

_sources/cardano-api/8.10.1.0/meta.toml
From https://github.com/input-output-hk/cardano-api at 8eba7753072b1c2cc063c5b92345f82cfc66d419
=> Added cardano-api-8.10.1.0

_sources/cardano-api/8.8.1.2/meta.toml
From https://github.com/input-output-hk/cardano-api at 902648edc8eb712e4682ef3785e0ecb17cbe6076
=> Added cardano-api-8.8.1.2

_sources/protolude/0.3.3.0.0.0.0.1/meta.toml
=> Remove extraneous trailing slash from protolude's meta.toml

_sources/cardano-api/8.10.2.0/meta.toml
From https://github.com/input-output-hk/cardano-api at 84a690d5404e7fd998959d2a5b04fa0ad26bd73f
=> Added cardano-api-8.10.2.0

CODEOWNERS, _sources/strict-checked-vars/0.1.0.0/meta.toml
=> `strict-checked-vars-0.1.0.0`

_sources/cardano-api/8.11.0.0/meta.toml
From https://github.com/input-output-hk/cardano-api at fbaa3c9d2d4ab43643a009c14890219d96dc927b
=> Added `cardano-api-8.11.0.0`

_sources/cardano-cli/8.4.1.0/meta.toml
From https://github.com/input-output-hk/cardano-cli at b2bb5da397077e63badc1d093105cd72db2f3d16
=> Added `cardano-cli-8.4.1.0`

_sources/cardano-lmdb-simple/0.6.1.1/meta.toml
From https://github.com/input-output-hk/lmdb-simple at 5e7e9e37dbc34d882cc0c5dcd63a2a69c0e32122
=> Added cardano-lmdb-simple-0.6.1.1

_sources/diff-containers/1.1.10/meta.toml
From https://github.com/input-output-hk/anti-diffs at fa51ada9fbb03279e7a4bcfbf9c6f83b97b41f4e
=> Added diff-containers-1.1.10

_sources/strict-checked-vars/0.1.0.1/meta.toml
From https://github.com/input-output-hk/cardano-base at 4427205b436ae3cc154c467a0ace918942e64e1b
=> Added strict-checked-vars-0.1.0.1

_sources/cardano-api/8.11.1.0/meta.toml
From https://github.com/input-output-hk/cardano-api at 9f61feee9d89ce09b77dfffbb2dbcdfbdce8d35e
=> Added cardano-api-8.11.1.0

_sources/strict-checked-vars/0.1.0.2/meta.toml
From https://github.com/input-output-hk/cardano-base at c3fb1294a6a19e9e01b58bd7967462f029005ddb
=> Added strict-checked-vars-0.1.0.2

_sources/strict-checked-vars/0.1.0.3/meta.toml
From https://github.com/input-output-hk/cardano-base at f54cdd877c6e03bab3950f6eaa74a80881b4dcc8
=> Added strict-checked-vars-0.1.0.3

_sources/cardano-api/8.12.0.0/meta.toml
From https://github.com/input-output-hk/cardano-api at 7bced7a4b2403f74f96393a4579dece5bb576b71
=> Added cardano-api-8.12.0.0

_sources/cardano-cli/8.5.0.0/meta.toml
From https://github.com/input-output-hk/cardano-cli at aebdcce52df97072c54858a99a287bb4a2f9acfe
=> Added cardano-cli-8.5.0.0

_sources/cardano-node-chairman/8.2.0/meta.toml, _sources/cardano-node-chairman/8.2.0/revisions/1.cabal, _sources/cardano-node/8.2.1/meta.toml, _sources/cardano-submit-api/3.1.3/meta.toml, _sources/cardano-testnet/8.2.0/meta.toml, _sources/plutus-scripts-bench/1.0.0.1/meta.toml, _sources/tx-generator/2.6/meta.toml
From https://github.com/input-output-hk/cardano-node at 0fd7e6afbb3e953b20e06fe1fe7114f6d4cff804
=> Added cardano-node-8.2.1

_sources/cardano-git-rev/0.1.2.0/meta.toml
From https://github.com/input-output-hk/cardano-node at 892b6202eafef2c0c66b1e6d51d8fc1b8d5d7619
=> Added cardano-git-rev-0.1.2.0

_sources/cardano-client/0.3.0.0/meta.toml, _sources/cardano-ping/0.2.0.6/meta.toml, _sources/network-mux/0.4.0.0/meta.toml, _sources/network-mux/0.4.0.0/revisions/1.cabal, _sources/ouroboros-network-api/0.5.1.0/meta.toml, _sources/ouroboros-network-framework/0.8.0.0/meta.toml, _sources/ouroboros-network-protocols/0.5.2.0/meta.toml, _sources/ouroboros-network-testing/0.3.1.0/meta.toml, _sources/ouroboros-network/0.9.0.0/meta.toml
- Added cardano-client-0.3.0.0
- Added cardano-ping-0.2.0.6
- Added ouroboros-network-0.9.0.0
- Added ouroboros-network-api-0.5.1.0
- Added ouroboros-network-framework-0.8.0.0
- Added ouroboros-network-protocols-0.5.2.0
- Added ouroboros-network-testing-0.3.1.0
- network-mux-0.4.0.0 revision
=> network/release: ouroboros-network-0.9.0.0

_sources/cardano-api/8.13.0.0/meta.toml
From https://github.com/input-output-hk/cardano-api at 54296fbc814732dbca4fd15a43b286f2c4ca3d7d
=> Added cardano-api-8.13.0.0

_sources/cardano-api/8.13.1.0/meta.toml
From https://github.com/input-output-hk/cardano-api at 3c2c27069ef97715ec813cc6b5bf1cabe72bc708
=> Added cardano-api-8.13.1.0

CODEOWNERS, _sources/aeson-record/0.1.0.0/meta.toml, _sources/byron-spec-chain/0.1.0.0/meta.toml, _sources/byron-spec-chain/0.1.0.0/revisions/1.cabal, _sources/marlowe-cardano/0.1.2.0/meta.toml, _sources/marlowe-chain-sync/0.0.4/meta.toml, _sources/marlowe-client/0.0.4/meta.toml, _sources/marlowe-object/0.1.0.0/meta.toml, _sources/marlowe-object/0.1.0.0/revisions/1.cabal, _sources/marlowe-protocols/0.2.0.0/meta.toml, _sources/marlowe-runtime-web/0.0.4/meta.toml, _sources/marlowe-runtime/0.0.4/meta.toml, _sources/marlowe-test/0.1.3.0/meta.toml, flake.nix
=> Marlowe lib updates

_sources/cardano-api/8.14.0.0/meta.toml, _sources/cardano-api/8.14.0.0/revisions/1.cabal, _sources/cardano-ledger-allegra/1.2.1.1/meta.toml, _sources/cardano-ledger-alonzo-test/1.1.2.3/meta.toml, _sources/cardano-ledger-alonzo/1.4.0.0/meta.toml, _sources/cardano-ledger-api/1.4.0.0/meta.toml, _sources/cardano-ledger-babbage-test/1.1.1.4/meta.toml, _sources/cardano-ledger-babbage/1.4.3.0/meta.toml, _sources/cardano-ledger-binary/1.1.2.0/meta.toml, _sources/cardano-ledger-conway-test/1.2.0.4/meta.toml, _sources/cardano-ledger-conway/1.7.0.0/meta.toml, _sources/cardano-ledger-core/1.5.0.0/meta.toml, _sources/cardano-ledger-mary/1.3.2.0/meta.toml, _sources/cardano-ledger-pretty/1.3.0.0/meta.toml, _sources/cardano-ledger-shelley-ma-test/1.2.1.2/meta.toml, _sources/cardano-ledger-shelley-test/1.2.0.3/meta.toml, _sources/cardano-ledger-shelley/1.5.0.0/meta.toml, _sources/cardano-protocol-tpraos/1.0.3.4/meta.toml
This is a release of all updated packages from ledger master, which is needed for current integration efforts and the upcoming release of cardano-node-8.3
=> Ledger release for 8.3

_sources/ekg-forward/0.4/meta.toml
From https://github.com/input-output-hk/ekg-forward at 5f5423b1b498a8bf0d33d869ac283eb7abb18b38
=> Added ekg-forward-0.4

_sources/cardano-api-gen/8.2.0.0/meta.toml, _sources/cardano-api/8.15.0.0/meta.toml
=> Mgalazyn/cardano api 8.15.0.0

_sources/cardano-api/8.16.0.0/meta.toml
From https://github.com/input-output-hk/cardano-api at a01de2aa1f9d11d795c61171d6dea6ab83ac489c
=> Added cardano-api-8.16.0.0

_sources/cardano-cli/8.6.0.0/meta.toml
From https://github.com/input-output-hk/cardano-cli at e198717d59768cee7a0283d2dc4b673f943576d7
=> Added cardano-cli-8.6.0.0

_sources/cardano-api/8.16.1.0/meta.toml
From https://github.com/input-output-hk/cardano-api at de57d4e495b96a0459be81b96fca0d8e104ba9ae
=> Added cardano-api-8.16.1.0

_sources/cardano-ledger-conway/1.7.1.0/meta.toml, _sources/cardano-ledger-shelley/1.5.1.0/meta.toml, flake.nix
Minor releases of two packages: https://github.com/input-output-hk/cardano-ledger/pull/3677
=> Patch conway and shelley packages to fix DRep stake distribution

_sources/plutus-core/1.11.0.0/meta.toml, _sources/plutus-ledger-api/1.11.0.0/meta.toml, _sources/plutus-tx-plugin/1.11.0.0/meta.toml, _sources/plutus-tx/1.11.0.0/meta.toml, _sources/prettyprinter-configurable/1.11.0.0/meta.toml
=> Release plutus 1.11.0.0

_sources/cardano-api/8.17.0.0/meta.toml
From https://github.com/input-output-hk/cardano-api at 28b9396b48a5df73c17cb1d8867d8454f8b2295d
=> Added cardano-api-8.17.0.0

_sources/cardano-api/8.16.2.0/meta.toml
From https://github.com/input-output-hk/cardano-api at 24b51cb8dc007b4f82ae089d745f2df81e128bbf
=> Added cardano-api-8.16.2.0

_sources/cardano-cli/8.7.0.0/meta.toml
From https://github.com/input-output-hk/cardano-cli at 1bd1804f7adeaba3220b446f5fa799bd927e474e
=> Added cardano-cli-8.7.0.0

_sources/cardano-api/8.18.0.0/meta.toml
From https://github.com/input-output-hk/cardano-api at aaba33e50116957bbf7697c2cfe162d15d92a7b1
=> Added cardano-api-8.18.0.0

_sources/strict-checked-vars/0.1.0.4/meta.toml
From https://github.com/input-output-hk/cardano-base at a00c5bd625ff003ac4af5ac8f8bf7c8c9ba6d4d8
=> Added strict-checked-vars-0.1.0.4

_sources/cardano-api/8.17.1.0/meta.toml
From https://github.com/input-output-hk/cardano-api at 73ec41cc236ac950ad0a99e92877a03b4b3670e3
=> Added cardano-api-8.17.1.0

_sources/cardano-api/8.16.3.0/meta.toml
From https://github.com/input-output-hk/cardano-api at 69956be1214daa6792d64847ed5c45ba2868fe8e
=> Added cardano-api-8.16.3.0

_sources/cardano-cli/8.6.1.0/meta.toml
From https://github.com/input-output-hk/cardano-cli at 897cc074ebe38b96999aa22370974154332c3e3a
=> Added cardano-cli-8.6.1.0

_sources/cardano-ledger-allegra/1.2.2.0/meta.toml, _sources/cardano-ledger-alonzo-test/1.1.2.4/meta.toml, _sources/cardano-ledger-alonzo/1.4.1.0/meta.toml, _sources/cardano-ledger-api/1.5.0.0/meta.toml, _sources/cardano-ledger-babbage-test/1.1.1.5/meta.toml, _sources/cardano-ledger-babbage/1.4.4.0/meta.toml, _sources/cardano-ledger-conway-test/1.2.0.5/meta.toml, _sources/cardano-ledger-conway/1.8.0.0/meta.toml, _sources/cardano-ledger-core/1.6.0.0/meta.toml, _sources/cardano-ledger-mary/1.3.3.0/meta.toml, _sources/cardano-ledger-pretty/1.3.1.0/meta.toml, _sources/cardano-ledger-shelley-ma-test/1.2.1.3/meta.toml, _sources/cardano-ledger-shelley-test/1.2.0.4/meta.toml, _sources/cardano-ledger-shelley/1.6.0.0/meta.toml, _sources/cardano-protocol-tpraos/1.0.3.5/meta.toml, _sources/ekg-forward/0.4/meta.toml, _sources/ekg-forward/0.4/revisions/1.cabal, flake.nix
- ekg-forward-0.4 revision
- Added cardano-ledger-allegra-1.2.2.0
- Added cardano-ledger-alonzo-1.4.1.0
- Added cardano-ledger-alonzo-test-1.1.2.4
- Added cardano-ledger-babbage-1.4.4.0
- Added cardano-ledger-babbage-test-1.1.1.5
- Added cardano-ledger-conway-1.8.0.0
- Added cardano-ledger-conway-test-1.2.0.5
- Added cardano-ledger-mary-1.3.3.0
- Added cardano-ledger-shelley-1.6.0.0
- Added cardano-ledger-shelley-test-1.2.0.4
- Added cardano-ledger-shelley-ma-test-1.2.1.3
- Added cardano-ledger-api-1.5.0.0
- Added cardano-ledger-core-1.6.0.0
- Added cardano-ledger-pretty-1.3.1.0
- Added cardano-protocol-tpraos-1.0.3.5
=> Release cardano-ledger and revise ekg-forward

.github/workflows/CI.yml, scripts/add-from-github.sh, scripts/check-archive-extension.sh, scripts/check.sh, scripts/compare-package-metadata.sh, scripts/current-timestamp.sh, scripts/fetch-github-cabal-files.sh, scripts/list-latest-package-versions.sh, scripts/update-chap-deps.sh, scripts/update-timestamps-and-fixup.sh, scripts/update-timestamps-in-revision.sh, scripts/version-lookup.sh
This should help ensure we have our shell scripts checked and changes won't introduce unexpected behaviour.
=> Add shellcheck to CI

README.md
=> Update shell script usage

_sources/cardano-api/8.19.0.0/meta.toml
From https://github.com/input-output-hk/cardano-api at 6cf16e5636358cabeeba57142a95f9b58d06f8f3
=> Added cardano-api-8.19.0.0

_sources/cardano-node/8.3.1/meta.toml, _sources/cardano-submit-api/3.1.4/meta.toml, _sources/trace-dispatcher/2.1.0/meta.toml, _sources/trace-forward/2.1.0/meta.toml
From https://github.com/input-output-hk/cardano-node at 2f041a1b21233ced41e2f8a8bca20e97ed257f0d
=> Added cardano-node-8.3.1

flake.nix
Let's observe the carnage and see if we can start enabling this.
=> GHC 9.6 CI

README.md
Improve the overview in way that _might_ have helped me debug a related failure had @michaelpj not been available.
=> Mention Haddock pass in the README.md high-level summary

_sources/diff-containers/1.1.1.0/meta.toml
From https://github.com/input-output-hk/anti-diffs at fa51ada9fbb03279e7a4bcfbf9c6f83b97b41f4e
=> Added diff-containers-1.1.1.0

_sources/hjsonpointer/1.5.0.0.0.0.0.1/meta.toml
From https://github.com/input-output-hk/hjsonpointer at 78c21e936bdb7a77dd81fb929c2dbb34c7230af0
=> Added hjsonpointer-1.5.0.0.0.0.0.1

_sources/hjsonschema/1.10.0.0.0.0.0.1/meta.toml
From https://github.com/input-output-hk/hjsonschema at 8ce704c4c4f2e5f2f9699e48e8587a4f85c3b4c7
=> Added hjsonschema-1.10.0.0.0.0.0.1

_sources/cardano-api/8.20.0.0/meta.toml
From https://github.com/input-output-hk/cardano-api at e8da7aebe48a518e73d19d93231d06e8cd60a1b7
=> Added cardano-api-8.20.0.0

_sources/cardano-cli/8.8.0.0/meta.toml
From https://github.com/input-output-hk/cardano-cli at a38c1c6db06f65fdb95271e7549c97960fcabc74
=> Added cardano-cli-8.8.0.0

flake.nix
Rationale here: https://github.com/input-output-hk/cardano-haskell-packages/pull/499#issue-1896514708
=> Add marlowe-runtime as a smoke test package

_sources/cardano-api/8.20.1.0/meta.toml
From https://github.com/input-output-hk/cardano-api at 5bddb49747d3a47a2323f2e2e2490a05a8e3d956
=> Added cardano-api-8.20.1.0

_sources/plutus-core/1.13.0.0/meta.toml, _sources/plutus-ledger-api/1.13.0.0/meta.toml, _sources/plutus-tx-plugin/1.13.0.0/meta.toml, _sources/plutus-tx/1.13.0.0/meta.toml, _sources/prettyprinter-configurable/1.13.0.0/meta.toml
=> Plutus 1.13

_sources/cardano-cli/8.9.0.0/meta.toml
From https://github.com/input-output-hk/cardano-cli at 79264057deda984ca955c36e56c15a5c28e9307a
=> Added cardano-cli-8.9.0.0

_sources/quickcheck-contractmodel/0.1.5.0/meta.toml, _sources/quickcheck-threatmodel/1.1.0/meta.toml, flake.nix
=> quickcheck-contractmodel 0.1.5.0

_sources/cardano-api/8.20.2.0/meta.toml
From https://github.com/input-output-hk/cardano-api at 14d847559301e1357a31f51010392b1a8978ee70
=> Added cardano-api-8.20.2.0

_sources/cardano-api/8.21.0.0/meta.toml
From https://github.com/input-output-hk/cardano-api at 4a2e1fb641e0bded861297a3038adec62a814433
=> Added cardano-api-8.21.0.0

_sources/dependent-sum-template/0.1.1.1.0.0.0.1/meta.toml
From https://github.com/input-output-hk/dependent-sum-template at adb6550fbde9b5b0613d71c65f23bd0fbb46d761
=> Added dependent-sum-template-0.1.1.1.0.0.0.1

_sources/cardano-ledger-allegra/1.2.3.0/meta.toml, _sources/cardano-ledger-alonzo-test/1.1.2.5/meta.toml, _sources/cardano-ledger-alonzo/1.4.2.0/meta.toml, _sources/cardano-ledger-api/1.6.0.0/meta.toml, _sources/cardano-ledger-babbage-test/1.1.1.6/meta.toml, _sources/cardano-ledger-babbage/1.4.5.0/meta.toml, _sources/cardano-ledger-binary/1.1.3.0/meta.toml, _sources/cardano-ledger-conway-test/1.2.1.0/meta.toml, _sources/cardano-ledger-conway/1.9.0.0/meta.toml, _sources/cardano-ledger-core/1.7.0.0/meta.toml, _sources/cardano-ledger-mary/1.3.4.0/meta.toml, _sources/cardano-ledger-pretty/1.3.2.0/meta.toml, _sources/cardano-ledger-shelley-test/1.2.0.5/meta.toml, _sources/cardano-ledger-shelley/1.6.2.0/meta.toml, _sources/cardano-protocol-tpraos/1.0.3.6/meta.toml
And the rest of the packages needed for Conway version bump
=> Cardano ledger conway 1.9.0.0

_sources/cardano-api/8.22.0.0/meta.toml
From https://github.com/input-output-hk/cardano-api at d4f297cf4
=> Added cardano-api-8.22.0.0

_sources/ouroboros-consensus-cardano/0.10.0.0/meta.toml, _sources/ouroboros-consensus-diffusion/0.8.0.1/meta.toml, _sources/ouroboros-consensus-protocol/0.5.0.7/meta.toml, _sources/ouroboros-consensus/0.12.0.0/meta.toml
Corresponding release PR: https://github.com/input-output-hk/ouroboros-consensus/pull/377
=> Release Consensus packages for Node 8.5

flake.lock
=> Bump CHaP pin

_sources/cardano-api/8.23.0.0/meta.toml
From https://github.com/input-output-hk/cardano-api at 49903052391d9fe579863a38f7b7b802a1ee00ca
=> Added `cardano-api-8.23.0.0`

_sources/cardano-api/8.23.1.0/meta.toml
=> Newhoggy/add cardano api 8.23.1.0

_sources/cardano-api/8.24.0.0/meta.toml
From https://github.com/input-output-hk/cardano-api at 8a7542a465ac34c6533aea1c3a107cd4d9c4a7e4
=> Added cardano-api-8.24.0.0

_sources/cardano-api/8.23.2.0/meta.toml
From https://github.com/input-output-hk/cardano-api at 7c25dab1fbe1bcfe63f0a76a8a06e6d5523f8a87
=> Added cardano-api-8.23.2.0

_sources/cardano-api/8.25.0.0/meta.toml
From https://github.com/input-output-hk/cardano-api at 7fe34eb80e3af2bc3ebcc7160bb178d0af874a43
=> Added cardano-api-8.25.0.0

_sources/cardano-api/8.25.0.1/meta.toml
From https://github.com/input-output-hk/cardano-api at dd8e898e1ce331235952799d49f51ac023693344
=> Added cardano-api-8.25.0.1

_sources/cardano-cli/8.10.0.0/meta.toml
From https://github.com/input-output-hk/cardano-cli at 55d627015935f01e6ab43d9ad63e21b5f5338dd3
=> Added cardano-cli-8.10.0.0

_sources/cardano-cli/8.11.0.0/meta.toml
=> Add `cardano-cli-8.11.0.0`

_sources/cardano-api/8.25.2.0/meta.toml
From https://github.com/input-output-hk/cardano-api at dfb2a8f6a325f27985651c6388b54a3fd8d9e951
=> Added cardano-api-8.25.2.0

_sources/cardano-cli/8.12.0.0/meta.toml
From https://github.com/input-output-hk/cardano-cli at b62266fa0d6d6bfd4ff71536deb478c74f9f3997
=> Added cardano-cli-8.12.0.0

_sources/cardano-node/8.5.0/meta.toml, _sources/cardano-submit-api/3.1.7/meta.toml, _sources/trace-dispatcher/2.3.0/meta.toml
From https://github.com/input-output-hk/cardano-node at dbb13dc3219311ee3f3f1c250a5e3dc39d2f678e
=> Added cardano-node-8.5.0

_sources/plutus-core/1.15.0.0/meta.toml, _sources/plutus-ledger-api/1.15.0.0/meta.toml, _sources/plutus-tx-plugin/1.15.0.0/meta.toml, _sources/plutus-tx/1.15.0.0/meta.toml, _sources/prettyprinter-configurable/1.15.0.0/meta.toml
=> Kwxm/plutus 1.15.0.0

_sources/cardano-api/8.26.0.0/meta.toml
From https://github.com/input-output-hk/cardano-api at e631c5b5a2948b857f29a3155a3978c09902fa64
=> Added cardano-api-8.26.0.0

_sources/cardano-api/8.27.0.0/meta.toml
From https://github.com/input-output-hk/cardano-api at ec72630c2a13aea0039d475b0510b1b52c8ad0e8
=> Added cardano-api-8.27.0.0

_sources/cardano-crypto-class/2.1.3.0/meta.toml
From https://github.com/input-output-hk/cardano-base at 79ee04b837bf758bb4565a4fb89c24d119ec2a1e
=> Added cardano-crypto-class-2.1.3.0

_sources/cardano-api/8.28.0.0/meta.toml
From https://github.com/input-output-hk/cardano-api at 8295c207dfc1ae8cd7104e17dc98779793e3b7a9
=> Added cardano-api-8.28.0.0

_sources/typed-protocols/0.1.1.0/meta.toml
From https://github.com/input-output-hk/typed-protocols at e0f008311ce58ea58d61157fa7f93312b6839bd7
=> Added typed-protocols-0.1.1.0

_sources/cardano-ping/0.2.0.7/meta.toml
From https://github.com/input-output-hk/ouroboros-network at b3a3c5214fdcd6c8c4a0faabf4528b664220f81d
=> Added cardano-ping-0.2.0.7

_sources/cardano-data/1.1.1.0/meta.toml, _sources/cardano-ledger-allegra/1.2.3.1/meta.toml, _sources/cardano-ledger-alonzo-test/1.1.2.6/meta.toml, _sources/cardano-ledger-alonzo/1.5.0.0/meta.toml, _sources/cardano-ledger-api/1.7.0.0/meta.toml, _sources/cardano-ledger-babbage-test/1.1.1.7/meta.toml, _sources/cardano-ledger-babbage/1.5.0.0/meta.toml, _sources/cardano-ledger-binary/1.2.0.0/meta.toml, _sources/cardano-ledger-conway-test/1.2.1.1/meta.toml, _sources/cardano-ledger-conway/1.10.0.0/meta.toml, _sources/cardano-ledger-core/1.8.0.0/meta.toml, _sources/cardano-ledger-mary/1.3.5.0/meta.toml, _sources/cardano-ledger-pretty/1.3.3.0/meta.toml, _sources/cardano-ledger-shelley-ma-test/1.2.1.4/meta.toml, _sources/cardano-ledger-shelley-test/1.2.0.6/meta.toml, _sources/cardano-ledger-shelley/1.7.0.0/meta.toml
=> Ledger release for 8.6

_sources/ouroboros-consensus-cardano/0.11.0.0/meta.toml, _sources/ouroboros-consensus-diffusion/0.8.0.2/meta.toml, _sources/ouroboros-consensus-protocol/0.6.0.0/meta.toml, _sources/ouroboros-consensus/0.13.0.0/meta.toml
=> ouroboros-consensus  packages for 8.6

_sources/cardano-api/8.29.0.0/meta.toml
From https://github.com/input-output-hk/cardano-api at 38e3b148facc09e381a2127a698dd3b5230d12c0
=> cardano-api package for 8.6 

_sources/cardano-cli/8.13.0.0/meta.toml
From https://github.com/input-output-hk/cardano-cli at d4eaabdcde1f650fee17ec6b31906c0f2913f0d8
=> cardano-cli package for 8.6 

_sources/cardano-crypto-class/2.1.4.0/meta.toml, _sources/cardano-data/1.1.1.0/meta.toml, _sources/cardano-data/1.1.1.0/revisions/1.cabal, flake.lock
From https://github.com/input-output-hk/cardano-base at a4b01d1b990fab63505f2c20b79ccbbed033f3fc
=> Added cardano-crypto-class-2.1.4.0

_sources/cardano-node-chairman/8.6.0/meta.toml, _sources/cardano-node/8.6.0/meta.toml, _sources/cardano-submit-api/3.1.8/meta.toml, _sources/cardano-testnet/8.6.0/meta.toml, _sources/plutus-scripts-bench/1.0.0.5/meta.toml, _sources/trace-dispatcher/2.4.0/meta.toml, _sources/tx-generator/2.9/meta.toml, flake.nix, result
=> cardano-node packages  8.6

_sources/cardano-api/8.30.0.0/meta.toml
From https://github.com/input-output-hk/cardano-api at 95dbeb718106cce98452130018ba7dc4fc403b8e
=> Added cardano-api-8.30.0.0

_sources/cardano-cli/8.14.0.0/meta.toml
From https://github.com/input-output-hk/cardano-cli at 66415fff7ad86b3de645325a57f12114fd8915b3
=> Added cardano-cli-8.14.0.0

_sources/cardano-api/8.31.0.0/meta.toml
=> Newhoggy/add cardano api 8.31.0.0

_sources/cardano-data/1.1.2.0/meta.toml, _sources/cardano-ledger-allegra/1.2.5.0/meta.toml, _sources/cardano-ledger-alonzo-test/1.1.2.7/meta.toml, _sources/cardano-ledger-alonzo/1.5.1.0/meta.toml, _sources/cardano-ledger-api/1.7.0.1/meta.toml, _sources/cardano-ledger-babbage-test/1.1.1.8/meta.toml, _sources/cardano-ledger-babbage/1.5.1.0/meta.toml, _sources/cardano-ledger-binary/1.2.1.0/meta.toml, _sources/cardano-ledger-byron/1.0.0.3/meta.toml, _sources/cardano-ledger-conway-test/1.2.1.2/meta.toml, _sources/cardano-ledger-conway/1.11.0.0/meta.toml, _sources/cardano-ledger-core/1.9.0.0/meta.toml, _sources/cardano-ledger-mary/1.4.0.0/meta.toml, _sources/cardano-ledger-pretty/1.3.3.1/meta.toml, _sources/cardano-ledger-shelley-ma-test/1.2.1.5/meta.toml, _sources/cardano-ledger-shelley-test/1.3.0.0/meta.toml, _sources/cardano-ledger-shelley/1.8.0.0/meta.toml, _sources/cardano-protocol-tpraos/1.0.3.7/meta.toml
=> Ledger release for Node 8.7.0

_sources/plutus-core/1.16.0.0/meta.toml, _sources/plutus-ledger-api/1.16.0.0/meta.toml, _sources/plutus-tx-plugin/1.16.0.0/meta.toml, _sources/plutus-tx/1.16.0.0/meta.toml, _sources/prettyprinter-configurable/1.16.0.0/meta.toml
=> Kwxm/plutus 1.16.0.0

_sources/ouroboros-consensus-cardano/0.12.0.0/meta.toml, _sources/ouroboros-consensus-diffusion/0.9.0.0/meta.toml, _sources/ouroboros-consensus/0.13.0.1/meta.toml
=> Consensus packages for node 8.7.0

_sources/fs-api/0.2.0.0/meta.toml, _sources/fs-api/0.2.0.0/revisions/1.cabal, _sources/fs-sim/0.2.1.0/meta.toml, _sources/fs-sim/0.2.1.0/revisions/1.cabal
=> Revise fs-api and fs-sim for newer io-classes

_sources/cardano-api/8.32.0.0/meta.toml
From https://github.com/input-output-hk/cardano-api at ef4882cd71a6d57ff1d12b46553448266d6a8ec7
=> Added cardano-api-8.32.0.0

_sources/cardano-ping/0.2.0.9/meta.toml, _sources/network-mux/0.4.3.0/meta.toml, _sources/ouroboros-network-api/0.6.0.1/meta.toml, _sources/ouroboros-network-framework/0.10.1.0/meta.toml, _sources/ouroboros-network-protocols/0.6.0.1/meta.toml, _sources/ouroboros-network-testing/0.4.0.1/meta.toml, _sources/ouroboros-network/0.10.0.1/meta.toml
=> Network release

_sources/ouroboros-consensus-diffusion/0.9.0.0/meta.toml, _sources/ouroboros-consensus-diffusion/0.9.0.0/revisions/1.cabal, _sources/ouroboros-consensus/0.13.0.1/meta.toml, _sources/ouroboros-consensus/0.13.0.1/revisions/1.cabal
=> Add consensus revisions for newer io-classes

_sources/cardano-api/8.33.0.0/meta.toml
From https://github.com/input-output-hk/cardano-api at 6767351e07a9d4ed331b8837482c88953e9f8a1b
=> Added cardano-api-8.33.0.0

_sources/cardano-cli/8.15.0.0/meta.toml
From https://github.com/input-output-hk/cardano-cli at 7a2c3514aa06a3fe72eb75dace02687884e192d6
=> Added cardano-cli-8.15.0.0

_sources/cardano-api/8.34.0.0/meta.toml
From https://github.com/input-output-hk/cardano-api at 13741a229ae93011b9f17dd53bb0c68dbe533c84
=> Added cardano-api-8.34.0.0

_sources/cardano-binary/1.7.0.1/meta.toml, _sources/cardano-binary/1.7.0.1/revisions/1.cabal, _sources/cardano-crypto-praos/2.1.2.0/meta.toml, _sources/cardano-crypto-praos/2.1.2.0/revisions/1.cabal, _sources/cardano-crypto-tests/2.1.2.0/meta.toml, _sources/cardano-crypto-tests/2.1.2.0/revisions/1.cabal, _sources/cardano-slotting/0.1.1.1/meta.toml, _sources/cardano-slotting/0.1.1.1/revisions/1.cabal, flake.lock
=> Bump base upper bounds of some cardano-base packages (needed for ghc-9.8).

_sources/plutus-core/1.17.0.0/meta.toml, _sources/plutus-ledger-api/1.17.0.0/meta.toml, _sources/plutus-tx-plugin/1.17.0.0/meta.toml, _sources/plutus-tx/1.17.0.0/meta.toml, _sources/prettyprinter-configurable/1.17.0.0/meta.toml
=> Plutus 1.17

_sources/strict-checked-vars/0.1.0.3/meta.toml, _sources/strict-checked-vars/0.1.0.3/revisions/2.cabal
=> strict-checked-vars: Bump base dependency

_sources/cardano-slotting/0.1.1.1/meta.toml, _sources/cardano-slotting/0.1.1.1/revisions/2.cabal
=> cardano-slotting: Bump base dependency

_sources/cardano-api/8.34.1.0/meta.toml
From https://github.com/input-output-hk/cardano-api at 4ce369ac058936368914a9bf8d983e2812a94573
=> Added cardano-api-8.34.1.0

_sources/strict-checked-vars/0.1.0.4/meta.toml, _sources/strict-checked-vars/0.1.0.4/revisions/2.cabal
=> strict-checked-vars-0.1.0.4: Bump base revision

_sources/plutus-core/1.15.0.1/meta.toml, _sources/plutus-ledger-api/1.15.0.1/meta.toml, _sources/plutus-ledger-api/1.15.0.1/revisions/1.cabal, _sources/plutus-tx-plugin/1.15.0.1/meta.toml, _sources/plutus-tx/1.15.0.1/meta.toml
=> Plutus 1.15.0.1

_sources/cardano-cli/8.16.0.0/meta.toml
From https://github.com/input-output-hk/cardano-cli at d00a7d45fcb7750288679f9c2a4ce8915a75aed9
=> Added cardano-cli-8.16.0.0

_sources/cardano-binary/1.7.1.0/meta.toml, _sources/cardano-slotting/0.1.2.0/meta.toml
=> Release `cardano-slotting` and `cardano-binary`

_sources/cardano-cli/8.16.0.1/meta.toml
From https://github.com/input-output-hk/cardano-cli at 06e27c924f7e98767602a5092165fc309886214f
=> Added cardano-cli-8.16.0.1

_sources/ouroboros-network-api/0.6.1.0/meta.toml, _sources/ouroboros-network/0.10.1.0/meta.toml
ouroboros-network and ouroboros-network-api release
=> Added ouroboros-network-0.10.1.0

_sources/fs-api/0.2.0.1/meta.toml, _sources/fs-sim/0.2.1.1/meta.toml
=> `fs-api-0.2.0.1`, `fs-sim-0.2.1.1`

_sources/ouroboros-consensus-cardano/0.12.1.0/meta.toml, _sources/ouroboros-consensus-diffusion/0.9.0.0/meta.toml, _sources/ouroboros-consensus-diffusion/0.9.0.0/revisions/2.cabal, _sources/ouroboros-consensus-protocol/0.6.0.0/meta.toml, _sources/ouroboros-consensus-protocol/0.6.0.0/revisions/1.cabal, _sources/ouroboros-consensus/0.14.0.0/meta.toml
=> Consensus for node 8.7.1

_sources/cardano-api/8.34.1.0/meta.toml, _sources/cardano-api/8.34.1.0/revisions/1.cabal, _sources/cardano-node/8.7.0/meta.toml, _sources/cardano-node/8.7.0/revisions/1.cabal, _sources/ouroboros-consensus-cardano/0.12.0.0/meta.toml, _sources/ouroboros-consensus-cardano/0.12.0.0/revisions/1.cabal
=> Revisions for text-1.2.5.0

_sources/cardano-api/8.35.0.0/meta.toml, _sources/cardano-api/8.35.0.0/revisions/1.cabal
=> Revise cardano-api 8.15 for latest consensus

_sources/cardano-cli/8.17.0.0/meta.toml
From https://github.com/input-output-hk/cardano-cli at e62ea2f94a7e1bc3211f9a538093d20718a3c76b
=> Added cardano-cli-8.17.0.0

_sources/cardano-node/8.7.2/meta.toml, _sources/cardano-submit-api/3.2.1/meta.toml
=> Add cardano-node 8.7.2 & cardano-submit-api-3.2.1

_sources/strict-checked-vars/0.2.0.0/meta.toml
From https://github.com/input-output-hk/cardano-base at e545ee648cb7ef9d2715286dbc38987ffc3b5e4d
=> Added strict-checked-vars-0.2.0.0

_sources/ouroboros-network/0.10.2.2/meta.toml
From https://github.com/input-output-hk/ouroboros-network at ce4476555356c0432bb15916e6a4ff73d0ee0e4e
=> Added ouroboros-network-0.10.2.2

_sources/cardano-node/8.7.3/meta.toml
From https://github.com/input-output-hk/cardano-node at cbff6953a04b5740c1d6e4af0510e4475ae6030a
=> Added cardano-node-8.7.3

README.md, scripts/version-lookup.sh
=> chap: change static site URL to chap.intersectmbo.org

README.md
See also https://github.com/IntersectMBO/cardano-api/pull/405/commits/b7a423b8c194c0fb3026500e285f0c69a1206236
=> Update README.md for proper chap url in docs.

_sources/cardano-testnet/8.7.2/meta.toml
From https://github.com/intersectmbo/cardano-node at cde05e6ce506474bbac81723b2cf5871dc1982ad
=> Added cardano-testnet-8.7.2

_sources/quickcheck-contractmodel/0.1.6.0/meta.toml, _sources/quickcheck-threatmodel/1.2.0/meta.toml
=> quickcheck-contractmodel-0.1.6.0

_sources/cardano-cli/8.18.0.0/meta.toml
From https://github.com/IntersectMBO/cardano-cli at 553092f22f8215d5fd9a73f312a0a04ae81f6a2b
=> Added cardano-cli-8.18.0.0

_sources/cardano-node-emulator/1.3.0.0/meta.toml, _sources/cardano-node-socket-emulator/1.3.0.0/meta.toml, _sources/freer-extras/1.3.0.0/meta.toml, _sources/plutus-ledger/1.3.0.0/meta.toml, _sources/plutus-script-utils/1.3.0.0/meta.toml, flake.nix
=> cardano-node-emulator-1.3.0.0

_sources/plutus-core/1.20.0.0/meta.toml, _sources/plutus-ledger-api/1.20.0.0/meta.toml, _sources/plutus-tx-plugin/1.20.0.0/meta.toml, _sources/plutus-tx/1.20.0.0/meta.toml, _sources/prettyprinter-configurable/1.20.0.0/meta.toml
=> Plutus 1.20

_sources/cardano-api/8.37.1.0/meta.toml
From https://github.com/IntersectMBO/cardano-api at 4794681151a45694ca54d1ff2b94a69178468553
=> Added cardano-api-8.37.1.0

_sources/cardano-cli/8.19.0.0/meta.toml, flake.lock
From https://github.com/IntersectMBO/cardano-cli at 24dd2e18f3dd19133d4bd1c01e144f20a0b6dcbf
=> Added cardano-cli-8.19.0.0

_sources/plutus-core/1.21.0.0/meta.toml, _sources/plutus-ledger-api/1.21.0.0/meta.toml, _sources/plutus-tx-plugin/1.21.0.0/meta.toml, _sources/plutus-tx/1.21.0.0/meta.toml, _sources/prettyprinter-configurable/1.21.0.0/meta.toml
=> Kwxm/plutus 1.21.0.0

_sources/non-integral/1.0.0.0/meta.toml, _sources/non-integral/1.0.0.0/revisions/2.cabal
=> Bump base upper bound on non-integral

_sources/cardano-node/8.7.3/meta.toml, _sources/cardano-node/8.7.3/revisions/1.cabal, _sources/iohk-monitoring/0.1.11.4/meta.toml
From https://github.com/input-output-hk/iohk-monitoring-framework at ef5cd8924f391a83625901e3a39f68b1249ad503
=> Added iohk-monitoring-0.1.11.4

_sources/cardano-api/8.38.0.0/meta.toml, _sources/cardano-api/8.38.0.0/revisions/1.cabal
=> Add a revision to cardano-api-8.38.0.0

_sources/cardano-api/8.38.0.1/meta.toml
From https://github.com/IntersectMBO/cardano-api at f207b42afde8daa64b64ff9d764145ee3974aea6
=> Added cardano-api-8.38.0.1

_sources/cardano-cli/8.20.0.0/meta.toml
From https://github.com/IntersectMBO/cardano-cli at e23c8f5064a634c4c721a47e6207a19907ccbec3
=> Added cardano-cli-8.20.0.0

_sources/cardano-cli/8.20.0.0/meta.toml, _sources/cardano-cli/8.20.0.0/revisions/1.cabal
=> Add a revision to cardano-cli-8.20.0.0

_sources/cardano-api/8.38.0.2/meta.toml
From https://github.com/IntersectMBO/cardano-api at c9ca0f3642c4ea9416dbd6967445286c62f91d08
=> Added cardano-api-8.38.0.2

_sources/cardano-cli/8.20.1.0/meta.toml
From https://github.com/IntersectMBO/cardano-cli at 646baf4d516df5f772bf4d5b14f288533e12f666
=> Added cardano-cli-8.20.1.0

README.md
Hi :wave: 
I've lost some time in #665 while figuring out the problem, I think adding a short note in the README may save some time to beginner users and make this more accessible.
Let me know if you find this valuable and/or you have any comment
=> Add note on iohk-nix overlays in README

_sources/cardano-api-gen/8.2.1.0/meta.toml, _sources/cardano-api/8.39.0.0/meta.toml
=> Release cardano-api-8.39.0.0

README.md
=> Mention `nix flakes` quoting issue in `README`

_sources/typed-protocols/0.1.1.0/meta.toml, _sources/typed-protocols/0.1.1.0/revisions/2.cabal
=> typed-protocols 0.1.1.0 revision

_sources/strict-checked-vars/0.2.0.0/meta.toml, _sources/strict-checked-vars/0.2.0.0/revisions/1.cabal
=> strict-checked-vars revision

_sources/plutus-core/1.22.0.0/meta.toml, _sources/plutus-ledger-api/1.22.0.0/meta.toml, _sources/plutus-tx-plugin/1.22.0.0/meta.toml, _sources/plutus-tx/1.22.0.0/meta.toml, _sources/prettyprinter-configurable/1.22.0.0/meta.toml
=> Plutus 1.22.0.0

_sources/cardano-client/0.3.1.1/meta.toml, _sources/cardano-ping/0.2.0.12/meta.toml, _sources/network-mux/0.4.5.1/meta.toml, _sources/ouroboros-network-api/0.7.0.0/meta.toml, _sources/ouroboros-network-framework/0.11.1.0/meta.toml, _sources/ouroboros-network-protocols/0.8.0.0/meta.toml, _sources/ouroboros-network-testing/0.6.0.0/meta.toml, _sources/ouroboros-network/0.12.0.0/meta.toml
From https://github.com/intersectmbo/ouroboros-network at c86df0277baf00c97df1dd00b6ac413e0ee49e4d
=> Release network packages

_sources/fs-sim/0.2.1.1/meta.toml, _sources/fs-sim/0.2.1.1/revisions/1.cabal
=> fs-sim bump io-classes and strict-stm

_sources/fs-api/0.2.0.1/meta.toml, _sources/fs-api/0.2.0.1/revisions/1.cabal
=> Bump fs-api

_sources/cardano-api/8.39.1.0/meta.toml
From https://github.com/IntersectMBO/cardano-api at 6cd5f03e3871600c0e0ea670b87c57fd27dda431
=> Added cardano-api-8.39.1.0

_sources/ouroboros-consensus-cardano/0.14.0.0/meta.toml, _sources/ouroboros-consensus-diffusion/0.11.0.0/meta.toml, _sources/ouroboros-consensus-protocol/0.7.0.0/meta.toml, _sources/ouroboros-consensus-protocol/0.7.0.0/revisions/1.cabal, _sources/ouroboros-consensus/0.16.0.0/meta.toml
Corresponding release PR: https://github.com/IntersectMBO/ouroboros-consensus/pull/969
=> Release Consensus packages for Node 8.9

README.md
=> Add README note about deprecations

_sources/cardano-api/8.39.2.0/meta.toml
From https://github.com/IntersectMBO/cardano-api at a5c2c776b1c4bfb9bfa9f029d00c52a7feb03095
=> Added cardano-api-8.39.2.0

_sources/cardano-cli/8.20.3.0/meta.toml
From https://github.com/IntersectMBO/cardano-cli at c4b922950541e638caaae8c07292f11c2d6c67cf
=> Added cardano-cli-8.20.3.0

_sources/cardano-node/8.9.0/meta.toml, _sources/cardano-submit-api/3.2.2/meta.toml, _sources/trace-dispatcher/2.5.3/meta.toml, _sources/trace-forward/2.2.3/meta.toml
From https://github.com/IntersectMBO/cardano-node at 184caa6e2d6d35c969a6bbecd6728175423682fb
=> Added cardano-node-8.9.0

_sources/cardano-ping/0.2.0.13/meta.toml
From https://github.com/intersectmbo/ouroboros-network at 68742e7b3afb4b4cedb6df031241168d4cc22065
=> Added cardano-ping-0.2.0.13

_sources/cardano-cli/8.20.3.0/meta.toml, _sources/cardano-cli/8.20.3.0/revisions/1.cabal
=> cardano-cli revision bump cardano-ping

_sources/ouroboros-consensus-cardano/0.14.0.1/meta.toml, _sources/ouroboros-consensus-diffusion/0.11.0.1/meta.toml
Backports of IntersectMBO/ouroboros-consensus#983 and IntersectMBO/ouroboros-consensus#985
=> Fix consensus node 8.9

_sources/plutus-core/1.23.0.0/meta.toml, _sources/plutus-ledger-api/1.23.0.0/meta.toml, _sources/plutus-tx-plugin/1.23.0.0/meta.toml, _sources/plutus-tx/1.23.0.0/meta.toml, _sources/prettyprinter-configurable/1.23.0.0/meta.toml
=> Plutus 1.23.00

_sources/cardano-git-rev/0.2.0.0/meta.toml, _sources/ouroboros-consensus-cardano/0.14.0.1/meta.toml, _sources/ouroboros-consensus-cardano/0.14.0.1/revisions/1.cabal
From https://github.com/IntersectMBO/cardano-base at 113ff707b91e059d7f41ec18b7c1ade481ab7bba
=> Added cardano-git-rev-0.2.0.0

_sources/cardano-api/8.40.0.0/meta.toml
From https://github.com/IntersectMBO/cardano-api at a6733d0b3ce7536acb94b95c3e981fb59582112a
=> Added cardano-api-8.40.0.0

_sources/cardano-api/8.41.0.0/meta.toml
From https://github.com/IntersectMBO/cardano-api at a06c135e484d68341da19cd47746a2d53ae46b48
=> Added cardano-api-8.41.0.0

_sources/ouroboros-consensus-cardano/0.14.1.0/meta.toml, _sources/ouroboros-consensus-diffusion/0.12.0.0/meta.toml
https://github.com/IntersectMBO/ouroboros-consensus/pull/997
=> Release Consensus packages for Node 8.9.1

_sources/ekg-forward/0.5/meta.toml
From https://github.com/input-output-hk/ekg-forward at 18c833c556df6d67b5b01dd1e8b302c1ecaa5aa4
=> Added ekg-forward-0.5

_sources/cardano-api/8.39.3.0/meta.toml
From https://github.com/intersectmbo/cardano-api at 75b2c372a02ca91477f74348d3cc0064677dab4d
=> Added cardano-api-8.39.3.0

_sources/cardano-api/8.42.0.0/meta.toml
From https://github.com/IntersectMBO/cardano-api at 042c80df0b4e53838a2df9818d9ffe58bab3dc68
=> Added cardano-api-8.42.0.0

_sources/ouroboros-network/0.13.1.0/meta.toml
From https://github.com/intersectmbo/ouroboros-network at e8d1721c1a60104f5c208cbdef5987290e5c59e6
=> Added ouroboros-network-0.13.1.0

_sources/cardano-api/8.43.0.0/meta.toml
From https://github.com/input-output-hk/cardano-api at 3999f41ce79a0904b9fbd78afca74bbd36f8c811
=> Added cardano-api-8.43.0.0

_sources/plutus-core/1.24.0.0/meta.toml, _sources/plutus-ledger-api/1.24.0.0/meta.toml, _sources/plutus-tx-plugin/1.24.0.0/meta.toml, _sources/plutus-tx/1.24.0.0/meta.toml, _sources/prettyprinter-configurable/1.24.0.0/meta.toml
=> Plutus 1.24.0.0

_sources/byron-spec-chain/1.0.1.0/meta.toml, _sources/byron-spec-ledger/1.0.1.0/meta.toml, _sources/cardano-crypto-test/1.5.0.2/meta.toml, _sources/cardano-crypto-wrapper/1.5.1.2/meta.toml, _sources/cardano-data/1.2.1.0/meta.toml, _sources/cardano-ledger-allegra/1.4.0.0/meta.toml, _sources/cardano-ledger-alonzo-test/1.2.1.0/meta.toml, _sources/cardano-ledger-alonzo/1.7.0.0/meta.toml, _sources/cardano-ledger-api/1.9.0.0/meta.toml, _sources/cardano-ledger-babbage-test/1.2.0.1/meta.toml, _sources/cardano-ledger-babbage/1.7.0.0/meta.toml, _sources/cardano-ledger-binary/1.3.1.0/meta.toml, _sources/cardano-ledger-byron-test/1.5.1.0/meta.toml, _sources/cardano-ledger-byron/1.0.1.0/meta.toml, _sources/cardano-ledger-conway-test/1.2.1.4/meta.toml, _sources/cardano-ledger-conway/1.13.0.0/meta.toml, _sources/cardano-ledger-core/1.11.0.0/meta.toml, _sources/cardano-ledger-mary/1.5.1.0/meta.toml, _sources/cardano-ledger-shelley-ma-test/1.2.2.0/meta.toml, _sources/cardano-ledger-shelley-test/1.4.0.0/meta.toml, _sources/cardano-ledger-shelley/1.10.0.0/meta.toml, _sources/cardano-protocol-tpraos/1.2.0.0/meta.toml, _sources/ouroboros-consensus-cardano/0.14.2.0/meta.toml, _sources/ouroboros-consensus-cardano/0.14.2.0/revisions/1.cabal, _sources/small-steps/1.1.0.0/meta.toml, result
Ledger packages for node 8.10. 
This PR should be merged only after this one:  https://github.com/IntersectMBO/cardano-ledger/pull/4219 gets merged in ledger.
=> Ledger release 8.10

_sources/ouroboros-network-protocols/0.8.0.0/meta.toml, _sources/ouroboros-network-protocols/0.8.0.0/revisions/1.cabal, _sources/ouroboros-network-protocols/0.8.1.0/meta.toml, _sources/ouroboros-network-protocols/0.8.1.0/revisions/1.cabal
Support cardano-slotting-0.2.0.
=> ouroboros-network-0.8.x revisions

_sources/cardano-ledger-conway/1.13.1.0/meta.toml
From https://github.com/intersectmbo/cardano-ledger at 2b816e58cb714061176d888e6d4c8e57bcc848b2
=> Added cardano-ledger-conway-1.13.1.0

_sources/cardano-api/8.44.0.0/meta.toml
From https://github.com/IntersectMBO/cardano-api at 530d443849680746879821a2bb39b9d2930e1ff2
=> Added cardano-api-8.44.0.0

_sources/cardano-cli/8.22.0.0/meta.toml
From https://github.com/IntersectMBO/cardano-cli at 44d385f0ccd0a32ba524aa3135797ce4f2a11649
=> Added cardano-cli-8.22.0.0

_sources/cardano-lmdb/0.4.0.1/meta.toml
From https://github.com/input-output-hk/haskell-lmdb at 3612b99b911d77de52877bef90bd9fbd5a1e58e5
=> Added cardano-lmdb-0.4.0.1

_sources/plutus-core/1.25.0.0/meta.toml, _sources/plutus-ledger-api/1.25.0.0/meta.toml, _sources/plutus-tx-plugin/1.25.0.0/meta.toml, _sources/plutus-tx/1.25.0.0/meta.toml, _sources/prettyprinter-configurable/1.25.0.0/meta.toml
=> Kwxm/plutus 1.25.0.0 4

_sources/cardano-api/8.39.3.0/meta.toml, _sources/cardano-api/8.39.3.0/revisions/1.cabal, _sources/ouroboros-consensus-cardano/0.14.1.0/meta.toml, _sources/ouroboros-consensus-cardano/0.14.1.0/revisions/1.cabal
* cardano-api: relaxed bounds of ouroboros-consensus-diffusion
* ouroboros-consensus-cardano: relax cardano-git-rev bounds
=> ouroboros-consensus-cardano: relax cardano-git-rev bounds

README.md
I found this useful, maybe someone else does too.
=> README: add worktree approach for getting the built repo

_sources/cardano-api/8.44.0.0/meta.toml, _sources/cardano-api/8.44.0.0/revisions/1.cabal
... which bumps `ouroboros-consensus-diffusion` to `0.15`.
=> Add a revision for cardano-api-8.44.0.0

_sources/cardano-api/8.45.0.0/meta.toml
From https://github.com/IntersectMBO/cardano-api at 380326faf20c60aec963da77e2c0f6f476670f9c
=> Added cardano-api-8.45.0.0

_sources/cardano-api/8.45.1.0/meta.toml
From https://github.com/IntersectMBO/cardano-api at 15b97d18b98cfa9021c01d9be2516dd9b76c51b1
=> Added cardano-api-8.45.1.0

_sources/cardano-cli/8.23.0.0/meta.toml
From https://github.com/IntersectMBO/cardano-cli at 
226f2f4789a683e15fc826b1850b301ffab42d20
=> Added cardano-cli-8.23.0.0

_sources/cardano-data/1.2.2.0/meta.toml, _sources/cardano-ledger-allegra/1.4.1.0/meta.toml, _sources/cardano-ledger-alonzo-test/1.2.1.1/meta.toml, _sources/cardano-ledger-alonzo/1.8.0.0/meta.toml, _sources/cardano-ledger-api/1.9.1.0/meta.toml, _sources/cardano-ledger-babbage/1.8.0.0/meta.toml, _sources/cardano-ledger-binary/1.3.2.0/meta.toml, _sources/cardano-ledger-conway/1.14.0.0/meta.toml, _sources/cardano-ledger-core/1.12.0.0/meta.toml, _sources/cardano-ledger-mary/1.6.0.0/meta.toml, _sources/cardano-ledger-shelley-ma-test/1.2.2.1/meta.toml, _sources/cardano-ledger-shelley-test/1.4.0.1/meta.toml, _sources/cardano-ledger-shelley/1.11.0.0/meta.toml
=> Ledger release for `node-8.11`

_sources/ouroboros-consensus-cardano/0.16.0.0/meta.toml, _sources/ouroboros-consensus-diffusion/0.16.0.0/meta.toml, _sources/ouroboros-consensus-protocol/0.9.0.0/meta.toml, _sources/ouroboros-consensus/0.18.0.0/meta.toml, _sources/sop-extras/0.2.0.0/meta.toml, _sources/strict-sop-core/0.1.1.0/meta.toml, flake.nix
Consensus release PR: https://github.com/IntersectMBO/ouroboros-consensus/pull/1101 (needs to be merged first)
=> Release Consensus packages for Node 8.11

_sources/cardano-api/8.46.0.0/meta.toml
From https://github.com/IntersectMBO/cardano-api at 74e45283f15aaf1831153ab3da1b8e2a8c469b1f
=> Added cardano-api-8.46.0.0

_sources/cardano-cli/8.23.1.0/meta.toml
From https://github.com/IntersectMBO/cardano-cli at ac57ca5f6d9f736eeaa083ca2bb406426e5e8657
=> Added cardano-cli-8.23.1.0

_sources/lobemo-backend-ekg/0.1.1.0/meta.toml
From https://github.com/input-output-hk/iohk-monitoring-framework/commit/998ce323a6eb585d0b4f6e5a664f213474b5160f
=> add lobemo-backend-ekg-0.1.1.0

_sources/cardano-node/8.11.0/meta.toml, _sources/cardano-submit-api/8.11.0/meta.toml, _sources/cardano-tracer/0.2.3/meta.toml, _sources/trace-dispatcher/2.5.6/meta.toml
=> Release for `cardano-node-8.11.0`

_sources/strict-checked-vars/0.2.0.0/meta.toml, _sources/strict-checked-vars/0.2.0.0/revisions/3.cabal
Forgot to bump the other packages
=> Bump strict-stm and strict-mvar

.gitignore, result
Remove ./result link and add result* to gitignore
=> Remove ./result link and add result* to gitignore

_sources/diff-containers/1.2.0.0/meta.toml
From https://github.com/input-output-hk/anti-diffs at 353e0cc86e1aeeffa95821253158376065ac653a
=> Added diff-containers-1.2.0.0

_sources/ouroboros-network/0.16.0.0/meta.toml, _sources/ouroboros-network/0.16.0.0/revisions/1.cabal
=> Revise ouroboros-network-0.16

_sources/cardano-crypto-class/2.1.5.0/meta.toml
From https://github.com/IntersectMBO/cardano-base at 994d5b4
=> Added cardano-crypto-class-2.1.5.0

_sources/cardano-api/8.47.0.0/meta.toml
From https://github.com/IntersectMBO/cardano-api at b2de4f272759fbfa402fb0d9dc92dea34b81b725
=> Added cardano-api-8.47.0.0

_sources/cardano-crypto-tests/2.1.2.0/meta.toml, _sources/cardano-crypto-tests/2.1.2.0/revisions/2.cabal
=> cardano-crypto-tests: Bump base dependency upper bound

_sources/cardano-crypto-praos/2.1.2.0/meta.toml, _sources/cardano-crypto-praos/2.1.2.0/revisions/2.cabal
From https://github.com/IntersectMBO/cardano-base at a9bfdf50b7794c962f73f06763546dc65257720e
=> Bump base dependency in cardano-crypto-praos-2.1.2.0

_sources/cardano-api/8.48.0.1/meta.toml
From https://github.com/IntersectMBO/cardano-api at 5f1b6ba62b8a0bef985560eb3192dc54800b782d
=> Added cardano-api-8.48.0.1

_sources/cardano-cli/8.24.0.0/meta.toml
From https://github.com/IntersectMBO/cardano-cli at 485628fdf004e3baff9d214718e1997d96488e6e
=> Added cardano-cli-8.24.0.0

_sources/cardano-node/8.12.0/meta.toml, _sources/cardano-submit-api/8.12.0/meta.toml, _sources/trace-dispatcher/2.5.8/meta.toml, _sources/trace-forward/2.2.6/meta.toml, _sources/trace-resources/0.2.2.0/meta.toml
From https://github.com/intersectmbo/cardano-node at e69afde9e1da67f7d05c62f48666f0bb6aeb7717
=> Added cardano-node-8.12.0

_sources/cardano-ledger-conway/1.15.1.0/meta.toml, _sources/cardano-ledger-core/1.13.1.0/meta.toml, _sources/cardano-ledger-shelley/1.12.1.0/meta.toml
Waiting for PR to get merged: https://github.com/IntersectMBO/cardano-ledger/pull/4443
=> Ledger release for cardano node 8.12.1

_sources/ouroboros-consensus-cardano/0.14.3.0/meta.toml, _sources/ouroboros-consensus/0.16.1.0/meta.toml
Consensus PR: https://github.com/IntersectMBO/ouroboros-consensus/pull/1167
=> Release Consensus packages for Node 8.9.4

_sources/cardano-data/1.2.3.0/meta.toml, _sources/cardano-ledger-alonzo/1.10.0.0/meta.toml, _sources/cardano-ledger-api/1.9.2.1/meta.toml, _sources/cardano-ledger-babbage/1.8.2.0/meta.toml, _sources/cardano-ledger-conway-test/1.2.1.7/meta.toml, _sources/cardano-ledger-conway/1.16.0.0/meta.toml, _sources/cardano-ledger-core/1.13.2.0/meta.toml, _sources/cardano-ledger-shelley/1.12.2.0/meta.toml
Waiting for https://github.com/IntersectMBO/cardano-ledger/pull/4456
=> Ledger release for `cardano-node-9.0`

_sources/ouroboros-consensus-cardano/0.18.0.0/meta.toml, _sources/ouroboros-consensus-diffusion/0.17.0.1/meta.toml, _sources/ouroboros-consensus-diffusion/0.17.0.1/revisions/1.cabal, _sources/ouroboros-consensus-protocol/0.9.0.1/meta.toml, _sources/ouroboros-consensus-protocol/0.9.0.1/revisions/1.cabal, _sources/ouroboros-consensus/0.20.0.0/meta.toml, flake.lock
Consensus release PR: https://github.com/IntersectMBO/ouroboros-consensus/pull/1176
=> Release Consensus packages for Node 9.0

flake.nix
=> marlowe-runtime: disable for GHC 9.2

_sources/cardano-api/9.0.0.0/meta.toml
From https://github.com/IntersectMBO/cardano-api at 2bea0adca0ca369925ee9f11de01a300c2d53032
=> Added cardano-api-9.0.0.0

_sources/cardano-cli/9.0.0.0/meta.toml
=> Cl/add cardano cli 9.0.0.0

_sources/cardano-node/9.0.0/meta.toml, _sources/cardano-submit-api/9.0.0/meta.toml
cardano-node-9.0.0 and cardano-submit-api-9.0.0 from https://github.com/IntersectMBO/cardano-node/commit/2820a63dc934c6d5b5f450b6c2543b81c6476696
=> Add cardano node 9.0.0

_sources/typed-protocols-cborg/0.1.0.4/meta.toml, _sources/typed-protocols-cborg/0.1.0.4/revisions/2.cabal
=> Bump base dependency for typed-protocols-cborg

_sources/cardano-cli/9.0.0.1/meta.toml
From https://github.com/IntersectMBO/cardano-cli at d32212a9f0751257dd44b5edb1fa1a9d1f9c450a
=> Added cardano-cli-9.0.0.1

_sources/fs-sim/0.2.1.1/meta.toml, _sources/fs-sim/0.2.1.1/revisions/4.cabal
=> Bump base dependency on fs-sim 0.2.1.1

_sources/monoidal-synchronisation/0.1.0.5/meta.toml, _sources/monoidal-synchronisation/0.1.0.5/revisions/1.cabal
=> Bump base depenency for monoidal-synchronisation

_sources/network-mux/0.4.5.2/meta.toml, _sources/network-mux/0.4.5.2/revisions/1.cabal, _sources/quickcheck-monoids/0.1.0.0/meta.toml, _sources/quickcheck-monoids/0.1.0.0/revisions/1.cabal
=> Bump base dependency for two network related packages,

_sources/ouroboros-network-testing/0.6.2.0/meta.toml, _sources/ouroboros-network-testing/0.6.2.0/revisions/1.cabal, _sources/ouroboros-network/0.16.1.1/meta.toml, _sources/ouroboros-network/0.16.1.1/revisions/1.cabal
=> Bump base dependencies for network related packages

_sources/network-mux/0.4.5.2/meta.toml, _sources/network-mux/0.4.5.2/revisions/2.cabal
=> Update base dependency for network-mux

_sources/cardano-api/9.1.0.0/meta.toml
From https://github.com/IntersectMBO/cardano-api at a7af2f29dbc7ae923a7140dddbbbb0f89f760046
https://github.com/IntersectMBO/cardano-api/pull/593
=> Added cardano-api-9.1.0.0

_sources/cardano-cli/9.2.0.0/meta.toml
From https://github.com/IntersectMBO/cardano-cli at 27832209a96de7cecae80890808bbaa530427828
https://github.com/IntersectMBO/cardano-cli/pull/846
=> Added cardano-cli-9.2.0.0

_sources/plutus-core/1.31.0.0/meta.toml, _sources/plutus-ledger-api/1.31.0.0/meta.toml, _sources/plutus-tx-plugin/1.31.0.0/meta.toml, _sources/plutus-tx/1.31.0.0/meta.toml, _sources/prettyprinter-configurable/1.31.0.0/meta.toml
=> Plutus 1.31.0.0

_sources/ouroboros-network-api/0.7.3.0/meta.toml, _sources/ouroboros-network-api/0.7.3.0/revisions/1.cabal, _sources/ouroboros-network-framework/0.13.2.1/meta.toml, _sources/ouroboros-network-framework/0.13.2.1/revisions/1.cabal, _sources/ouroboros-network-mock/0.1.1.1/meta.toml, _sources/ouroboros-network-mock/0.1.1.1/revisions/1.cabal, _sources/ouroboros-network-protocols/0.9.0.0/meta.toml, _sources/ouroboros-network-protocols/0.9.0.0/revisions/1.cabal
=> Bump base dependency on ouroboros-network related packages

_sources/cardano-cli/9.2.1.0/meta.toml
From https://github.com/IntersectMBO/cardano-cli at 5acf8994ba8b486159939ca84b0515d08ee2cd99
https://github.com/IntersectMBO/cardano-cli/pull/847
=> Added cardano-cli-9.2.1.0

_sources/fs-sim/0.2.1.1/meta.toml, _sources/fs-sim/0.2.1.1/revisions/5.cabal, _sources/network-mux/0.4.5.2/meta.toml, _sources/network-mux/0.4.5.2/revisions/3.cabal
Needed for https://github.com/IntersectMBO/ouroboros-consensus/pull/1188
=> Allow containers-0.7 in a few packages

_sources/cuddle/0.3.0.0/meta.toml
From https://github.com/input-output-hk/cuddle at 9b15cf7138c422540831d27f2005b11a7a1302e3
=> Added cuddle-0.2.1.0

_sources/fs-api/0.2.0.1/meta.toml, _sources/fs-api/0.2.0.1/revisions/4.cabal, _sources/latex-svg-image/0.2.0.0.0.1/meta.toml, _sources/latex-svg-image/0.2.0.0.0.1/revisions/2.cabal
(Eventually) for https://github.com/IntersectMBO/ouroboros-consensus/pull/1188
=> Allow filepath-1.5 in a few packages

_sources/sop-extras/0.2.0.0/meta.toml, _sources/sop-extras/0.2.0.0/revisions/1.cabal, _sources/strict-sop-core/0.1.1.0/meta.toml, _sources/strict-sop-core/0.1.1.0/revisions/1.cabal
=> Bump base dependencies

_sources/ouroboros-consensus-cardano/0.18.0.0/meta.toml, _sources/ouroboros-consensus-cardano/0.18.0.0/revisions/1.cabal, _sources/ouroboros-consensus-diffusion/0.17.0.1/meta.toml, _sources/ouroboros-consensus-diffusion/0.17.0.1/revisions/2.cabal, _sources/ouroboros-consensus-protocol/0.9.0.1/meta.toml, _sources/ouroboros-consensus-protocol/0.9.0.1/revisions/2.cabal, _sources/ouroboros-consensus/0.20.0.0/meta.toml, _sources/ouroboros-consensus/0.20.0.0/revisions/1.cabal
=> Bump base dependency for consensus related packages.

_sources/cardano-ping/0.2.0.14/meta.toml, _sources/cardano-ping/0.2.0.14/revisions/1.cabal
=> Bump base dependency for cardano-ping 0.2.0.14

_sources/cardano-api/9.1.0.0/meta.toml, _sources/cardano-api/9.1.0.0/revisions/1.cabal
=> Bump dependencies for cardano-api 9.1.0.0

README.md
=> README.md: Update commands for creating _repo directory

_sources/plutus-core/1.32.0.0/meta.toml, _sources/plutus-ledger-api/1.32.0.0/meta.toml, _sources/plutus-tx-plugin/1.32.0.0/meta.toml, _sources/plutus-tx/1.32.0.0/meta.toml, _sources/prettyprinter-configurable/1.32.0.0/meta.toml
=> Bezirg/plutus 1.32.0.0

_sources/cardano-client/0.3.1.3/meta.toml, _sources/cardano-ping/0.3.0.0/meta.toml, _sources/monoidal-synchronisation/0.1.0.6/meta.toml, _sources/network-mux/0.4.5.3/meta.toml, _sources/ntp-client/0.0.1.6/meta.toml, _sources/ouroboros-network-api/0.8.0.0/meta.toml, _sources/ouroboros-network-framework/0.13.2.2/meta.toml, _sources/ouroboros-network-mock/0.1.1.2/meta.toml, _sources/ouroboros-network-protocols/0.10.0.0/meta.toml, _sources/ouroboros-network-testing/0.7.0.0/meta.toml, _sources/ouroboros-network/0.17.0.0/meta.toml, _sources/quickcheck-monoids/0.1.0.1/meta.toml
From https://github.com/intersectmbo/ouroboros-network at 257688bf555bea529037b307a157d74409586539
=> Release Network Packages (ouroboros-network 0.17 & co)

_sources/iohk-monitoring/0.1.11.5/meta.toml
From https://github.com/input-output-hk/iohk-monitoring-framework at 60b1ce999d14a67926ff150d7924346c56f48043
=> Added iohk-monitoring-0.1.11.5

_sources/ouroboros-consensus-diffusion/0.17.0.1/meta.toml, _sources/ouroboros-consensus-diffusion/0.17.0.1/revisions/3.cabal, _sources/ouroboros-consensus/0.20.0.0/meta.toml, _sources/ouroboros-consensus/0.20.0.0/revisions/2.cabal
=> Bump containers dependency

_sources/ouroboros-consensus-cardano/0.18.0.0/meta.toml, _sources/ouroboros-consensus-cardano/0.18.0.0/revisions/2.cabal
=> ouroboros-consensus-cardano: Bump upper bound for containers

_sources/cardano-cli/9.2.1.0/meta.toml, _sources/cardano-cli/9.2.1.0/revisions/1.cabal
=> cardano-api: Bump upper bounds for base

_sources/ouroboros-consensus-cardano/0.18.0.0/meta.toml, _sources/ouroboros-consensus-cardano/0.18.0.0/revisions/3.cabal
=> ouroboros-consensus-cardano: Bump containers upper bound

_sources/cardano-api/9.2.0.0/meta.toml
From https://github.com/IntersectMBO/cardano-api at 4c4d9acb38829f92cb205b369e24f399dca029e5
=> Added cardano-api-9.2.0.0

_sources/cardano-cli/9.3.0.0/meta.toml
From https://github.com/IntersectMBO/cardano-cli at 5db3edf42b919f083b39265012a4f327d92e6b70
=> Added cardano-cli-9.3.0.0

_sources/cardano-ledger-allegra/1.6.0.0/meta.toml, _sources/cardano-ledger-alonzo/1.10.2.0/meta.toml, _sources/cardano-ledger-api/1.9.3.0/meta.toml, _sources/cardano-ledger-babbage/1.9.0.0/meta.toml, _sources/cardano-ledger-binary/1.3.4.0/meta.toml, _sources/cardano-ledger-conway/1.16.1.0/meta.toml, _sources/cardano-ledger-core/1.14.0.0/meta.toml, _sources/cardano-ledger-mary/1.7.0.0/meta.toml, _sources/cardano-ledger-shelley/1.13.0.0/meta.toml
=> Ledger release for cardano-node-9.2

_sources/cardano-client/0.3.1.4/meta.toml, _sources/cardano-ping/0.4.0.0/meta.toml, _sources/ouroboros-network-api/0.9.0.0/meta.toml, _sources/ouroboros-network-framework/0.13.2.3/meta.toml, _sources/ouroboros-network-protocols/0.10.0.1/meta.toml, _sources/ouroboros-network/0.17.1.0/meta.toml
From https://github.com/intersectmbo/ouroboros-network at 8e20271790c976fc533913ad1ff570dfd3a47512
checked with build-with-chap.sh in ouroboros-network
=> ouroboros-network 0.17.1

_sources/plutus-core/1.33.1.0/meta.toml, _sources/plutus-ledger-api/1.33.1.0/meta.toml, _sources/plutus-tx/1.33.1.0/meta.toml, _sources/prettyprinter-configurable/1.33.1.0/meta.toml
=> Plutus/release 1.33.1.0

_sources/typed-protocols/0.1.1.1/meta.toml, _sources/typed-protocols/0.1.1.1/revisions/1.cabal
=> typed-protocols-0.1.1.1 revision

_sources/cardano-node/9.0.0/meta.toml, _sources/cardano-node/9.0.0/revisions/1.cabal, _sources/iohk-monitoring/0.2.0.0/meta.toml, _sources/lobemo-backend-ekg/0.2.0.0/meta.toml
=> Bump versions of iohk-monitoring and lobemo-backend-ekg

_sources/plutus-core/1.11.0.0/meta.toml, _sources/plutus-core/1.11.0.0/revisions/1.cabal
=> Add revision to plutus-core-1.11.0.0

_sources/cardano-crypto-wrapper/1.4.1/meta.toml, _sources/cardano-crypto-wrapper/1.4.1/revisions/2.cabal, _sources/ouroboros-consensus-cardano/0.19.0.0/meta.toml, _sources/ouroboros-consensus-diffusion/0.17.1.0/meta.toml, _sources/ouroboros-consensus/0.20.1.0/meta.toml, _sources/ouroboros-consensus/0.20.1.0/revisions/1.cabal, _sources/sop-extras/0.2.1.0/meta.toml, _sources/strict-sop-core/0.1.2.0/meta.toml
=> Consensus release for node 9.2

_sources/plutus-tx-plugin/1.33.1.0/meta.toml
From https://github.com/IntersectMBO/plutus at ed52f1b7f3a503edb5a02e64ea251fafeadd295e
=> Added plutus-tx-plugin-1.33.1.0

_sources/cardano-api-gen/9.0.0.0/meta.toml, _sources/cardano-api/9.3.0.0/meta.toml
=> cardano-api-9.3.0.0 cardano-api-gen-9.0.0.0

_sources/cardano-node/9.1.1/meta.toml
From https://github.com/IntersectMBO/cardano-node at efd560070aaf042d1eb4680ae37fc607c7742319
=> Added cardano-node-9.1.1

_sources/cardano-cli/9.4.0.0/meta.toml
From https://github.com/IntersectMBO/cardano-cli at 6777e1321d9dacee6b02c58d05e2346d10f8e975
=> Added cardano-cli-9.4.0.0

_sources/cardano-ping/0.4.0.2/meta.toml
From https://github.com/IntersectMBO/ouroboros-network at 63bbd24859125d257cd96109b15952d816abf1e2
=> Added cardano-ping-0.4.0.2

_sources/cardano-cli/9.4.1.0/meta.toml
From https://github.com/IntersectMBO/cardano-cli at e7e5a86e6db435ed1030fa18985a9f8b35bba1b3
=> Added cardano-cli-9.4.1.0

_sources/plutus-core/1.34.0.0/meta.toml, _sources/plutus-ledger-api/1.34.0.0/meta.toml, _sources/plutus-tx-plugin/1.34.0.0/meta.toml, _sources/plutus-tx/1.34.0.0/meta.toml, _sources/prettyprinter-configurable/1.34.0.0/meta.toml, flake.nix
=> plutus 1.34.0.0

_sources/cuddle/0.3.2.0/meta.toml
From https://github.com/input-output-hk/cuddle at 55d2c65dc6576b2a034616911cee0f3cfedb601c
=> Added cuddle-0.3.2.0

_sources/plutus-core/1.34.1.0/meta.toml, _sources/plutus-ledger-api/1.34.1.0/meta.toml, _sources/plutus-tx-plugin/1.34.1.0/meta.toml, _sources/plutus-tx/1.34.1.0/meta.toml, _sources/prettyprinter-configurable/1.34.1.0/meta.toml
This fixes a bug in one of the Plutus Core builtins.
=> Kwxm/plutus/1.34.1.0 (bugfix)

_sources/typed-protocols-examples/0.4.0.0/meta.toml
From https://github.com/input-output-hk/typed-protocols at cd80ff771156ba882a553de3f40ff16ccb6ca588
=> Added typed-protocols-examples-0.4.0.0

_sources/cuddle/0.3.2.1/meta.toml
From https://github.com/input-output-hk/cuddle at 609bf9c3a2c4eae6cac0455d744b00e2731eda0e
=> Added cuddle-0.3.2.1

_sources/cardano-node/9.2.0/meta.toml, _sources/trace-dispatcher/2.6.0/meta.toml, _sources/trace-forward/2.2.7/meta.toml
From https://github.com/IntersectMBO/cardano-node at 415282dc66f08ff540067e74a24ca65ac9e44808
=> Added cardano-node-9.2.0

_sources/ekg-forward/0.6/meta.toml
Add ekg-forward-0.6:
* from https://github.com/input-output-hk/ekg-forward
* at `180df580ad404c0a189b6a6c3f0bde996de736d5`
=> Add ekg-forward-0.6

_sources/cardano-node/9.2.1/meta.toml
From https://github.com/IntersectMBO/cardano-node at 5d3da8ac771ee5ed424d6c78473c11deabb7a1f3
=> Added cardano-node-9.2.1

_sources/typed-protocols-cborg/0.3.0.0/meta.toml, _sources/typed-protocols-examples/0.5.0.0/meta.toml, _sources/typed-protocols-stateful-cborg/0.3.0.0/meta.toml, _sources/typed-protocols-stateful/0.3.0.0/meta.toml, _sources/typed-protocols/0.3.0.0/meta.toml
- **Added typed-protocols-0.3.0.0**
- **Added typed-protocols-cborg-0.3.0.0**
- **Added typed-protocols-stateful-0.3.0.0**
- **Added typed-protocols-stateful-cborg-0.3.0.0**
- **Added typed-protocols-examples-0.5.0.0**
=> coot/typed protocols 0.3.0.0

_sources/cardano-lmdb/0.4.0.2/meta.toml, _sources/diff-containers/1.3.0.0/meta.toml, _sources/fingertree-rm/1.0.0.3/meta.toml
=> Release some packages updated for GHC 9.10 only used in UTxO-HD

_sources/cardano-lmdb-simple/0.7.0.1/meta.toml
From https://github.com/input-output-hk/lmdb-simple at eae65e9caa1329f25ecdc97daf1fc8b96faafc5d
=> Added cardano-lmdb-simple-0.7.0.1

_sources/cardano-api/9.4.0.0/meta.toml
From https://github.com/IntersectMBO/cardano-api at 5557298db13912fe7602ac2f76670a3eff5508f6
Corresponding API PR: https://github.com/IntersectMBO/cardano-api/pull/653
=> Added cardano-api-9.4.0.0

_sources/ouroboros-consensus-cardano/0.20.0.0/meta.toml, _sources/ouroboros-consensus-diffusion/0.18.0.0/meta.toml, _sources/ouroboros-consensus-protocol/0.9.0.2/meta.toml, _sources/ouroboros-consensus/0.21.0.0/meta.toml
Release PR (needs to be merged first): https://github.com/IntersectMBO/ouroboros-consensus/pull/1283
=> Release Consensus packages for Node 10.0

_sources/cardano-ledger-shelley/1.14.1.0/meta.toml
From https://github.com/IntersectMBO/cardano-ledger at 96f7119d8405fc489e12131ec5ea9e21f47fa7cc
=> Added cardano-ledger-shelley-1.14.1.0

_sources/cardano-cli/10.0.0.0/meta.toml
From https://github.com/IntersectMBO/cardano-cli at 695b39bdc5497348887fac0eb1a16f9e7f22f04c
Related PR IntersectMBO/cardano-cli#933
=> release cardano-cli-10.0.0.0

_sources/cardano-node-chairman/10.0.0/meta.toml, _sources/cardano-node/10.0/meta.toml, _sources/cardano-submit-api/10.0/meta.toml, _sources/cardano-testnet/10.0.0/meta.toml, _sources/plutus-scripts-bench/1.0.4.1/meta.toml, _sources/trace-dispatcher/2.7.0/meta.toml, _sources/trace-forward/2.2.8/meta.toml, _sources/tx-generator/2.14.2/meta.toml
From https://github.com/IntersectMBO/cardano-node at 1abdd4748301349ece9c8f3a015aedd4e13c3a86
Related PR IntersectMBO/cardano-node#5998
=> release cardano-node 10.0

_sources/cardano-cli/10.1.0.0/meta.toml
From https://github.com/IntersectMBO/cardano-cli at 07384e916af7ade25e3ffb672b0204b277b8caf4
=> Added cardano-cli-10.1.0.0

_sources/cardano-cli/10.1.1.0/meta.toml
From https://github.com/IntersectMBO/cardano-cli at 7d3dd761830cf3c3ec73cf154058b2c4fd6fc37d
=> Added cardano-cli-10.1.1.0

_sources/trace-resources/0.2.3/meta.toml
From https://github.com/IntersectMBO/cardano-node at 4184f9297bf7306713bfbb8f39eef61c056198cc
=> Added trace-resources-0.2.3

_sources/cardano-api/10.2.0.0/meta.toml
From https://github.com/IntersectMBO/cardano-api at 49848cab62014fe8b75893bab72accceb86f8c3f
Corresponding API PR: https://github.com/IntersectMBO/cardano-api/pull/676
=> Added cardano-api-10.2.0.0

_sources/cardano-api/10.3.0.0/meta.toml
From https://github.com/IntersectMBO/cardano-api at e6912ab71dc2aa73082ec1a6fcb0fbb3e46e2828
=> Added cardano-api-10.3.0.0

_sources/cardano-ledger-conway/1.17.3.0/meta.toml
From https://github.com/IntersectMBO/cardano-ledger at d30a7ae828e802e98277c82e278e570955afc273
=> Added cardano-ledger-conway-1.17.3.0

_sources/cardano-ledger-alonzo/1.11.0.0/meta.toml, _sources/cardano-ledger-alonzo/1.11.0.0/revisions/1.cabal, _sources/plutus-core/1.37.0.0/meta.toml, _sources/plutus-ledger-api/1.37.0.0/meta.toml, _sources/plutus-tx-plugin/1.37.0.0/meta.toml, _sources/plutus-tx/1.37.0.0/meta.toml
=> Add 1.37.0.0 for Plutus packages

_sources/cardano-node/10.1.3/meta.toml
From https://github.com/IntersectMBO/cardano-node at 36871ba0cd3e86a5dbcfd6878cdb7168bb4e56a1
=> cardano-node 10.1.3

_sources/cardano-api/10.4.0.0/meta.toml
From https://github.com/IntersectMBO/cardano-api at c21fad9c46c66151b9361a336ef6c75b9f56b9a0
Corresponding API PR: https://github.com/IntersectMBO/cardano-api/pull/700
=> Added cardano-api-10.4.0.0

_sources/plutus-core/1.38.0.0/meta.toml, _sources/plutus-ledger-api/1.38.0.0/meta.toml, _sources/plutus-tx-plugin/1.38.0.0/meta.toml, _sources/plutus-tx/1.38.0.0/meta.toml
=> Plutus 1.38.0.0

_sources/cardano-ledger-conway-test/1.3.0.0/meta.toml, _sources/cardano-ledger-conway-test/1.3.0.0/revisions/1.cabal, _sources/cardano-ledger-shelley-ma-test/1.2.2.4/meta.toml, _sources/cardano-ledger-shelley-ma-test/1.2.2.4/revisions/1.cabal
* `cardano-ledger-shelley-ma-test-1.2.2.4` revision `1`
* `cardano-ledger-conway-test-1.3.0.0` revision `1`
=> Ledger revisions

_sources/cardano-api/10.5.0.0/meta.toml
From https://github.com/IntersectMBO/cardano-api at b00c675918f12fabca77ca121ed5c4f09baa55e8
=> Added cardano-api-10.5.0.0

_sources/cardano-lmdb-simple/0.8.0.0/meta.toml
From https://github.com/input-output-hk/lmdb-simple at 1200b75b1cf32e9a54b2cdf6c7bf9af6d1527ea0
=> Added cardano-lmdb-simple-0.8.0.0

_sources/ekg-forward/0.8/meta.toml
From https://github.com/input-output-hk/ekg-forward at d5cb6a1134ad78648fbbb54d5e0b64ad38c8841e
=> Added ekg-forward-0.8

_sources/cardano-ledger-conway/1.17.4.0/meta.toml
From https://github.com/IntersectMBO/cardano-ledger at IntersectMBO/cardano-ledger@df07b600c3f5dd8462f27450d59405b1cab6dc62
=> Added cardano-ledger-conway-1.17.4.0

_sources/cardano-ledger-conway/1.18.1.0/meta.toml
From https://github.com/IntersectMBO/cardano-ledger at d428f5bfcf60c9e0d9503f097175e61c968fefb9
=> Added cardano-ledger-conway-1.18.1.0

_sources/cardano-node/10.1.4/meta.toml
From https://github.com/IntersectMBO/cardano-node at 1f63dbf2ab39e0b32bf6901dc203866d3e37de08
=> Added cardano-node-10.1.4

_sources/cardano-api-gen/10.1.0.0/meta.toml, _sources/cardano-api/10.6.0.0/meta.toml
=> cardano-api-10.6.0.0 & cardano-api-gen-10.1.0.0

_sources/cardano-cli/10.3.0.0/meta.toml
From https://github.com/IntersectMBO/cardano-cli at 0c904ea3332acfdd2f063648400ab52e34bd2e9c
=> Added cardano-cli-10.3.0.0

_sources/plutus-core/1.38.0.0/meta.toml, _sources/plutus-core/1.38.0.0/revisions/2.cabal, flake.lock
=> plutus-core-1.38.0.0: Add upper bound for cardano-crypto

_sources/plutus-core/1.38.0.0/meta.toml, _sources/plutus-core/1.38.0.0/revisions/3.cabal
=> plutus-core-1.38.0.0: Restrict bounds on cardano-crypto-class

_sources/plutus-core/1.37.0.0/revisions/2.cabal
=> plutus-core-1.37.0.0: Restrict bounds on cardano-crypto-class

_sources/plutus-core/1.37.0.0/meta.toml, _sources/plutus-core/1.37.0.0/revisions/3.cabal, _sources/plutus-core/1.38.0.0/meta.toml, _sources/plutus-core/1.38.0.0/revisions/4.cabal
=> Restrict dependency on cardano-crypto

_sources/plutus-core/1.36.0.0/meta.toml, _sources/plutus-core/1.36.0.0/revisions/1.cabal
=> plutus-core-1.36.0.0: Restrict dependency on cardano-crypto

_sources/cardano-crypto/1.2.0/meta.toml
From https://github.com/IntersectMBO/cardano-crypto at 9152d0e74bf1d17781482bc6649e2079827a93aa
=> Added cardano-crypto-1.2.0

_sources/cardano-api/10.7.0.0/meta.toml
From https://github.com/IntersectMBO/cardano-api at 41ece2bc0fee984d50994e21ef8a30213a0abd7f
Corresponding API PR: https://github.com/IntersectMBO/cardano-api/pull/736
=> Added cardano-api-10.7.0.0

_sources/cardano-api/10.8.0.0/meta.toml
From https://github.com/IntersectMBO/cardano-api at 96dc68721cc96232afefe8433c3f3e17034472c1
=> Added cardano-api-10.8.0.0

_sources/ekg-forward/0.8.1/meta.toml
From https://github.com/input-output-hk/ekg-forward at 6896ddc16e576de7f7e1b3e928d1cce62dd00579
=> Added ekg-forward-0.8.1

_sources/cardano-cli/10.4.0.0/meta.toml
From https://github.com/IntersectMBO/cardano-cli at 72bae1799052b8563edc3d07f9f496ee53cb3494
=> Added cardano-cli-10.4.0.0

_sources/ouroboros-consensus-cardano/0.21.0.1/meta.toml, _sources/ouroboros-consensus-diffusion/0.20.0.0/meta.toml
=> Consensus backports for 10.2

CODEOWNERS, _sources/cardano-wallet-read/1.0.0.0/meta.toml, flake.nix
From https://github.com/cardano-foundation/cardano-wallet-agda at 099b4fb3c672d94c31979fe8d436eadc6fd7ed15
=> Add `cardano-wallet-read-1.0.0.0`

_sources/ouroboros-network/0.19.0.3/meta.toml
From https://github.com/intersectmbo/ouroboros-network at d405f0e0fc5393e8421ada87c85098a7a4fea6b6
=> Added ouroboros-network-0.19.0.3

_sources/cardano-api/10.7.0.0/meta.toml, _sources/cardano-api/10.7.0.0/revisions/1.cabal, _sources/cardano-api/10.8.0.0/meta.toml, _sources/cardano-api/10.8.0.0/revisions/1.cabal
- cardano-api-10.8 revision: allow ouroboros-consensus-diffusion-0.20
- cardano-api-10.7 revision: allow ouroboros-consensus-diffusion-0.20
=> cardano-api revisions

_sources/cardano-node/10.2.1/meta.toml, _sources/trace-dispatcher/2.8.1/meta.toml, _sources/trace-forward/2.2.10/meta.toml
From https://github.com/IntersectMBO/cardano-node at 52b708f37cd3dc92a188717deae2a6a60117f696
=> Added cardano-node-10.2.1

_sources/latex-svg-image/0.2.0.0.0.1/meta.toml, _sources/latex-svg-image/0.2.0.0.0.1/revisions/3.cabal, _sources/quickcheck-monoids/0.1.0.1/meta.toml, _sources/quickcheck-monoids/0.1.0.1/revisions/1.cabal
=> Bump two base revisions

_sources/monoidal-synchronisation/0.1.0.6/meta.toml, _sources/monoidal-synchronisation/0.1.0.6/revisions/1.cabal, _sources/network-mux/0.6/meta.toml, _sources/network-mux/0.6/revisions/1.cabal, _sources/ouroboros-network-api/0.12.0.0/meta.toml, _sources/ouroboros-network-api/0.12.0.0/revisions/1.cabal, _sources/ouroboros-network-framework/0.16.0.0/meta.toml, _sources/ouroboros-network-framework/0.16.0.0/revisions/1.cabal, _sources/ouroboros-network-mock/0.1.1.2/meta.toml, _sources/ouroboros-network-mock/0.1.1.2/revisions/1.cabal, _sources/ouroboros-network-protocols/0.13.0.0/meta.toml, _sources/ouroboros-network-protocols/0.13.0.0/revisions/1.cabal, _sources/ouroboros-network-testing/0.8.1.0/meta.toml, _sources/ouroboros-network-testing/0.8.1.0/revisions/1.cabal, _sources/ouroboros-network/0.19.0.3/meta.toml, _sources/ouroboros-network/0.19.0.3/revisions/1.cabal
=> Bump base dependencies on a bunch of ouroboros-network related packages

_sources/cardano-api/10.10.0.0/meta.toml
From https://github.com/IntersectMBO/cardano-api at caf5632b3ccf2e3662b4ddff47aec9f7e7bb0680
=> Added cardano-api-10.10.0.0

_sources/ouroboros-consensus-cardano/0.21.0.1/meta.toml, _sources/ouroboros-consensus-cardano/0.21.0.1/revisions/1.cabal, _sources/ouroboros-consensus-diffusion/0.20.0.0/meta.toml, _sources/ouroboros-consensus-diffusion/0.20.0.0/revisions/1.cabal, _sources/ouroboros-consensus-protocol/0.10.0.0/meta.toml, _sources/ouroboros-consensus-protocol/0.10.0.0/revisions/1.cabal, _sources/ouroboros-consensus/0.22.0.0/meta.toml, _sources/ouroboros-consensus/0.22.0.0/revisions/1.cabal, _sources/sop-extras/0.2.1.0/meta.toml, _sources/sop-extras/0.2.1.0/revisions/1.cabal, _sources/strict-sop-core/0.1.2.0/meta.toml, _sources/strict-sop-core/0.1.2.0/revisions/1.cabal
=> Bump a set of base dependency revisions.

_sources/ouroboros-consensus-cardano/0.21.0.1/meta.toml, _sources/ouroboros-consensus-cardano/0.21.0.1/revisions/2.cabal
=> ouroboros-consensus-cardano/0.21.0.1: Update base dependency

_sources/cardano-api/10.10.0.0/meta.toml, _sources/cardano-api/10.10.0.0/revisions/1.cabal, _sources/cardano-ping/0.7.0.0/meta.toml, _sources/cardano-ping/0.7.0.0/revisions/1.cabal
=> Update a couple of base dependencies

_sources/plutus-core/1.42.0.0/meta.toml, _sources/plutus-ledger-api/1.42.0.0/meta.toml, _sources/plutus-tx-plugin/1.42.0.0/meta.toml, _sources/plutus-tx/1.42.0.0/meta.toml
=> Plutus Release 1.42.0.0

_sources/iohk-monitoring/0.2.1.0/meta.toml
From https://github.com/input-output-hk/iohk-monitoring-framework/ at b514257f6d26ccaca72789dfc0a9e6a085598af4
=> Added iohk-monitoring-0.2.1.0

_sources/cardano-api/10.8.0.0/meta.toml, _sources/cardano-api/10.8.0.0/revisions/2.cabal, _sources/cardano-cli/10.4.0.0/meta.toml, _sources/cardano-cli/10.4.0.0/revisions/1.cabal
=> Bump upper bound on base dependency

_sources/ouroboros-consensus-cardano/0.20.0.0/meta.toml, _sources/ouroboros-consensus-cardano/0.20.0.0/revisions/1.cabal, _sources/ouroboros-consensus-diffusion/0.18.0.0/meta.toml, _sources/ouroboros-consensus-diffusion/0.18.0.0/revisions/1.cabal, _sources/ouroboros-consensus-protocol/0.9.0.2/meta.toml, _sources/ouroboros-consensus-protocol/0.9.0.2/revisions/1.cabal, _sources/ouroboros-consensus/0.21.0.0/meta.toml, _sources/ouroboros-consensus/0.21.0.0/revisions/1.cabal
=> Bump base dependencies on consensus packages

_sources/network-mux/0.4.5.3/meta.toml, _sources/network-mux/0.4.5.3/revisions/1.cabal, _sources/ouroboros-network-api/0.10.0.0/meta.toml, _sources/ouroboros-network-api/0.10.0.0/revisions/1.cabal, _sources/ouroboros-network-framework/0.13.2.5/meta.toml, _sources/ouroboros-network-framework/0.13.2.5/revisions/1.cabal, _sources/ouroboros-network-protocols/0.11.0.0/meta.toml, _sources/ouroboros-network-protocols/0.11.0.0/revisions/1.cabal, _sources/ouroboros-network-testing/0.7.0.0/meta.toml, _sources/ouroboros-network-testing/0.7.0.0/revisions/1.cabal, _sources/ouroboros-network/0.17.1.2/meta.toml, _sources/ouroboros-network/0.17.1.2/revisions/1.cabal
=> Bump base dependency for network related packages

_sources/cardano-crypto-class/2.2.1.0/meta.toml, _sources/cardano-strict-containers/0.1.4.0/meta.toml
=> cardano-crypto-class-2.2.1.0 and cardano-strict-containers-0.1.4.0

_sources/cardano-api/10.11.1.0/meta.toml
From https://github.com/IntersectMBO/cardano-api at 66d6ac6ff641cc4ff059ce05501d18b722e851de
=> Added cardano-api-10.11.1.0

_sources/byron-spec-ledger/1.1.0.0/meta.toml, _sources/cardano-crypto-test/1.6.0.0/meta.toml, _sources/cardano-crypto-wrapper/1.6.0.0/meta.toml, _sources/cardano-data/1.2.4.0/meta.toml, _sources/cardano-ledger-allegra/1.7.0.0/meta.toml, _sources/cardano-ledger-alonzo-test/1.3.1.0/meta.toml, _sources/cardano-ledger-alonzo/1.13.0.0/meta.toml, _sources/cardano-ledger-api/1.11.0.0/meta.toml, _sources/cardano-ledger-babbage-test/1.3.1.0/meta.toml, _sources/cardano-ledger-babbage/1.11.0.0/meta.toml, _sources/cardano-ledger-binary/1.6.0.0/meta.toml, _sources/cardano-ledger-byron-test/1.5.2.1/meta.toml, _sources/cardano-ledger-byron/1.0.1.0/meta.toml, _sources/cardano-ledger-byron/1.0.1.0/revisions/1.cabal, _sources/cardano-ledger-byron/1.0.2.0/meta.toml, _sources/cardano-ledger-byron/1.0.2.0/revisions/1.cabal, _sources/cardano-ledger-byron/1.1.0.0/meta.toml, _sources/cardano-ledger-conway-test/1.3.1.0/meta.toml, _sources/cardano-ledger-conway/1.19.0.0/meta.toml, _sources/cardano-ledger-core/1.17.0.0/meta.toml, _sources/cardano-ledger-mary/1.8.0.0/meta.toml, _sources/cardano-ledger-shelley-ma-test/1.3.0.0/meta.toml, _sources/cardano-ledger-shelley-test/1.6.0.0/meta.toml, _sources/cardano-ledger-shelley/1.16.0.0/meta.toml, _sources/cardano-protocol-tpraos/1.4.0.0/meta.toml, _sources/small-steps/1.1.1.0/meta.toml
=> Release cardano-ledger packages in preparation for 10.3

_sources/cardano-cli/10.5.0.0/meta.toml
From https://github.com/IntersectMBO/cardano-cli at 8e21aaa19c35e724b8fc8205098f995f20508b1c
=> Added cardano-cli-10.5.0.0

flake.nix
With recent versions of nixpkgs GHC 8.10 seems to be broken on macOS.
See https://gitlab.haskell.org/ghc/ghc/-/issues/25608
=> Disable macOS builds with GHC 8.10

_sources/ouroboros-consensus-cardano/0.22.0.0/meta.toml, _sources/ouroboros-consensus-diffusion/0.21.0.0/meta.toml, _sources/ouroboros-consensus-protocol/0.11.0.0/meta.toml, _sources/ouroboros-consensus/0.23.0.0/meta.toml, _sources/sop-extras/0.2.2.0/meta.toml, _sources/strict-sop-core/0.1.3.0/meta.toml
=> Consensus release for node 10.3

_sources/ekg-forward/0.9/meta.toml
From https://github.com/input-output-hk/ekg-forward at e372f6d8b6bc493ec64c1fbee8a1d2fcfa41b056
=> Added ekg-forward-0.9

_sources/plutus-core/1.44.0.0/meta.toml, _sources/plutus-ledger-api/1.44.0.0/meta.toml, _sources/plutus-tx-plugin/1.44.0.0/meta.toml, _sources/plutus-tx/1.44.0.0/meta.toml
=> Plutus Release 1.44.0.0

_sources/cardano-api/10.13.0.0/meta.toml
From https://github.com/IntersectMBO/cardano-api at c8aa79fabf0069d08fb41743beb81dfee8fc8625
=> Added cardano-api-10.13.0.0

_sources/network-mux/0.7/meta.toml, _sources/network-mux/0.7/revisions/1.cabal, _sources/ouroboros-network-api/0.13.0.0/meta.toml, _sources/ouroboros-network-api/0.13.0.0/revisions/1.cabal, _sources/ouroboros-network-framework/0.17.0.0/meta.toml, _sources/ouroboros-network-framework/0.17.0.0/revisions/1.cabal, _sources/ouroboros-network-protocols/0.14.0.0/meta.toml, _sources/ouroboros-network-protocols/0.14.0.0/revisions/1.cabal, _sources/ouroboros-network/0.20.1.0/meta.toml, _sources/ouroboros-network/0.20.1.0/revisions/1.cabal
=> Bump base dependencies.

_sources/cardano-ping/0.8.0.0/meta.toml, _sources/cardano-ping/0.8.0.0/revisions/1.cabal
=> cardano-ping/0.8.0.0: Bump base dependency

_sources/cardano-lmdb/0.4.0.3/meta.toml, _sources/diff-containers/1.3.0.0/meta.toml, _sources/diff-containers/1.3.0.0/revisions/1.cabal, _sources/fingertree-rm/1.0.0.4/meta.toml
=> Revise UTxO-HD related packages for GHC 9.12

_sources/cardano-lmdb-simple/0.8.0.1/meta.toml
From https://github.com/input-output-hk/lmdb-simple at 8b5149bd6e281da516f06e828b3948df0257fc94
=> Added cardano-lmdb-simple-0.8.0.1

_sources/cardano-api/10.13.1.0/meta.toml
From https://github.com/IntersectMBO/cardano-api at a8c9de1f4230036abbb4ab20466618134b9e74fd
=> Added cardano-api-10.13.1.0

_sources/cardano-node-chairman/10.0.2/meta.toml, _sources/cardano-node/10.3.0/meta.toml, _sources/cardano-submit-api/10.1.1/meta.toml, _sources/cardano-testnet/10.0.1/meta.toml, _sources/cardano-tracer/0.3.2/meta.toml, _sources/trace-dispatcher/2.9/meta.toml, _sources/trace-forward/2.2.11/meta.toml, flake.nix
=> cardano-node-10.3.0

_sources/cardano-crypto-class/2.2.2.0/meta.toml, _sources/cardano-crypto-praos/2.2.1.0/meta.toml, _sources/cardano-crypto-tests/2.2.1.0/meta.toml
This release is needed for Hydra
CC @locallycompact
=> Release crypto packages

_sources/cardano-client/0.5.1.0/meta.toml, _sources/cardano-client/0.5.1.0/revisions/1.cabal
=> cardano-client/0.5.1.0: Bump base dependency

_sources/cardano-node/10.3.1/meta.toml
From https://github.com/intersectmbo/cardano-node at b3f237b75e64f4d8142af95b053e2828221d707f
=> Added cardano-node-10.3.1

_sources/plutus-core/1.45.0.0/meta.toml, _sources/plutus-ledger-api/1.45.0.0/meta.toml, _sources/plutus-tx-plugin/1.45.0.0/meta.toml, _sources/plutus-tx/1.45.0.0/meta.toml
=> Plutus release/1.45.0.0

_sources/cardano-api/10.14.0.0/meta.toml
From https://github.com/IntersectMBO/cardano-api at d32df4d329d4a3962287d1ae0d32f6e5f2a40b6b
=> Added cardano-api-10.14.0.0

_sources/cardano-cli/10.8.0.0/meta.toml, flake.lock
From https://github.com/IntersectMBO/cardano-cli at 685970733dc4ef5838967cb7cfb6d3fe4c2a2b06
=> Added cardano-cli-10.8.0.0

_sources/ouroboros-consensus-cardano/0.25.0.0/meta.toml, _sources/ouroboros-consensus-diffusion/0.22.0.1/meta.toml, _sources/ouroboros-consensus-protocol/0.12.0.0/meta.toml, _sources/ouroboros-consensus/0.26.0.0/meta.toml
=> Release consensus for node 10.4

_sources/cardano-api/10.14.1.0/meta.toml
From https://github.com/IntersectMBO/cardano-api at e63857a481806fe55765996b65351e26d11018ad
=> Added cardano-api-10.14.1.0

_sources/cardano-node/10.4.0/meta.toml
From https://github.com/IntersectMBO/cardano-node at 91e8d93460ef79b87bf936e534373270e6196112
=> Added cardano-node-10.4.0

_sources/ouroboros-consensus/0.26.0.1/meta.toml
Release PR: https://github.com/IntersectMBO/ouroboros-consensus/pull/1486
=> Added ouroboros-consensus-0.26.0.1

_sources/cardano-api/10.16.0.0/meta.toml
From https://github.com/IntersectMBO/cardano-api at 2bc2e9ae56abd3b1f9d51bc48334c9b5bec62b7b
=> Added cardano-api-10.16.0.0

_sources/cardano-cli/10.9.0.0/meta.toml
From https://github.com/IntersectMBO/cardano-cli at e13f84d9fc9cafa293e88f017592d994ca1b12a2
=> Added cardano-cli-10.9.0.0

README.md, flake.nix
=> drop ghc810 support from CHaP

_sources/cardano-ledger-binary/1.3.4.0/meta.toml, _sources/cardano-ledger-binary/1.3.4.0/revisions/2.cabal, _sources/cardano-ledger-binary/1.4.0.0/meta.toml, _sources/cardano-ledger-binary/1.4.0.0/revisions/2.cabal, _sources/cardano-ledger-binary/1.5.0.0/meta.toml, _sources/cardano-ledger-binary/1.5.0.0/revisions/1.cabal, _sources/cardano-ledger-binary/1.6.0.0/meta.toml, _sources/cardano-ledger-binary/1.6.0.0/revisions/1.cabal, _sources/cuddle/0.4.0.0/meta.toml
From https://github.com/input-output-hk/cuddle at 809b3ff4df986c506732fc77e6bb9b3e6ec24835
related: https://github.com/IntersectMBO/cardano-ledger/pull/4996
=> Added cuddle-0.4.0.0

_sources/ouroboros-consensus-cardano/0.25.1.0/meta.toml, _sources/ouroboros-consensus-diffusion/0.23.0.0/meta.toml, _sources/ouroboros-consensus-protocol/0.12.0.0/meta.toml, _sources/ouroboros-consensus-protocol/0.12.0.0/revisions/1.cabal, _sources/ouroboros-consensus/0.27.0.0/meta.toml
=> Consensus for node 10.5

_sources/cardano-api/10.16.1.0/meta.toml
From https://github.com/IntersectMBO/cardano-api at 556d93d922cf43f92e4e271b14407422448915b8
=> Added cardano-api-10.16.1.0

_sources/cardano-cli/10.10.0.0/meta.toml
From https://github.com/IntersectMBO/cardano-cli at cbb3947689d39388a60b4fa635437d9e76a20a8b
=> Added cardano-cli-10.10.0.0

_sources/iohk-monitoring/0.2.1.1/meta.toml
From https://github.com/input-output-hk/iohk-monitoring-framework at `dfce33976a1b82e84f582187b7db5aeb4d8d55a5`.
=> Added iohk-monitoring-0.2.1.1

_sources/cardano-client/0.5.2.0/meta.toml
From https://github.com/intersectmbo/ouroboros-network at 97ffb8c5674a240bbd41bfe184bd6ee1509450ed
=> Added cardano-client-0.5.2.0

_sources/cardano-api/10.16.2.0/meta.toml
From https://github.com/IntersectMBO/cardano-api at 9eafbbed6eab2517672870ef51682aa111c1a251
=> Added cardano-api-10.16.2.0

_sources/cuddle/0.5.0.0/meta.toml
From https://github.com/input-output-hk/cuddle at d0dad49a83389220c8ee8265dbcdd5641cd218e6
=> Added cuddle-0.5.0.0

_sources/hedgehog-extras/0.7.2.0/meta.toml
From https://github.com/input-output-hk/hedgehog-extras at b813e9d68d4cd9e7f91c662f75a8c4f003cb3aa3
=> Add `hedgehog-extras-0.7.2.0`

_sources/cardano-api/10.17.0.0/meta.toml
From https://github.com/IntersectMBO/cardano-api at f9dba57edcbbcef242c916c708811dd61b6719e7
=> Added cardano-api-10.17.0.0

_sources/plutus-core/1.47.0.0/meta.toml, _sources/plutus-ledger-api/1.47.0.0/meta.toml, _sources/plutus-metatheory/1.47.0.0/meta.toml, _sources/plutus-tx-plugin/1.47.0.0/meta.toml, _sources/plutus-tx/1.47.0.0/meta.toml
=> Plutus Release 1.47.0.0

_sources/network-mux/0.8.0.1/meta.toml, _sources/network-mux/0.8.0.1/revisions/1.cabal, _sources/ouroboros-network-api/0.14.0.0/meta.toml, _sources/ouroboros-network-api/0.14.0.0/revisions/1.cabal, _sources/ouroboros-network-framework/0.18.0.1/meta.toml, _sources/ouroboros-network-framework/0.18.0.1/revisions/1.cabal, _sources/ouroboros-network-protocols/0.14.0.1/meta.toml, _sources/ouroboros-network-protocols/0.14.0.1/revisions/1.cabal, _sources/ouroboros-network/0.21.2.0/meta.toml, _sources/ouroboros-network/0.21.2.0/revisions/1.cabal
=> Bump a set of network base dependencies.

_sources/network-mux/0.8.0.1/meta.toml, _sources/network-mux/0.8.0.1/revisions/2.cabal
=> network-mux/0.8.0.1: Bump base dependency in all components

_sources/network-mux/0.8.0.2/meta.toml, _sources/ouroboros-network-api/0.14.1.0/meta.toml, _sources/ouroboros-network-framework/0.18.0.2/meta.toml, _sources/ouroboros-network-protocols/0.14.0.2/meta.toml, _sources/ouroboros-network/0.21.3.0/meta.toml
IntersectMBO/ouroboros-network#5162
=> ouroboros-network 0.21.3

_sources/plutus-core/1.52.0.0/meta.toml, _sources/plutus-ledger-api/1.52.0.0/meta.toml, _sources/plutus-metatheory/1.52.0.0/meta.toml, _sources/plutus-tx-plugin/1.52.0.0/meta.toml, _sources/plutus-tx/1.52.0.0/meta.toml
=> Plutus Release 1.52.0.0

_sources/cardano-lmdb-simple/0.8.1.0/meta.toml
From https://github.com/input-output-hk/lmdb-simple at fb732fdc81e45667b948d0b56427076e81bf8604
=> Added cardano-lmdb-simple-0.8.1.0

_sources/cardano-tracer/0.3.4/meta.toml, _sources/trace-dispatcher/2.10.0/meta.toml, _sources/trace-forward/2.3.0/meta.toml
- Added cardano-tracer-0.3.4
- Added trace-dispatcher-2.10.0
- Added trace-forward-0.2.3
=> bench release 2025-08-22

_sources/ntp-client/0.0.1.6/meta.toml, _sources/ntp-client/0.0.1.6/revisions/2.cabal, _sources/ouroboros-network-framework/0.19.1.0/meta.toml, _sources/ouroboros-network/0.22.3.0/meta.toml, _sources/quickcheck-monoids/0.1.0.3/meta.toml
- **Added ouroboros-network-0.22.3.0**
- **Added ouroboros-network-framework-0.19.1.0**
- **Added quickcheck-monoids-0.1.0.3**
=> ouroboros-network-0.22.3.0

_sources/kes-agent-crypto/0.1.0.0/meta.toml, _sources/kes-agent/0.2.0.0/meta.toml
Adds:
- `kes-agent-0.2.0.0` at `abe5aafc90fc837b0941504a89f7a207b589fd83`
- `kes-agent-crypto-0.1.0.0` at `abe5aafc90fc837b0941504a89f7a207b589fd83`
=> kes-agent-0.2.0.0 and kes-agent-crypto-0.1.0.0

_sources/kes-agent/0.2.0.1/meta.toml
From https://github.com/input-output-hk/kes-agent at d7c27bfbf8e216920c40ed84b276d2d789c3c5ef
=> Added kes-agent-0.2.0.1

CODEOWNERS, _sources/cardano-prometheus-tracker/0.1.0.0/meta.toml
From: https://github.com/input-output-hk/cardano-automation
commit: `d2017cf99d9c98b0acb4383d03ecfa8f9fdc2aac`
=> New package: cardano-prometheus-tracker-0.1.0.0
